/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTLabels)
+ (id)clearLabelWithFont:(id)fp8 color:(id)fp12 shadowType:(int)fp16;
+ (id)clearLabelWithFont:(id)fp8 color:(id)fp12;
+ (id)clearLabel;
- (float)actualFontSize;
- (void)sizeToFitWithMaxWidth:(float)fp8;
- (void)sizeHeightToFitWithWidth:(float)fp8 numberOfLines:(int)fp12;
- (void)setFont:(id)fp8 color:(id)fp12 shadowType:(int)fp16;
@end

