/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (GIPShowInView)
- (void)showFromRect:(struct CGRect)fp8 inRotatedView:(id)fp24 animated:(BOOL)fp28;
@end

