/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTErrors)
+ (id)errorWithDRMStatus:(int)fp8;
+ (id)errorWithDRMEvent:(int)fp8 attributes:(id)fp12;
+ (id)errorWithPlaybackError:(int)fp8;
+ (id)errorWithCode:(int)fp8 cause:(id)fp12;
+ (id)errorWithCode:(int)fp8;
- (BOOL)isAuthenticationError;
- (id)logDescription;
@end

