/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Crypto)
- (id)ccCrypt:(id)fp8 operation:(unsigned int)fp12 algorithm:(unsigned int)fp16 options:(unsigned int)fp20 iv:(id)fp24;
@end

