/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Resize)
- (struct CGAffineTransform)transformForOrientation:(struct CGSize)fp8;
- (id)resizedImage:(struct CGSize)fp8 transform:(struct CGAffineTransform)fp16 drawTransposed:(BOOL)fp40 interpolationQuality:(int)fp44;
- (id)resizedImageWithContentMode:(int)fp8 bounds:(struct CGSize)fp12 interpolationQuality:(int)fp20;
- (id)resizedImage:(struct CGSize)fp8 interpolationQuality:(int)fp16;
- (id)thumbnailImage:(int)fp8 transparentBorder:(unsigned int)fp12 cornerRadius:(unsigned int)fp16 interpolationQuality:(int)fp20;
- (id)croppedImage:(struct CGRect)fp8;
@end

