/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (TBXML_Compression)
+ (id)dataWithBase64EncodedString:(id)fp8;
+ (id)dataWithUncompressedContentsOfFile:(id)fp8;
- (id)gzipInflate;
- (id)gzipDeflate;
- (id)base64EncodingWithLineLength:(unsigned int)fp8;
- (id)base64Encoding;
- (id)initWithBase64EncodedString:(id)fp8;
@end

