/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTNotifications)
+ (id)notificationWithName:(id)fp8 video:(id)fp12 mediaTime:(double)fp16;
+ (id)notificationWithName:(id)fp8 subscription:(id)fp12 subscribed:(BOOL)fp16;
- (double)mediaTimeValue;
- (BOOL)subscribedValue;
@end

