/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTImageManipulation)
+ (struct CGSize)adjustSizeFromPointsToPixels:(struct CGSize)fp8;
+ (struct CGSize)shrinkSize:(struct CGSize)fp8 toAspectRatio:(float)fp16;
+ (struct CGSize)growSize:(struct CGSize)fp8 toAspectRatio:(float)fp16;
- (struct CGAffineTransform)transformForOrientation:(struct CGSize)fp8;
- (id)imageResizedToSize:(struct CGSize)fp8 transform:(struct CGAffineTransform)fp16 drawTransposed:(BOOL)fp40 interpolationQuality:(int)fp44;
- (id)imageResizedToSize:(struct CGSize)fp8 interpolationQuality:(int)fp16;
- (id)imageCroppedToFacesWithHeight:(float)fp8;
- (id)imageCroppedToRect:(struct CGRect)fp8;
- (id)imageScaledToFillSize:(struct CGSize)fp8;
@end

