/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTButtons)
+ (id)barButtonWithTitle:(id)fp8 resourceLoader:(id)fp12;
+ (id)buttonWithStyle:(int)fp8 title:(id)fp12 resourceLoader:(id)fp16;
@end

