/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UILabel;

@interface AudiencePickerCell : _AVAudioSessionCategoryPlayback
{
    UILabel *countLabel_;
}

- (void)setSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (void)setCount:(id)fp8;

@end

