/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UILabel;

@interface AudienceSectionHeaderView : _AVAudioSessionCategoryPlayback
{
    UILabel *textLabel_;
}

- (void)drawRect:(struct CGRect)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithText:(id)fp8 width:(float)fp12;

@end

