/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray;

@interface AudienceScrollView : _AVAudioSessionCategoryPlayback
{
    NSMutableArray *metaAudienceCells_;
    NSMutableArray *metaCircles_;
    NSMutableArray *audienceCells_;
    NSMutableArray *circles_;
    BOOL editable_;
    id <AudienceScrollViewDelegate> audienceDelegate_;
    BOOL wrapCells_;
}

- (void)setWrapCells:(BOOL)fp8;
- (BOOL)wrapCells;
- (void)setAudienceDelegate:(id)fp8;
- (id)audienceDelegate;
- (void)cellToggled:(id)fp8;
- (void)metaCellToggled:(id)fp8;
- (void)flushAudienceCells;
- (void)flushMetaAudienceCells;
- (void)layoutCells;
- (void)addCircleNoLayout:(id)fp8;
- (void)addMetaCircleNoLayout:(id)fp8;
- (void)drawMetaAudienceCells;
- (void)drawAudienceCells;
- (void)drawAllCells;
- (void)removeCircle:(id)fp8;
- (void)removeMetaCircle:(id)fp8;
- (void)addCircle:(id)fp8;
- (void)addMetaCircle:(id)fp8;
- (void)setCircles:(id)fp8;
- (void)setMetaCircles:(id)fp8;
- (void)dealloc;
- (id)initWithMetaCircles:(id)fp8 circles:(id)fp12 editable:(BOOL)fp16;

@end

