/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton;

@interface AudienceCell : _AVAudioSessionCategoryPlayback
{
    UIButton *backgroundButton_;
    UIButton *foregroundButton_;
    BOOL selected_;
}

- (BOOL)selected;
- (void)addTarget:(id)fp8 action:(SEL)fp12;
- (void)setSelected:(BOOL)fp8;
- (void)toggleSelected;
- (void)autoResize;
- (void)setupButtonWithText:(id)fp8;
- (void)dealloc;
- (id)initWithSystemStyle:(int)fp8 selected:(BOOL)fp12 editable:(BOOL)fp16;
- (id)initWithText:(id)fp8 selected:(BOOL)fp12 editable:(BOOL)fp16;

@end

