/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface DefaultSHKConfigurator : _AVAudioSessionCategoryPlayback
{
}

- (id)allowAutoShare;
- (id)allowOffline;
- (id)authPrefix;
- (id)favsPrefixKey;
- (id)maxFavCount;
- (id)usePlaceholders;
- (id)sharersPlistName;
- (id)sharedWithSignature;
- (id)shareMenuAlphabeticalOrder;
- (id)modalTransitionStyle;
- (id)modalPresentationStyle;
- (id)formBgColorBlue;
- (id)formBgColorGreen;
- (id)formBgColorRed;
- (id)formFontColorBlue;
- (id)formFontColorGreen;
- (id)formFontColorRed;
- (id)barTintForView:(id)fp8;
- (id)barStyle;
- (id)foursquareV2RedirectURI;
- (id)foursquareV2ClientId;
- (id)linkedInCallbackUrl;
- (id)linkedInSecret;
- (id)linkedInConsumerKey;
- (id)bitLyKey;
- (id)bitLyLogin;
- (id)flickrCallbackUrl;
- (id)flickrSecretKey;
- (id)flickrConsumerKey;
- (id)evernoteSecret;
- (id)evernoteConsumerKey;
- (id)evernoteNetStoreURLBase;
- (id)evernoteUserStoreURL;
- (id)twitterUsername;
- (id)twitterUseXAuth;
- (id)twitterCallbackUrl;
- (id)twitterSecret;
- (id)twitterConsumerKey;
- (id)readItLaterKey;
- (id)googlePlusClientSecret;
- (id)googlePlusClientId;
- (id)facebookLocalAppId;
- (id)facebookAppId;
- (id)vkontakteAppId;
- (id)appURL;
- (id)appName;
- (id)getAppName;

@end

