/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "AVAudioSessionDelegate-Protocol.h"
#import "GIPAudioPlayerDelegate-Protocol.h"

@class AVAudioSession, GIPAudioPlayer;

@interface GIPAudioController : _AVAudioSessionCategoryPlayback <GIPAudioPlayerDelegate, AVAudioSessionDelegate>
{
    GIPAudioPlayer *player_;
    unsigned long audioMode_;
    unsigned long inactiveAudioMode_;
    int iPodPlaybackState_;
    BOOL resumePlayingAfterAudio_;
    BOOL isInterrupted_;
    BOOL activeWhenInterrupted_;
    BOOL useSpeakerOutput_;
    BOOL allowBluetoothInput_;
    AVAudioSession *audioSession_;
    BOOL isActive_;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)sharedInstance;
- (void)setIsActive:(BOOL)fp8;
- (BOOL)isActive;
- (void)setAudioSession:(id)fp8;
- (id)audioSession;
- (BOOL)allowBluetoothInput;
- (BOOL)useSpeakerOutput;
- (void)setResumePlayingAfterAudio:(BOOL)fp8;
- (BOOL)resumePlayingAfterAudio;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)audioRouteDidChange:(id)fp8;
- (void)setUseSpeakerOutput:(BOOL)fp8;
- (void)updateAudioRoute;
- (void)inputIsAvailableChanged:(BOOL)fp8;
- (void)endInterruptionWithFlags:(unsigned int)fp8;
- (void)endInterruption;
- (void)beginInterruption;
- (void)notifyPlaybackComplete:(id)fp8;
- (void)playbackDidComplete:(id)fp8;
- (void)stopPlayback;
- (BOOL)playSound:(id)fp8 identifier:(id)fp12;
- (BOOL)playSound:(id)fp8;
- (void)setAllowBluetoothInput:(BOOL)fp8;
- (BOOL)isInitialized;
- (BOOL)audioInputAvailable;
- (BOOL)hasExternalMicrophone;
- (BOOL)wasMusicPlaying;
- (BOOL)isMusicPlaying;
- (BOOL)isPlaying;
- (BOOL)audioSessionSetInactive;
- (BOOL)setAudioSessionMode:(unsigned long)fp8;
- (unsigned long)audioSessionMode;
- (BOOL)audioSessionSetActive;
- (BOOL)audioInit;
- (BOOL)audioInitIfAvailable;
- (void)dealloc;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

