/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIView;

@interface GIPContainerActionSheet : _AVAudioSessionCategoryPlayback
{
    UIView *containedView_;
}

- (id)containedView;
- (void)sizeToFit;
- (void)layoutSubviews;
- (BOOL)respondsToSelector:(SEL)fp8;
- (void)showFromRect:(struct CGRect)fp8 inView:(id)fp24 animated:(BOOL)fp28;
- (id)initWithContainedView:(id)fp8 delegate:(id)fp12;

@end

