/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPCrashReportHandlerProtocol-Protocol.h"
#import "MFMailComposeViewControllerDelegate-Protocol.h"

@class NSArray, NSString, UIViewController;

@interface GIPCrashReportMailHandler : _AVAudioSessionCategoryPlayback <GIPCrashReportHandlerProtocol, MFMailComposeViewControllerDelegate>
{
    UIViewController *rootViewController_;
    NSString *recipientEmail_;
    NSString *appName_;
    NSString *appVersion_;
    BOOL storeUnsentReports_;
    NSArray *crashReports_;
}

- (void)setStoreUnsentReports:(BOOL)fp8;
- (BOOL)storeUnsentReports;
- (void)setRootViewController:(id)fp8;
- (id)rootViewController;
- (void)setRecipientEmail:(id)fp8;
- (id)recipientEmail;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (void)sendCrashes:(id)fp8;
- (void)handleCrashReportData:(id)fp8;
- (void)dealloc;
- (id)initWithRootViewController:(id)fp8 recipientEmail:(id)fp12;

@end

