/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GIPCache <NSObject>
- (unsigned int)count;
- (unsigned int)cacheSize;
- (id)allKeys;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)objectForKey:(id)fp8;
- (void)flush;
- (id)initWithCacheSize:(unsigned int)fp8;
@end

