/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSArray, NSString, NSURL;

@interface GIPClientOAuth : _AVAudioSessionCategoryPlayback
{
    NSString *clientId_;
    NSString *clientSecret_;
    id completion_;
    NSString *locale_;
    NSURL *redirectUrl_;
    NSArray *scopes_;
    int endpoint_;
}

- (void)setScopes:(id)fp8;
- (id)scopes;
- (void)setRedirectUrl:(id)fp8;
- (id)redirectUrl;
- (void)setLocale:(id)fp8;
- (id)locale;
- (void)setClientSecret:(id)fp8;
- (id)clientSecret;
- (void)setClientId:(id)fp8;
- (id)clientId;
- (void)completeWithAuthorizer:(id)fp8 error:(id)fp12 challenge:(id)fp16;
- (id)errorWithCode:(int)fp8 description:(id)fp12 fallback:(id)fp16;
- (void)sendRequest:(id)fp8;
- (id)endpoint;
- (void)fetcher:(id)fp8 didCompleteWithData:(id)fp12;
- (void)loginWithChallenge:(id)fp8 solution:(id)fp12 completion:(id)fp(null);
- (void)loginWithUsername:(id)fp8 password:(id)fp12 completion:(id)fp(null);
- (void)dealloc;
- (id)init;
- (id)initWithEndpoint:(int)fp8;

@end

