/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class GIPCrashReportData, NSDate, NSMutableArray, NSString, UIImage;

@interface GIPFeedbackCollectedData : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSDate *timestamp_;
    NSString *appName_;
    NSString *bundleVersion_;
    NSString *executableFileName_;
    NSString *bundleIdentifier_;
    NSString *osVersion_;
    NSString *logContents_;
    float batteryLevel_;
    int batteryState_;
    UIImage *screenshot_;
    NSString *userFeedback_;
    NSString *obfuscatedGaiaID_;
    NSString *categoryTag_;
    NSMutableArray *productSpecificData_;
    GIPCrashReportData *crashReport_;
    NSString *userEmail_;
}

+ (id)collectedDataWithCrashReport:(id)fp8;
+ (id)collectedData;
+ (id)batteryStateAsString:(int)fp8;
- (void)setUserEmail:(id)fp8;
- (id)userEmail;
- (void)setObfuscatedGaiaId:(id)fp8;
- (id)obfuscatedGaiaId;
- (id)crashReport;
- (void)setScreenshot:(id)fp8;
- (id)screenshot;
- (void)setUserFeedback:(id)fp8;
- (id)userFeedback;
- (void)setLogContents:(id)fp8;
- (id)logContents;
- (id)osVersion;
- (id)bundleIdentifier;
- (id)executableFileName;
- (void)setCategoryTag:(id)fp8;
- (id)categoryTag;
- (id)bundleVersion;
- (id)appName;
- (id)timestamp;
- (id)userFacingDescription;
- (id)exportAsProto;
- (int)protoBatteryState;
- (void)setSystemDataFromCurrentData;
- (void)setSystemDataFromCrashReport:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (int)reportType;
- (void)setCrashReport:(id)fp8;
- (void)addProductSpecificDataWithKey:(id)fp8 value:(id)fp12;
- (id)productSpecificData;
- (void)setProductSpecificData:(id)fp8;
- (void)dealloc;
- (id)initInternalWithCategoryTag:(id)fp8 crashReport:(id)fp12;
- (id)initWithCategoryTag:(id)fp8 crashReport:(id)fp12;
- (id)initWithCategoryTag:(id)fp8;

@end

