/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString, UITextView;

@interface GIPFeedbackLogViewerViewController : _AVAudioSessionCategoryPlayback
{
    UITextView *logText_;
    NSString *logContents_;
}

- (void)setLogContents:(id)fp8;
- (id)logContents;
- (void)setLogText:(id)fp8;
- (id)logText;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)dealloc;
- (void)viewDidLoad;

@end

