/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPFeedbackCollectedData, UILabel, UINavigationBar, UITextView, UIToolbar;

@interface GIPFeedbackCrashReportViewController : _AVAudioSessionCategoryPlayback
{
    GIPFeedbackCollectedData *feedbackData_;
    int titleBarStyle_;
    UINavigationBar *titlebar_;
    UILabel *systemDataLabel_;
    UITextView *systemDataView_;
    UILabel *feedbackLabel_;
    UITextView *feedbackView_;
    UILabel *legalLabel_;
    UIToolbar *toolbar_;
}

- (void)setTitleBarStyle:(int)fp8;
- (int)titleBarStyle;
- (void)presentInViewController:(id)fp8;
- (void)sendButtonAction;
- (void)closeButtonAction;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)loadView;
- (id)presentingViewController;
- (void)setCrashReport:(id)fp8;
- (id)crashReport;
- (void)setFeedbackData:(id)fp8;
- (id)feedbackData;
- (void)dealloc;
- (id)init;

@end

