/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPCrashReportHandlerProtocol-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class NSArray, NSString, UIViewController;

@interface GIPFeedbackCrashReportHandler : _AVAudioSessionCategoryPlayback <UIAlertViewDelegate, GIPCrashReportHandlerProtocol>
{
    NSString *categoryTag_;
    NSArray *crashReportDatas_;
    NSString *obfuscatedGaiaId_;
    UIViewController *viewController_;
}

- (void)setObfuscatedGaiaId:(id)fp8;
- (id)obfuscatedGaiaId;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)handleCrashReportData:(id)fp8;
- (void)dealloc;
- (id)initWithViewController:(id)fp8 categoryTag:(id)fp12;
- (id)init;

@end

