/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIAlertViewDelegate-Protocol.h"

@class GIPCrashReportData, GIPFeedbackCrashReportViewController, GIPFeedbackStyleSet, NSArray, NSBundle, NSString, UIAlertView, UIViewController;

@interface GIPFeedback : _AVAudioSessionCategoryPlayback <UIAlertViewDelegate>
{
    GIPFeedbackCrashReportViewController *crashViewController_;
    NSString *crashCategoryTag_;
    NSString *userInitiatedFeedbackCategoryTag_;
    NSBundle *resources_;
    NSString *stringTableName_;
    NSString *appDisplayName_;
    GIPFeedbackStyleSet *styleSet_;
    UIAlertView *sendCrashReportAlertView_;
    UIViewController *presentingViewController_;
    GIPCrashReportData *crashReport_;
    NSArray *crashReportsToSend_;
}

+ (void)sendCrashReports:(id)fp8;
+ (id)stringTableName;
+ (id)resources;
+ (BOOL)hasCrashReportToSend;
+ (id)createScreenshot:(id)fp8;
+ (void)sendAllCrashReports;
+ (void)submitFeedbackWithCollectedDataNoToast:(id)fp8;
+ (void)submitFeedbackWithCollectedData:(id)fp8;
+ (BOOL)hasInternetConnection;
+ (id)reportTypeAsString:(int)fp8;
+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)sharedInstance;
- (void)setStyleSet:(id)fp8;
- (id)styleSet;
- (void)setAppDisplayName:(id)fp8;
- (id)appDisplayName;
- (void)setUserInitiatedFeedbackCategoryTag:(id)fp8;
- (id)userInitiatedFeedbackCategoryTag;
- (void)setCrashCategoryTag:(id)fp8;
- (id)crashCategoryTag;
- (void)setCrashViewController:(id)fp8;
- (id)crashViewController;
- (id)sendCrashReportAlertView;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)handleLowMemoryWarning;
- (void)sendCrashReportsIfPermitted:(id)fp8;
- (void)sendCrashReportIfPermitted:(id)fp8;
- (void)sendCrashReportIfNecessary;
- (void)presentCrashReportInViewController:(id)fp8;
- (void)presentCrashReport:(id)fp8 inViewController:(id)fp12;
- (void)setShouldSendCrashReportsWasSet:(BOOL)fp8;
- (BOOL)shouldSendCrashReportsWasSet;
- (void)setShouldSendCrashReports:(BOOL)fp8;
- (BOOL)shouldSendCrashReports;
- (id)stringTableName;
- (void)setResources:(id)fp8;
- (id)resources;
- (void)dealloc;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

