/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView;

@interface GIPKeyboardToggler : _AVAudioSessionCategoryPlayback
{
    UIImageView *arrow_;
    UIImageView *backgroundView_;
    UIImageView *keyboard_;
}

- (void)flip:(BOOL)fp8;
- (void)setBackgroundHighlighted:(id)fp8;
- (void)setBackground:(id)fp8;
- (id)backgroundHighlighted;
- (id)background;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)createView;
- (void)setHighlighted:(BOOL)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)init;

@end

