/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface GIPNativeURL : _AVAudioSessionCategoryPlayback
{
    NSString *applicationName_;
    BOOL hasRegisteredHandler_;
}

+ (id)iTunesURL:(id)fp8;
+ (id)youTubeURL:(id)fp8;
+ (id)mapsURL:(id)fp8;
+ (id)nativeURL:(id)fp8 rewriteURLsForURLTypes:(unsigned int)fp12;
+ (id)nativeURL:(id)fp8 rewriteURLsForNativeApps:(BOOL)fp12;
+ (id)nativeURL:(id)fp8;
+ (BOOL)isMediaURL:(id)fp8;
- (BOOL)hasRegisteredHandler;
- (void)setApplicationName:(id)fp8;
- (id)applicationName;
- (void)dealloc;
- (id)initWithURL:(id)fp8;

@end

