/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface GIPPlaceholderTextView : _AVAudioSessionCategoryPlayback
{
    NSString *placeholder_;
    struct UIEdgeInsets placeholderInset_;
}

- (struct UIEdgeInsets)placeholderInset;
- (id)placeholder;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (void)textChanged:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setPlaceholderInset:(struct UIEdgeInsets)fp8;
- (void)setPlaceholder:(id)fp8;
- (void)setText:(id)fp8;

@end

