/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface GIPResourceLoader : _AVAudioSessionCategoryPlayback
{
    NSString *bundleName_;
    id <GIPCache> cache_;
}

+ (id)imageNamed:(id)fp8 inBundle:(id)fp12;
+ (id)imageNamed:(id)fp8 fromLoader:(id)fp12 shouldCache:(BOOL)fp16;
+ (id)imageNamed:(id)fp8 fromLoader:(id)fp12;
+ (id)sharedLoaderForBundleNamed:(id)fp8;
+ (void)setSharedLoader:(id)fp8 forBundleNamed:(id)fp12;
+ (void)initialize;
- (void)setBundleName:(id)fp8;
- (id)bundleName;
- (void)flush;
- (void)put:(id)fp8 forKey:(id)fp12;
- (id)contentsOfFileNamed:(id)fp8 ofType:(id)fp12 inDirectory:(id)fp16 fromBundle:(id)fp20;
- (id)imageNamed:(id)fp8 cache:(BOOL)fp12;
- (id)imageNamed:(id)fp8;
- (void)dealloc;
- (id)initWithCacheSize:(int)fp8 bundleName:(id)fp12;
- (id)initWithCacheSize:(int)fp8;
- (id)initWithBundleName:(id)fp8;
- (id)init;

@end

