/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GIPRectSplitter : _AVAudioSessionCategoryPlayback
{
    struct CGRect remainingRect_;
    int splitDirection_;
}

+ (struct CGRect)centeredRectForSize:(struct CGSize)fp8 inRect:(struct CGRect)fp16;
+ (id)splitterWithRect:(struct CGRect)fp8 splitDirection:(int)fp24;
- (id)splitByLength:(float)fp8 align:(CDAnonymousStruct3)fp12;
- (id)splitByLength:(float)fp8;
- (id)splitByPercent:(float)fp8;
- (id)toggleSplitDirection;
- (BOOL)isCenteredAlongSplitDirection:(CDAnonymousStruct3)fp8;
- (void)recalculateRemainingRect:(struct CGRect)fp8 align:(CDAnonymousStruct3)fp24 remainderAfterObject:(struct CGRect *)fp32;
- (struct CGRect)makeWithSize:(struct CGSize)fp8 padding:(CDAnonymousStruct7)fp16 align:(CDAnonymousStruct3)fp32 useRemainingSize:(BOOL)fp40 remainderAfterObject:(struct CGRect *)fp44;
- (void)removePaddingFromRemainder:(CDAnonymousStruct7)fp8;
- (struct CGRect)frameForSize:(struct CGSize)fp8 padding:(CDAnonymousStruct7)fp16 align:(CDAnonymousStruct3)fp32 remainderSplitter:(id *)fp40;
- (struct CGRect)frameForSize:(struct CGSize)fp8 padding:(CDAnonymousStruct7)fp16 align:(CDAnonymousStruct3)fp32;
- (struct CGRect)frameForPercent:(float)fp8;
- (struct CGRect)frameForLength:(float)fp8 padding:(CDAnonymousStruct7)fp12 align:(CDAnonymousStruct3)fp28;
- (struct CGRect)frameForRemainderWithPadding:(CDAnonymousStruct7)fp8;
- (struct CGRect)frameForRemainder;
- (struct CGSize)remainderLessPadding:(CDAnonymousStruct7)fp8;
- (struct CGSize)remainder;
- (id)initWithRect:(struct CGRect)fp8 splitDirection:(int)fp24;

@end

