/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GSKRecognitionConfig-Protocol.h"

@class NSString;

@interface GIPSpeechRecognitionRequest : _AVAudioSessionCategoryPlayback <GSKRecognitionConfig>
{
    unsigned long long captureStartTime_;
    BOOL isEmbeddedMic_;
    NSString *voiceSearchLanguage_;
}

+ (id)speechRecognitionRequest;
- (void)setVoiceSearchLanguage:(id)fp8;
- (void)setIsEmbeddedMic:(BOOL)fp8;
- (BOOL)isEmbeddedMic;
- (void)setCaptureStartTime:(unsigned long long)fp8;
- (BOOL)fetchSearchResults;
- (id)voiceSearchLanguage;
- (int)networkType;
- (BOOL)usingEmbeddedMic;
- (unsigned long long)captureStartTime;
- (id)applicationVersion;
- (void)dealloc;
- (id)init;

@end

