/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GIPWebViewController.h"

@class NSMutableDictionary, NSString, NSURL;

@interface GIPSuperWebViewController : GIPWebViewController
{
    NSURL *lastInjectedURL_;
    NSMutableDictionary *handlers_;
    NSString *initJs_;
    NSString *jsBundleName_;
    BOOL injectsJavascriptAfterLoad_;
    BOOL shouldForceInit_;
}

+ (id)parseKeyValuesFromString:(id)fp8;
+ (id)jsFromResource:(id)fp8 inBundle:(id)fp12;
- (void)setInjectsJavascriptAfterLoad:(BOOL)fp8;
- (BOOL)injectsJavascriptAfterLoad;
- (id)handlerForService:(id)fp8;
- (void)unregisterHandlerForService:(id)fp8;
- (void)registerHandler:(id)fp8 forService:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)resetInjectedJavascript:(id)fp8;
- (void)injectJavascript:(id)fp8;
- (id)initJs;
- (void)loadJavascriptFromResource:(id)fp8;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 jsBundleName:(id)fp12;

@end

