/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPMicrophoneVolumeView, GIPResourceLoader, GIPWaveformView;

@interface GIPSpeechFeedbackView : _AVAudioSessionCategoryPlayback
{
    GIPWaveformView *waveformView_;
    GIPMicrophoneVolumeView *microphoneView_;
    GIPResourceLoader *loader_;
    id <GIPSpeechWindowConfiguration> configuration_;
}

- (id)waveformView;
- (void)setWaveformLevel:(float)fp8;
- (void)setWaveformLevelsArray:(float *)fp8 ofSize:(int)fp12;
- (void)setWaveformMaxSamples:(unsigned int)fp8;
- (void)setWaveformScrolling:(BOOL)fp8;
- (void)setWaveformHidden:(BOOL)fp8;
- (void)setWaveformScaled:(BOOL)fp8;
- (void)setMicrophoneHidden:(BOOL)fp8;
- (id)microphoneView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 resourceLoader:(id)fp24 configuration:(id)fp28;
- (id)initWithFrame:(struct CGRect)fp8;

@end

