/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GIPSpeechErrorInterface : _AVAudioSessionCategoryPlayback
{
}

+ (id)messageForMissingMicrophone;
+ (BOOL)canTryAgainForError:(id)fp8;
+ (id)buttonForError:(id)fp8;
+ (id)messageForError:(id)fp8;

@end

