/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIPickerView, UIToolbar;

@interface GIPToolbarPickerView : _AVAudioSessionCategoryPlayback
{
    UIPickerView *pickerView_;
    UIToolbar *toolbar_;
    id <GIPToolbarPickerDelegate> pickerDelegate_;
}

- (id)pickerView;
- (void)select;
- (void)clear;
- (void)cancel;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithToolbarPickerDelegate:(id)fp8 useClearButton:(BOOL)fp12;

@end

