/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPWebViewDelegateInterceptor;

@interface GIPWebView : _AVAudioSessionCategoryPlayback
{
    GIPWebViewDelegateInterceptor *delegateInterceptor_;
}

- (void)dealloc;
- (void)cleanup;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)initWithFrame:(struct CGRect)fp8;

@end

