/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString, NSURL, NSURLRequest;

@interface GIPWebViewHistoryEntry : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSURLRequest *request_;
    NSURL *url_;
    NSString *html_;
}

+ (id)entryWithHTML:(id)fp8 baseURL:(id)fp12;
+ (id)entryWithRequest:(id)fp8;
- (void)setRequest:(id)fp8;
- (id)request;
- (void)setUrl:(id)fp8;
- (id)url;
- (void)setHtml:(id)fp8;
- (id)html;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithHTML:(id)fp8 baseURL:(id)fp12;
- (id)initWithRequest:(id)fp8;

@end

