/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GMURequestInterfaceHolder : _AVAudioSessionCategoryPlayback
{
    struct RequestInterface *requestInterface_;
}

- (void)setRequestInterface:(struct RequestInterface *)fp8;
- (struct RequestInterface *)requestInterface;

@end

