/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPSuperWebViewHandler-Protocol.h"
#import "GIPWebViewControllerDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class GIPSuperWebViewController, GTLPlusPerson, GTLServicePlus, GTMOAuth2Authentication, NSString;

@interface GooglePlus : _AVAudioSessionCategoryPlayback <GIPWebViewControllerDelegate, GIPSuperWebViewHandler, UIWebViewDelegate>
{
    id <GooglePlusDelegate> delegate_;
    GTMOAuth2Authentication *auth_;
    NSString *clientID_;
    NSString *clientSecret_;
    NSString *keychainItemName_;
    GTLServicePlus *plusService_;
    GIPSuperWebViewController *oobViewController_;
    GTLPlusPerson *userInfo_;
    NSString *javascript_;
    BOOL canceledOOB_;
    BOOL finishedOOB_;
    NSString *extraAuthorizationScopes_;
}

+ (id)plusOneOAuth2Scopes;
+ (id)shareboxOAuth2Scopes;
+ (id)allOAuth2Scopes;
+ (id)sharedInstance;
- (id)oobViewController;
- (void)setExtraAuthorizationScopes:(id)fp8;
- (id)extraAuthorizationScopes;
- (void)setFinishedOOB:(BOOL)fp8;
- (BOOL)finishedOOB;
- (BOOL)cancelledOOB;
- (id)userInfo;
- (void)setKeychainItemName:(id)fp8;
- (id)keychainItemName;
- (void)setClientSecret:(id)fp8;
- (id)clientSecret;
- (void)setClientID:(id)fp8;
- (id)clientID;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)removeLoginTokenCookies;
- (void)logOut;
- (id)javascript;
- (void)handleMethod:(id)fp8 withArgs:(id)fp12 fromSource:(id)fp16;
- (void)webViewController:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewControllerDidFinishLoad:(id)fp8;
- (BOOL)webViewController:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (BOOL)isWhitelistedURL:(id)fp8;
- (void)viewControllerWasClosed:(id)fp8;
- (void)spawnOOBFlowIfNeeded;
- (void)gotoOOBWithURL:(id)fp8;
- (id)oobURLWithContinue:(id)fp8;
- (void)setCancelledOOB:(BOOL)fp8;
- (void)retrieveUserInfo;
- (void)getAllCircles:(id)fp(null);
- (void)insertActivity:(id)fp8 jpegData:(id)fp12 preview:(BOOL)fp16 progress:(id)fp(null) finished:(void)fp20;
- (void)insertActivity:(id)fp8 jpegData:(id)fp12 progress:(id)fp(null) finished:(void)fp16;
- (void)previewInsertWithActivity:(id)fp8 finished:(id)fp(null);
- (void)setUpAuthWithCompletionHandler:(id)fp(null);
- (BOOL)tryToGetAuthFromKeychain;
- (void)setAuth:(id)fp8;
- (id)auth;
- (BOOL)canAuthorize;
- (void)setAuthorizers;
- (void)setSdkHeaders;
- (void)dealloc;
- (id)initWithClientID:(id)fp8 clientSecret:(id)fp12 keychainItemName:(id)fp16;
- (id)initWithClientID:(id)fp8 clientSecret:(id)fp12;
- (id)init;

@end

