/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GSKProtoClientParameters;

@interface GSKProtoClientExperimentConfig : _AVAudioSessionCategoryPlayback
{
    GSKProtoClientParameters *clientParameters_;
}

- (void)setClientParameters:(id)fp8;
- (id)clientParameters;
- (void)dealloc;

@end

