/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol GSKSpeechRecognizerDelegate
- (void)recognitionDidFail:(id)fp8 withError:(id)fp12;
- (void)recognitionTimedOutOrFailed:(id)fp8 withError:(id)fp12 afterInterval:(double)fp16;
- (void)recognitionDidComplete:(id)fp8;
- (void)recognitionProgressDidUpdate:(id)fp8;
- (void)recognitionWasCanceled:(id)fp8;
- (void)captureDidFinish:(id)fp8;
- (void)captureDidStart:(id)fp8;
@end

