/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol GSKSpeechRecognizerListenerDelegate
- (void)recognitionDidFailWithError:(id)fp8;
- (void)recognitionInProgress:(id)fp8;
- (void)recognitionDidComplete:(id)fp8 withHttpHeaders:(id)fp12;
- (void)captureDidStop;
- (void)captureDidStart;
@end

