/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GSKSpeechRecognizerListenerDelegate-Protocol.h"

@class NSArray, NSDate, NSString;

@interface GSKSpeechRecognizerClient : _AVAudioSessionCategoryPlayback <GSKSpeechRecognizerListenerDelegate>
{
    id <GSKSpeechRecognizerDelegate> delegate_;
    int state_;
    NSArray *results_;
    NSString *endpointMethod_;
    NSDate *inProgressResultsReceivedDate_;
    double timeoutInProgressBetweenCutoff_;
    struct SpeechRecognizerClient *recognizer_;
    struct SpeechRecognizerListener *listener_;
}

- (void)setListener:(struct SpeechRecognizerListener *)fp8;
- (struct SpeechRecognizerListener *)listener;
- (void)setRecognizer:(struct SpeechRecognizerClient *)fp8;
- (struct SpeechRecognizerClient *)recognizer;
- (void)setResults:(id)fp8;
- (id)results;
- (void)setEndpointMethod:(id)fp8;
- (id)endpointMethod;
- (id)clientExperimentConfig;
- (id)audioEncodingDescription;
- (id)currentUtteranceId;
- (void)resume:(BOOL)fp8;
- (void)suspend;
- (float)audioInputLevel;
- (BOOL)isRecognizing;
- (BOOL)isCapturing;
- (BOOL)isIdle;
- (BOOL)isSuspended;
- (void)recognitionDidFailWithError:(id)fp8;
- (void)recognitionInProgress:(id)fp8;
- (void)recognitionDidComplete:(id)fp8 withHttpHeaders:(id)fp12;
- (void)recognitionTimedOutOrFailedAfterInProgressWithError:(id)fp8;
- (void)captureDidStop;
- (void)captureDidStart;
- (id)recognitionResults;
- (void)cancelRecognition;
- (void)stopRecognitionWithButtonPress:(BOOL)fp8;
- (void)recognizeWithConfig:(id)fp8 delegate:(id)fp12;
- (struct basic_string<char, std::char_traits<char>, std::allocator<char>>)makeApplicationData:(id)fp8 searchRequestHeaders:(id)fp12;
- (void)addRequestAttributeWithName:(id)fp8 value:(id)fp12 toProto:(struct GoogleSearchRequestProto *)fp16;
- (struct basic_string<char, std::char_traits<char>, std::allocator<char>>)makeGrammar:(int)fp8 maxNBest:(int)fp12;
- (void)dealloc;
- (void)closeRecognizer;
- (void)initializeRecognizerWithConfig:(id)fp8;
- (void)resetSessionWithConfig:(id)fp8;
- (id)initWithSessionConfig:(id)fp8;

@end

