/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface GSKVoiceSearchResult : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *recognitionResult_;
    double confidence_;
    NSString *webResultHTML_;
    NSString *webResultURL_;
}

- (void)setWebResultURL:(id)fp8;
- (id)webResultURL;
- (void)setWebResultHTML:(id)fp8;
- (id)webResultHTML;
- (void)setConfidence:(double)fp8;
- (double)confidence;
- (void)setRecognitionResult:(id)fp8;
- (id)recognitionResult;
- (id)description;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithRecognitionResult:(id)fp8 confidence:(double)fp12;
- (id)initWithRecognitionResult:(id)fp8;
- (id)initWithRecognitionResult:(id)fp8 webResultURL:(id)fp12;
- (id)initWithRecognitionResult:(id)fp8 webResultHTML:(id)fp12;

@end

