/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTLObject.h"

#import "GTLBatchItemCreationProtocol-Protocol.h"

@class NSMutableDictionary;

@interface GTLBatchResult : GTLObject <GTLBatchItemCreationProtocol>
{
    NSMutableDictionary *successes_;
    NSMutableDictionary *failures_;
}

- (void)setFailures:(id)fp8;
- (id)failures;
- (void)setSuccesses:(id)fp8;
- (id)successes;
- (void)createItemsWithClassMap:(id)fp8;
- (id)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

