/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTLObject.h"

#import "GTLCollectionProtocol-Protocol.h"
#import "NSFastEnumeration-Protocol.h"

@interface GTLCollectionObject : GTLObject <GTLCollectionProtocol, NSFastEnumeration>
{
}

- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct6 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (id)objectAtIndexedSubscript:(int)fp8;
- (id)itemAtIndex:(unsigned int)fp8;

@end

