/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GTLQueryProtocol-Protocol.h"
#import "GTLRuntimeCommon-Protocol.h"

@class GTLObject, GTLUploadParameters, NSDictionary, NSMutableDictionary, NSString;

@interface GTLQuery : _AVAudioSessionCategoryPlayback <GTLRuntimeCommon, GTLQueryProtocol>
{
    NSString *methodName_;
    NSMutableDictionary *json_;
    GTLObject *bodyObject_;
    NSMutableDictionary *childCache_;
    NSString *requestID_;
    GTLUploadParameters *uploadParameters_;
    NSDictionary *urlQueryParameters_;
    NSDictionary *additionalHTTPHeaders_;
    Class expectedObjectClass_;
    BOOL skipAuthorization_;
    id completionBlock_;
}

+ (BOOL)resolveInstanceMethod:(SEL)fp8;
+ (Class)ancestorClass;
+ (id)arrayPropertyToClassMapForClass:(Class)fp8;
+ (id)propertyToJSONKeyMapForClass:(Class)fp8;
+ (void)initialize;
+ (id)arrayPropertyToClassMap;
+ (id)parameterNameMap;
+ (id)nextRequestID;
+ (id)queryWithMethodName:(id)fp8;
- (void)setCompletionBlock:(id)fp(null);
- (id)completionBlock;
- (void)setShouldSkipAuthorization:(BOOL)fp8;
- (BOOL)shouldSkipAuthorization;
- (void)setExpectedObjectClass:(Class)fp8;
- (Class)expectedObjectClass;
- (void)setAdditionalHTTPHeaders:(id)fp8;
- (id)additionalHTTPHeaders;
- (void)setUrlQueryParameters:(id)fp8;
- (id)urlQueryParameters;
- (void)setUploadParameters:(id)fp8;
- (id)uploadParameters;
- (void)setRequestID:(id)fp8;
- (id)requestID;
- (void)setBodyObject:(id)fp8;
- (id)bodyObject;
- (void)setJSON:(id)fp8;
- (id)JSON;
- (id)methodName;
- (id)surrogates;
- (id)cacheChildForKey:(id)fp8;
- (void)setCacheChild:(id)fp8 forKey:(id)fp12;
- (id)JSONValueForKey:(id)fp8;
- (void)setJSONValue:(id)fp8 forKey:(id)fp12;
- (void)executionDidStop;
- (BOOL)isBatchQuery;
- (void)setCustomParameter:(id)fp8 forKey:(id)fp12;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithMethodName:(id)fp8;

@end

