/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@protocol GTLQueryProtocol <NSObject, NSCopying>
- (id)uploadParameters;
- (id)additionalHTTPHeaders;
- (void)executionDidStop;
- (BOOL)shouldSkipAuthorization;
- (BOOL)isBatchQuery;
@end

