/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GTLRuntimeCommon <NSObject>
+ (Class)ancestorClass;
+ (id)arrayPropertyToClassMapForClass:(Class)fp8;
+ (id)propertyToJSONKeyMapForClass:(Class)fp8;
- (id)surrogates;
- (id)cacheChildForKey:(id)fp8;
- (void)setCacheChild:(id)fp8 forKey:(id)fp12;
- (id)JSONValueForKey:(id)fp8;
- (void)setJSONValue:(id)fp8 forKey:(id)fp12;
@end

