/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GTMHTTPFetcherService, NSDictionary, NSMutableDictionary, NSOperationQueue, NSString, NSURL;

@interface GTLService : _AVAudioSessionCategoryPlayback
{
    NSOperationQueue *parseQueue_;
    NSString *userAgent_;
    GTMHTTPFetcherService *fetcherService_;
    NSString *userAgentAddition_;
    NSMutableDictionary *serviceProperties_;
    NSDictionary *surrogates_;
    SEL uploadProgressSelector_;
    id retryBlock_;
    id uploadProgressBlock_;
    unsigned int uploadChunkSize_;
    BOOL isRetryEnabled_;
    SEL retrySelector_;
    double maxRetryInterval_;
    BOOL shouldFetchNextPages_;
    NSString *apiKey_;
    BOOL isRESTDataWrapperRequired_;
    NSString *apiVersion_;
    NSURL *rpcURL_;
    NSURL *rpcUploadURL_;
    NSDictionary *urlQueryParameters_;
    NSDictionary *additionalHTTPHeaders_;
}

+ (unsigned int)defaultServiceUploadChunkSize;
+ (void)invokeCallback:(SEL)fp8 target:(id)fp12 ticket:(id)fp16 object:(id)fp20 error:(id)fp24;
+ (Class)ticketClass;
- (void)setUploadProgressBlock:(id)fp(null);
- (id)uploadProgressBlock;
- (void)setRetryBlock:(id)fp(null);
- (id)retryBlock;
- (void)setRpcUploadURL:(id)fp8;
- (id)rpcUploadURL;
- (void)setRpcURL:(id)fp8;
- (id)rpcURL;
- (void)setApiVersion:(id)fp8;
- (id)apiVersion;
- (void)setAdditionalHTTPHeaders:(id)fp8;
- (id)additionalHTTPHeaders;
- (void)setUrlQueryParameters:(id)fp8;
- (id)urlQueryParameters;
- (void)setIsRESTDataWrapperRequired:(BOOL)fp8;
- (BOOL)isRESTDataWrapperRequired;
- (void)setAPIKey:(id)fp8;
- (id)APIKey;
- (void)setMaxRetryInterval:(double)fp8;
- (double)maxRetryInterval;
- (void)setRetrySelector:(SEL)fp8;
- (SEL)retrySelector;
- (void)setRetryEnabled:(BOOL)fp8;
- (BOOL)isRetryEnabled;
- (void)setUploadProgressSelector:(SEL)fp8;
- (SEL)uploadProgressSelector;
- (void)setSurrogates:(id)fp8;
- (id)surrogates;
- (void)setShouldFetchNextPages:(BOOL)fp8;
- (BOOL)shouldFetchNextPages;
- (void)setParseQueue:(id)fp8;
- (id)parseQueue;
- (void)setFetcherService:(id)fp8;
- (id)fetcherService;
- (void)setUserAgentAddition:(id)fp8;
- (id)userAgentAddition;
- (void)setServiceUploadChunkSize:(unsigned int)fp8;
- (unsigned int)serviceUploadChunkSize;
- (id)authorizer;
- (void)setAuthorizer:(id)fp8;
- (id)serviceUserData;
- (void)setServiceUserData:(id)fp8;
- (id)servicePropertyForKey:(id)fp8;
- (void)setServiceProperty:(id)fp8 forKey:(id)fp12;
- (id)serviceProperties;
- (void)setServiceProperties:(id)fp8;
- (id)runLoopModes;
- (void)setRunLoopModes:(id)fp8;
- (BOOL)shouldFetchInBackground;
- (void)setShouldFetchInBackground:(BOOL)fp8;
- (int)cookieStorageMethod;
- (void)setCookieStorageMethod:(int)fp8;
- (void)setUserAgent:(id)fp8;
- (void)setExactUserAgent:(id)fp8;
- (id)userAgent;
- (id)deleteResourceURL:(id)fp8 ETag:(id)fp12 completionHandler:(id)fp(null);
- (id)fetchObjectByUpdatingObject:(id)fp8 forURL:(id)fp12 completionHandler:(id)fp(null);
- (id)fetchObjectByInsertingObject:(id)fp8 forURL:(id)fp12 completionHandler:(id)fp(null);
- (id)fetchObjectWithURL:(id)fp8 completionHandler:(id)fp(null);
- (id)deleteResourceURL:(id)fp8 ETag:(id)fp12 delegate:(id)fp16 didFinishSelector:(SEL)fp20;
- (id)fetchObjectByUpdatingObject:(id)fp8 forURL:(id)fp12 delegate:(id)fp16 didFinishSelector:(SEL)fp20;
- (id)fetchObjectByInsertingObject:(id)fp8 forURL:(id)fp12 delegate:(id)fp16 didFinishSelector:(SEL)fp20;
- (id)fetchObjectWithURL:(id)fp8 objectClass:(Class)fp12 delegate:(id)fp16 didFinishSelector:(SEL)fp20;
- (id)fetchPublicObjectWithURL:(id)fp8 objectClass:(Class)fp12 delegate:(id)fp16 didFinishSelector:(SEL)fp20;
- (id)fetchObjectWithURL:(id)fp8 delegate:(id)fp12 didFinishSelector:(SEL)fp16;
- (id)fetchObjectWithMethodNamed:(id)fp8 parameters:(id)fp12 insertingObject:(id)fp16 objectClass:(Class)fp20 completionHandler:(id)fp(null);
- (id)fetchObjectWithMethodNamed:(id)fp8 insertingObject:(id)fp12 objectClass:(Class)fp16 completionHandler:(id)fp(null);
- (id)fetchObjectWithMethodNamed:(id)fp8 parameters:(id)fp12 objectClass:(Class)fp16 completionHandler:(id)fp(null);
- (id)fetchObjectWithMethodNamed:(id)fp8 parameters:(id)fp12 insertingObject:(id)fp16 objectClass:(Class)fp20 delegate:(id)fp24 didFinishSelector:(SEL)fp28;
- (id)fetchObjectWithMethodNamed:(id)fp8 insertingObject:(id)fp12 objectClass:(Class)fp16 delegate:(id)fp20 didFinishSelector:(SEL)fp24;
- (id)fetchObjectWithMethodNamed:(id)fp8 parameters:(id)fp12 objectClass:(Class)fp16 delegate:(id)fp20 didFinishSelector:(SEL)fp24;
- (id)executeQuery:(id)fp8 completionHandler:(id)fp(null);
- (id)executeQuery:(id)fp8 delegate:(id)fp12 didFinishSelector:(SEL)fp16;
- (id)mergedNewResultObject:(id)fp8 oldResultObject:(id)fp12 forQuery:(id)fp16;
- (BOOL)fetchNextPageWithQuery:(id)fp8 delegate:(id)fp12 didFinishedSelector:(SEL)fp16 completionHandler:(id)fp(null) ticket:(void)fp20;
- (id)nextPageQueryForQuery:(id)fp8 result:(id)fp12 ticket:(id)fp16;
- (BOOL)waitForTicket:(id)fp8 timeout:(double)fp12 fetchedObject:(id *)fp20 error:(id *)fp24;
- (BOOL)invokeRetrySelector:(SEL)fp8 delegate:(id)fp12 ticket:(id)fp16 willRetry:(BOOL)fp20 error:(id)fp24;
- (BOOL)objectFetcher:(id)fp8 willRetry:(BOOL)fp12 forError:(id)fp16;
- (void)handleParsedObjectForFetcher:(id)fp8;
- (void)parseObjectFromDataOfFetcher:(id)fp8;
- (void)prepareToParseObjectForFetcher:(id)fp8;
- (void)objectFetcher:(id)fp8 finishedWithData:(id)fp12 error:(id)fp16;
- (void)objectFetcher:(id)fp8 didSendBytes:(int)fp12 totalBytesSent:(int)fp16 totalBytesExpectedToSend:(int)fp20;
- (void)invokeProgressCallbackForTicket:(id)fp8 deliveredBytes:(unsigned long long)fp12 totalBytes:(unsigned long long)fp20;
- (id)fetchObjectWithURL:(id)fp8 objectClass:(Class)fp12 bodyObject:(id)fp16 ETag:(id)fp20 httpMethod:(id)fp24 mayAuthorize:(BOOL)fp28 delegate:(id)fp32 didFinishSelector:(SEL)fp36 completionHandler:(id)fp40 ticket:(id)fp44;
- (id)executeBatchQuery:(id)fp8 delegate:(id)fp12 didFinishSelector:(SEL)fp16 completionHandler:(id)fp20 ticket:(id)fp24;
- (id)fetchObjectWithMethodNamed:(id)fp8 objectClass:(Class)fp12 parameters:(id)fp16 bodyObject:(id)fp20 requestID:(id)fp24 urlQueryParameters:(id)fp28 delegate:(id)fp32 didFinishSelector:(SEL)fp36 completionHandler:(id)fp40 executingQuery:(id)fp44 ticket:(id)fp48;
- (id)rpcPayloadForMethodNamed:(id)fp8 parameters:(id)fp12 bodyObject:(id)fp16 requestID:(id)fp20;
- (id)uploadFetcherWithRequest:(id)fp8 fetcherService:(id)fp12 params:(id)fp16;
- (id)fetchObjectWithURL:(id)fp8 objectClass:(Class)fp12 bodyObject:(id)fp16 dataToPost:(id)fp20 ETag:(id)fp24 httpMethod:(id)fp28 mayAuthorize:(BOOL)fp32 isREST:(BOOL)fp36 delegate:(id)fp40 didFinishSelector:(SEL)fp44 completionHandler:(id)fp48 executingQuery:(id)fp52 ticket:(id)fp56;
- (id)objectRequestForURL:(id)fp8 object:(id)fp12 ETag:(id)fp16 httpMethod:(id)fp20 isREST:(BOOL)fp24 additionalHeaders:(id)fp28 ticket:(id)fp32;
- (id)requestForURL:(id)fp8 ETag:(id)fp12 httpMethod:(id)fp16;
- (id)requestForURL:(id)fp8 ETag:(id)fp12 httpMethod:(id)fp16 ticket:(id)fp20;
- (id)requestUserAgent;
- (void)dealloc;
- (id)init;

@end

