/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GTLObject, GTLService, GTMHTTPFetcher, NSDictionary, NSError, NSMutableDictionary, NSOperation, NSString;

@interface GTLServiceTicket : _AVAudioSessionCategoryPlayback
{
    GTLService *service_;
    NSMutableDictionary *ticketProperties_;
    NSDictionary *surrogates_;
    GTMHTTPFetcher *objectFetcher_;
    SEL uploadProgressSelector_;
    BOOL shouldFetchNextPages_;
    BOOL isRetryEnabled_;
    SEL retrySelector_;
    double maxRetryInterval_;
    id retryBlock_;
    id uploadProgressBlock_;
    GTLObject *postedObject_;
    GTLObject *fetchedObject_;
    id <GTLQueryProtocol> executingQuery_;
    id <GTLQueryProtocol> originalQuery_;
    NSError *fetchError_;
    BOOL hasCalledCallback_;
    unsigned int pagesFetchedCounter_;
    NSString *apiKey_;
    BOOL isREST_;
    NSOperation *parseOperation_;
}

+ (id)ticketForService:(id)fp8;
- (void)setRetryBlock:(id)fp(null);
- (id)retryBlock;
- (void)setIsREST:(BOOL)fp8;
- (BOOL)isREST;
- (void)setParseOperation:(id)fp8;
- (id)parseOperation;
- (void)setAPIKey:(id)fp8;
- (id)APIKey;
- (void)setPagesFetchedCounter:(unsigned int)fp8;
- (unsigned int)pagesFetchedCounter;
- (void)setFetchError:(id)fp8;
- (id)fetchError;
- (void)setOriginalQuery:(id)fp8;
- (id)originalQuery;
- (void)setExecutingQuery:(id)fp8;
- (id)executingQuery;
- (void)setFetchedObject:(id)fp8;
- (id)fetchedObject;
- (void)setPostedObject:(id)fp8;
- (id)postedObject;
- (void)setObjectFetcher:(id)fp8;
- (id)objectFetcher;
- (void)setMaxRetryInterval:(double)fp8;
- (double)maxRetryInterval;
- (void)setRetrySelector:(SEL)fp8;
- (SEL)retrySelector;
- (void)setHasCalledCallback:(BOOL)fp8;
- (BOOL)hasCalledCallback;
- (void)setRetryEnabled:(BOOL)fp8;
- (BOOL)isRetryEnabled;
- (void)setShouldFetchNextPages:(BOOL)fp8;
- (BOOL)shouldFetchNextPages;
- (id)queryForRequestID:(id)fp8;
- (int)statusCode;
- (id)uploadProgressBlock;
- (void)setUploadProgressBlock:(id)fp(null);
- (void)setUploadProgressSelector:(SEL)fp8;
- (SEL)uploadProgressSelector;
- (void)setSurrogates:(id)fp8;
- (id)surrogates;
- (id)propertyForKey:(id)fp8;
- (void)setProperty:(id)fp8 forKey:(id)fp12;
- (id)properties;
- (void)setProperties:(id)fp8;
- (id)userData;
- (void)setUserData:(id)fp8;
- (id)service;
- (void)cancelTicket;
- (BOOL)isUploadPaused;
- (void)resumeUpload;
- (void)pauseUpload;
- (id)description;
- (void)dealloc;
- (id)initWithService:(id)fp8;

@end

