/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GTLUtilities : _AVAudioSessionCategoryPlayback
{
}

+ (id)mergedClassDictionaryForSelector:(SEL)fp8 startClass:(Class)fp12 ancestorClass:(Class)fp16 cache:(id)fp20;
+ (id)newStaticDictionary;
+ (id)URLWithString:(id)fp8 queryParameters:(id)fp12;
+ (int)compareVersion:(id)fp8 toVersion:(id)fp12;
+ (id)firstObjectFromArray:(id)fp8 withValue:(id)fp12 forKeyPath:(id)fp16;
+ (id)objectsFromArray:(id)fp8 withValue:(id)fp12 forKeyPath:(id)fp16;
+ (id)stringByPercentEncodingUTF8ForString:(id)fp8;
+ (id)stringByURLEncodingStringParameter:(id)fp8;
+ (id)stringByURLEncodingForURI:(id)fp8;
+ (id)stringByURLEncodingString:(id)fp8;

@end

