/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSData, NSFileHandle, NSString, NSURL;

@interface GTLUploadParameters : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *MIMEType_;
    NSData *data_;
    NSFileHandle *fileHandle_;
    NSURL *uploadLocationURL_;
    NSString *slug_;
    BOOL shouldSendUploadOnly_;
}

+ (id)uploadParametersWithFileHandle:(id)fp8 MIMEType:(id)fp12;
+ (id)uploadParametersWithData:(id)fp8 MIMEType:(id)fp12;
- (void)setShouldSendUploadOnly:(BOOL)fp8;
- (BOOL)shouldSendUploadOnly;
- (void)setSlug:(id)fp8;
- (id)slug;
- (void)setUploadLocationURL:(id)fp8;
- (id)uploadLocationURL;
- (void)setFileHandle:(id)fp8;
- (id)fileHandle;
- (void)setData:(id)fp8;
- (id)data;
- (void)setMIMEType:(id)fp8;
- (id)MIMEType;
- (id)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

