/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GTMCookieStorageProtocol-Protocol.h"

@class NSMutableArray;

@interface GTMCookieStorage : _AVAudioSessionCategoryPlayback <GTMCookieStorageProtocol>
{
    NSMutableArray *cookies_;
}

- (void)removeAllCookies;
- (void)removeExpiredCookies;
- (id)cookieMatchingCookie:(id)fp8;
- (id)cookiesForURL:(id)fp8;
- (void)deleteCookie:(id)fp8;
- (void)setCookies:(id)fp8;
- (void)dealloc;
- (id)init;

@end

