/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSData, NSDate, NSURLResponse;

@interface GTMCachedURLResponse : _AVAudioSessionCategoryPlayback
{
    NSURLResponse *response_;
    NSData *data_;
    NSDate *useDate_;
    NSDate *reservationDate_;
}

- (void)setUseDate:(id)fp8;
- (id)useDate;
- (void)setReservationDate:(id)fp8;
- (id)reservationDate;
- (id)data;
- (id)response;
- (int)compareUseDate:(id)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithResponse:(id)fp8 data:(id)fp12;

@end

