/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GTMFetcherCallbacks : _AVAudioSessionCategoryPlayback
{
    struct GTMHTTPCppCallback *cb_;
}

- (void)fetcher:(id)fp8 finishedWithData:(id)fp12 error:(id)fp16;
- (id)initWithCallback:(struct GTMHTTPCppCallback *)fp8;

@end

