/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GTMHTTPFetchHistoryProtocol-Protocol.h"

@class GTMCookieStorage, GTMURLCache;

@interface GTMHTTPFetchHistory : _AVAudioSessionCategoryPlayback <GTMHTTPFetchHistoryProtocol>
{
    GTMURLCache *etaggedDataCache_;
    BOOL shouldRememberETags_;
    BOOL shouldCacheETaggedData_;
    GTMCookieStorage *cookieStorage_;
}

- (void)setCookieStorage:(id)fp8;
- (id)cookieStorage;
- (void)setMemoryCapacity:(unsigned int)fp8;
- (unsigned int)memoryCapacity;
- (void)setShouldCacheETaggedData:(BOOL)fp8;
- (BOOL)shouldCacheETaggedData;
- (void)setShouldRememberETags:(BOOL)fp8;
- (BOOL)shouldRememberETags;
- (void)removeAllCookies;
- (void)clearHistory;
- (void)clearETaggedDataCache;
- (void)removeCachedDataForRequest:(id)fp8;
- (id)cachedDataForRequest:(id)fp8;
- (id)cachedETagForRequest:(id)fp8;
- (void)updateFetchHistoryWithRequest:(id)fp8 response:(id)fp12 downloadedData:(id)fp16;
- (void)updateRequest:(id)fp8 isHTTPGet:(BOOL)fp12;
- (void)dealloc;
- (id)initWithMemoryCapacity:(unsigned int)fp8 shouldCacheETaggedData:(BOOL)fp12;
- (id)init;

@end

