/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GTMHTTPFetchHistoryProtocol <NSObject>
- (void)removeCachedDataForRequest:(id)fp8;
- (void)updateFetchHistoryWithRequest:(id)fp8 response:(id)fp12 downloadedData:(id)fp16;
- (id)cookieStorage;
- (id)cachedDataForRequest:(id)fp8;
- (BOOL)shouldCacheETaggedData;
- (void)updateRequest:(id)fp8 isHTTPGet:(BOOL)fp12;
@end

