/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GTMLightweightProxy : _AVAudioSessionCategoryPlayback
{
    id representedObject_;
}

- (BOOL)respondsToSelector:(SEL)fp8;
- (void)doesNotRecognizeSelector:(SEL)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (void)forwardInvocation:(id)fp8;
- (void)setRepresentedObject:(id)fp8;
- (id)representedObject;
- (void)dealloc;
- (id)init;
- (id)initWithRepresentedObject:(id)fp8;

@end

