/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray;

@interface GTMMIMEDocument : _AVAudioSessionCategoryPlayback
{
    NSMutableArray *parts_;
    unsigned long long length_;
    unsigned int randomSeed_;
}

+ (id)MIMEDocument;
- (void)generateInputStream:(id *)fp8 length:(unsigned long long *)fp12 boundary:(id *)fp16;
- (id)uniqueBoundary;
- (unsigned int)random;
- (void)seedRandomWith:(unsigned int)fp8;
- (void)addPartWithHeaders:(id)fp8 body:(id)fp12;
- (void)dealloc;
- (id)init;

@end

