/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSData;

@interface GTMMIMEPart : _AVAudioSessionCategoryPlayback
{
    NSData *headerData_;
    NSData *bodyData_;
}

+ (id)partWithHeaders:(id)fp8 body:(id)fp12;
- (unsigned int)length;
- (id)body;
- (id)header;
- (BOOL)containsBytes:(const char *)fp8 length:(unsigned int)fp12;
- (void)dealloc;
- (id)initWithHeaders:(id)fp8 body:(id)fp12;

@end

