/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UINavigationControllerDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class GTMOAuth2SignIn, NSMutableDictionary, NSString, NSURL, NSURLRequest, UIBarButtonItem, UIButton, UIView, UIWebView;

@interface GTMOAuth2ViewControllerTouch : _AVAudioSessionCategoryPlayback <UINavigationControllerDelegate, UIWebViewDelegate>
{
    UIButton *backButton_;
    UIButton *forwardButton_;
    UIView *navButtonsView_;
    UIBarButtonItem *rightBarButtonItem_;
    UIWebView *webView_;
    GTMOAuth2SignIn *signIn_;
    NSURLRequest *request_;
    id delegate_;
    SEL finishedSelector_;
    id completionBlock_;
    id popViewBlock_;
    NSString *keychainItemName_;
    void *keychainItemAccessibility_;
    NSString *initialHTMLString_;
    NSURL *browserCookiesURL_;
    id userData_;
    NSMutableDictionary *properties_;
    BOOL isInsideShouldAutorotateToInterfaceOrientation_;
    BOOL isViewShown_;
    BOOL didViewAppear_;
    BOOL hasNotifiedWebViewStartedLoading_;
    BOOL hasCalledFinished_;
    BOOL hasDoneFinalRedirect_;
    BOOL didDismissSelf_;
}

+ (void)revokeTokenForGoogleAuthentication:(id)fp8;
+ (void)setSignInClass:(Class)fp8;
+ (Class)signInClass;
+ (BOOL)saveParamsToKeychainForName:(id)fp8 accessibility:(void *)fp12 authentication:(id)fp16;
+ (BOOL)saveParamsToKeychainForName:(id)fp8 authentication:(id)fp12;
+ (BOOL)removeAuthFromKeychainForName:(id)fp8;
+ (BOOL)authorizeFromKeychainForName:(id)fp8 authentication:(id)fp12;
+ (id)authForGoogleFromKeychainForName:(id)fp8 clientID:(id)fp12 clientSecret:(id)fp16;
+ (id)authNibBundle;
+ (id)authNibName;
+ (id)controllerWithAuthentication:(id)fp8 authorizationURL:(id)fp12 keychainItemName:(id)fp16 completionHandler:(id)fp(null);
+ (id)controllerWithAuthentication:(id)fp8 authorizationURL:(id)fp12 keychainItemName:(id)fp16 delegate:(id)fp20 finishedSelector:(SEL)fp24;
+ (id)controllerWithScope:(id)fp8 clientID:(id)fp12 clientSecret:(id)fp16 keychainItemName:(id)fp20 completionHandler:(id)fp(null);
+ (id)controllerWithScope:(id)fp8 clientID:(id)fp12 clientSecret:(id)fp16 keychainItemName:(id)fp20 delegate:(id)fp24 finishedSelector:(SEL)fp28;
- (void)setPopViewBlock:(id)fp(null);
- (id)popViewBlock;
- (void)setProperties:(id)fp8;
- (id)properties;
- (void)setUserData:(id)fp8;
- (id)userData;
- (id)signIn;
- (void)setBrowserCookiesURL:(id)fp8;
- (id)browserCookiesURL;
- (void)setInitialHTMLString:(id)fp8;
- (id)initialHTMLString;
- (void)setKeychainItemAccessibility:(void *)fp8;
- (void *)keychainItemAccessibility;
- (void)setKeychainItemName:(id)fp8;
- (id)keychainItemName;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setRightBarButtonItem:(id)fp8;
- (id)rightBarButtonItem;
- (void)setNavButtonsView:(id)fp8;
- (id)navButtonsView;
- (void)setForwardButton:(id)fp8;
- (id)forwardButton;
- (void)setBackButton:(id)fp8;
- (id)backButton;
- (void)setRequest:(id)fp8;
- (id)request;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (void)updateUI;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)isNavigationBarTranslucent;
- (void)moveWebViewFromUnderNavigationBar;
- (void)signIn:(id)fp8 finishedWithAuth:(id)fp12 error:(id)fp16;
- (void)signIn:(id)fp8 displayRequest:(id)fp12;
- (id)propertyForKey:(id)fp8;
- (void)setProperty:(id)fp8 forKey:(id)fp12;
- (BOOL)shouldUseKeychain;
- (double)networkLossTimeoutInterval;
- (void)setNetworkLossTimeoutInterval:(double)fp8;
- (void)clearBrowserCookies;
- (id)authentication;
- (void)cancelSigningIn;
- (void)notifyWithName:(id)fp8 webView:(id)fp12 kind:(id)fp16;
- (void)popView;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithAuthentication:(id)fp8 authorizationURL:(id)fp12 keychainItemName:(id)fp16 completionHandler:(id)fp(null);
- (id)initWithAuthentication:(id)fp8 authorizationURL:(id)fp12 keychainItemName:(id)fp16 delegate:(id)fp20 finishedSelector:(SEL)fp24;
- (id)initWithScope:(id)fp8 clientID:(id)fp12 clientSecret:(id)fp16 keychainItemName:(id)fp20 completionHandler:(id)fp(null);
- (id)initWithScope:(id)fp8 clientID:(id)fp12 clientSecret:(id)fp16 keychainItemName:(id)fp20 delegate:(id)fp24 finishedSelector:(SEL)fp28;

@end

