/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMOAuth2SignIn.h"

@class NSString;

@interface GTMOAuth2SignInInternal : GTMOAuth2SignIn
{
    NSString *authorizationEmail_;
    NSString *authorizationTemplate_;
    BOOL shouldUseLoginScope_;
}

+ (id)defaultSourceString;
+ (id)tokenAuthURLWithAuthToken:(id)fp8 service:(id)fp12 source:(id)fp16 URLString:(id)fp20;
+ (id)dictionaryWithClientLoginResponseString:(id)fp8;
+ (void)fetchTokenAuthURLWithValues:(id)fp8 service:(id)fp12 source:(id)fp16 URLString:(id)fp20 completionHandler:(id)fp(null);
+ (void)fetchAuthTokenWithValues:(id)fp8 service:(id)fp12 isSessionOnly:(BOOL)fp16 completionHandler:(id)fp(null);
+ (void)fetchClientLoginValuesWithAuth:(id)fp8 service:(id)fp12 source:(id)fp16 completionHandler:(id)fp(null);
+ (id)nativeClientRedirectURI;
+ (id)googleUserInfoURL;
+ (id)googleRevocationURL;
+ (id)googleTokenURL;
+ (id)googleAuthorizationURL;
+ (id)userInfoHost;
+ (void)setUserInfoHost:(id)fp8;
+ (id)authorizationHost;
+ (void)setAuthorizationHost:(id)fp8;
+ (id)accountsHost;
+ (void)setAccountsHost:(id)fp8;
- (void)setShouldUseLoginScope:(BOOL)fp8;
- (BOOL)shouldUseLoginScope;
- (void)setAuthorizationTemplate:(id)fp8;
- (id)authorizationTemplate;
- (void)setAuthorizationEmail:(id)fp8;
- (id)authorizationEmail;
- (BOOL)cookiesChanged:(id)fp8;
- (BOOL)titleChanged:(id)fp8;
- (id)parametersForWebRequest;
- (BOOL)startSigningIn;
- (void)dealloc;

@end

