/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GTMOAuth2Keychain : _AVAudioSessionCategoryPlayback
{
}

+ (id)keychainQueryForService:(id)fp8 account:(id)fp12;
+ (void)setDefaultKeychain:(id)fp8;
+ (id)defaultKeychain;
- (BOOL)setPassword:(id)fp8 forService:(id)fp12 accessibility:(void *)fp16 account:(id)fp20 error:(id *)fp24;
- (BOOL)removePasswordForService:(id)fp8 account:(id)fp12 error:(id *)fp16;
- (id)passwordForService:(id)fp8 account:(id)fp12 error:(id *)fp16;
- (id)keychainQueryForService:(id)fp8 account:(id)fp12;
- (id)keyForService:(id)fp8 account:(id)fp12;

@end

