/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMOAuth2ViewControllerTouch.h"

@interface GTMOAuth2ViewControllerTouchSharebox : GTMOAuth2ViewControllerTouch
{
}

- (void)webViewDidFinishLoad:(id)fp8;

@end

