/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GTMHTTPFetcher, GTMOAuth2Authentication, NSDictionary, NSTimer, NSURL;

@interface GTMOAuth2SignIn : _AVAudioSessionCategoryPlayback
{
    GTMOAuth2Authentication *auth_;
    NSURL *authorizationURL_;
    NSDictionary *additionalAuthorizationParameters_;
    id delegate_;
    SEL webRequestSelector_;
    SEL finishedSelector_;
    BOOL hasHandledCallback_;
    GTMHTTPFetcher *pendingFetcher_;
    BOOL shouldFetchGoogleUserEmail_;
    BOOL shouldFetchGoogleUserProfile_;
    NSDictionary *userProfile_;
    struct __SCNetworkReachability *reachabilityRef_;
    NSTimer *networkLossTimer_;
    double networkLossTimeoutInterval_;
    BOOL hasNotifiedNetworkLoss_;
    id userData_;
}

+ (void)revokeTokenForGoogleAuthentication:(id)fp8;
+ (id)userInfoFetcherWithAuth:(id)fp8;
+ (id)mutableURLRequestWithURL:(id)fp8 paramString:(id)fp12;
+ (id)standardGoogleAuthenticationForScope:(id)fp8 clientID:(id)fp12 clientSecret:(id)fp16;
+ (id)nativeClientRedirectURI;
+ (id)googleUserInfoURL;
+ (id)googleRevocationURL;
+ (id)googleTokenURL;
+ (id)googleAuthorizationURL;
- (void)setNetworkLossTimeoutInterval:(double)fp8;
- (double)networkLossTimeoutInterval;
- (void)setUserProfile:(id)fp8;
- (id)userProfile;
- (void)setShouldFetchGoogleUserProfile:(BOOL)fp8;
- (BOOL)shouldFetchGoogleUserProfile;
- (void)setShouldFetchGoogleUserEmail:(BOOL)fp8;
- (BOOL)shouldFetchGoogleUserEmail;
- (void)setUserData:(id)fp8;
- (id)userData;
- (void)setPendingFetcher:(id)fp8;
- (id)pendingFetcher;
- (void)setHasHandledCallback:(BOOL)fp8;
- (BOOL)hasHandledCallback;
- (void)setFinishedSelector:(SEL)fp8;
- (SEL)finishedSelector;
- (void)setWebRequestSelector:(SEL)fp8;
- (SEL)webRequestSelector;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAdditionalAuthorizationParameters:(id)fp8;
- (id)additionalAuthorizationParameters;
- (void)setAuthorizationURL:(id)fp8;
- (id)authorizationURL;
- (void)setAuthentication:(id)fp8;
- (id)authentication;
- (void)stopReachabilityCheck;
- (void)reachabilityTimerFired:(id)fp8;
- (void)reachabilityTarget:(struct __SCNetworkReachability *)fp8 changedFlags:(unsigned int)fp12;
- (void)destroyUnreachabilityTimer;
- (void)startReachabilityCheck;
- (void)invokeFinalCallbackWithError:(id)fp8;
- (void)finishSignInWithError:(id)fp8;
- (void)infoFetcher:(id)fp8 finishedWithData:(id)fp12 error:(id)fp16;
- (void)fetchGoogleUserInfo;
- (void)auth:(id)fp8 finishedWithFetcher:(id)fp12 error:(id)fp16;
- (void)handleCallbackReached;
- (BOOL)loadFailedWithError:(id)fp8;
- (BOOL)cookiesChanged:(id)fp8;
- (BOOL)titleChanged:(id)fp8;
- (BOOL)requestRedirectedToRequest:(id)fp8;
- (void)closeTheWindow;
- (void)windowWasClosed;
- (BOOL)startWebRequest;
- (id)parametersForWebRequest;
- (BOOL)startSigningIn;
- (void)cancelSigningIn;
- (void)dealloc;
- (id)initWithAuthentication:(id)fp8 authorizationURL:(id)fp12 delegate:(id)fp16 webRequestSelector:(SEL)fp20 finishedSelector:(SEL)fp24;

@end

