/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableDictionary, NSString;

@interface GTMURLBuilder : _AVAudioSessionCategoryPlayback
{
    NSMutableDictionary *params_;
    NSString *baseURLString_;
}

+ (id)builderWithURL:(id)fp8;
+ (id)builderWithString:(id)fp8;
- (id)baseURLString;
- (BOOL)isEqual:(id)fp8;
- (id)URLString;
- (id)URL;
- (id)parameters;
- (void)setParameters:(id)fp8;
- (void)removeParameter:(id)fp8;
- (id)valueForParameter:(id)fp8;
- (void)setIntegerValue:(int)fp8 forParameter:(id)fp12;
- (void)setValue:(id)fp8 forParameter:(id)fp12;
- (void)dealloc;
- (id)initWithString:(id)fp8;
- (id)init;

@end

