/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableDictionary;

@interface GTMURLCache : _AVAudioSessionCategoryPlayback
{
    NSMutableDictionary *responses_;
    unsigned int memoryCapacity_;
    unsigned int totalDataSize_;
    double reservationInterval_;
}

- (unsigned int)totalDataSize;
- (id)responses;
- (void)setReservationInterval:(double)fp8;
- (void)setMemoryCapacity:(unsigned int)fp8;
- (unsigned int)memoryCapacity;
- (void)removeAllCachedResponses;
- (void)removeCachedResponseForRequest:(id)fp8;
- (id)cachedResponseForRequest:(id)fp8;
- (void)storeCachedResponse:(id)fp8 forRequest:(id)fp12;
- (void)pruneCacheResponses;
- (id)description;
- (void)dealloc;
- (id)initWithMemoryCapacity:(unsigned int)fp8;
- (id)init;

@end

