/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DefaultSHKConfigurator.h"

@class NSDictionary;

@interface LegacySHKConfigurator : DefaultSHKConfigurator
{
    NSDictionary *configuration;
}

- (id)configuration;
- (id)performSelector:(SEL)fp8;
- (BOOL)respondsToSelector:(SEL)fp8;
- (id)init;
- (void)dealloc;

@end

