/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface MASFCookieRequest : _AVAudioSessionCategoryPlayback
{
    struct __MASFCookieRequestPrivate *cpp_;
    id <MASFCookieRequestObserver> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)onRequestUpdated:(id)fp8;
- (void)onRequestFailed:(id)fp8;
- (void)onRequestComplete:(id)fp8;
- (void)beginRequest;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8;

@end

