/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSArray, NSDate, NSString;

@interface MASFUserSettingsResponse : _AVAudioSessionCategoryPlayback
{
    int status_;
    NSString *email_;
    NSArray *services_;
    NSDate *startTime_;
    NSDate *endTime_;
}

- (id)endTime;
- (id)startTime;
- (id)email;
- (id)services;
- (int)status;
- (id)description;
- (void)dealloc;

@end

