/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MASFUserServicePreferences.h"

@interface MASFUserServicePreferences (CPP)
- (void)copyInto:(struct UserServicePreferences *)fp8;
- (struct UserServicePreferences *)cppValue;
- (id)initWithUserServicePreferences:(const struct UserServicePreferences *)fp8;
@end

