/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface MASFUserIdentification : _AVAudioSessionCategoryPlayback
{
    NSString *authToken_;
    NSString *userEmail_;
}

- (id)userEmail;
- (id)authToken;
- (void)dealloc;
- (id)initWithEmail:(id)fp8 authToken:(id)fp12;

@end

