/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSArray;

@interface MASFServicePreference : _AVAudioSessionCategoryPlayback
{
    int serviceId_;
    NSArray *subscriptions_;
}

+ (id)servicePreferenceWithServiceId:(int)fp8 subscriptionName:(id)fp12 notificationModes:(id)fp16;
+ (id)servicePreferenceWithServiceId:(int)fp8 subscriptionName:(id)fp12 notificationMode:(int)fp16;
- (void)setSubscriptions:(id)fp8;
- (id)subscriptions;
- (void)setServiceId:(int)fp8;
- (int)serviceId;
- (id)description;
- (void)dealloc;
- (id)initWithServiceId:(int)fp8 subscriptionName:(id)fp12 notificationMode:(int)fp16;
- (id)initWithServiceId:(int)fp8 subscriptions:(id)fp12;

@end

