/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MASFUserIdentification.h"

@interface MASFUserIdentification (CPP)
- (void)dealloc;
- (void)copyInto:(struct UserIdentification *)fp8;
- (struct UserIdentification *)cppValue;
- (id)initWithUserIdentification:(const struct UserIdentification *)fp8;
@end

