/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface MASFMuxConfig : _AVAudioSessionCategoryPlayback
{
    struct __MASFMuxConfigPrivate *cpp_;
}

- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;
- (struct MuxConfig *)muxConfig;
- (id)initWithClientLocale:(id)fp8 encoding:(id)fp12 masfURL:(id)fp16 platformId:(id)fp20 applicationName:(id)fp24 applicationVersion:(id)fp28 distributionChannel:(id)fp32;

@end

