/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class MASFMuxConfig, NSTimer;

@interface MASFServiceMux : _AVAudioSessionCategoryPlayback
{
    struct __MASFServiceMuxPrivate *cpp_;
    MASFMuxConfig *muxConfig_;
    NSTimer *timer_;
    BOOL initialized_;
    long long cookie_;
}

+ (void)initializeLogging;
+ (id)sharedServiceMux;
- (void)startDeferredRequests:(id)fp8;
- (void)requestQueueChanged:(struct MASFRequestQueue *)fp8;
- (void)recalculateTimer;
- (void)makeRequest:(id)fp8 serviceURI:(id)fp12 successBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeRequest:(id)fp8 serviceURI:(id)fp12 target:(id)fp16 onSuccess:(SEL)fp20 onError:(SEL)fp24;
- (void)setCookie:(long long)fp8;
- (BOOL)isInitialized;
- (void)dealloc;
- (id)muxConfig;
- (void)setMuxConfig:(id)fp8;
- (id)init;

@end

