/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface MASFGoogleMobileEventLogRequest : _AVAudioSessionCategoryPlayback
{
    struct __MASFGoogleMobileEventLogRequestPrivate *cpp_;
    id <MASFGoogleMobileEventLogRequestObserver> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)onRequestUpdated:(id)fp8;
- (void)onRequestFailed:(id)fp8;
- (void)onRequestComplete:(id)fp8;
- (void)cancelRequest;
- (void)beginRequest;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 actionType:(int)fp12 dropListItem:(int)fp16 dropListOffset:(int)fp20 duration:(int)fp24 locationWasAvailable:(_Bool)fp28 dropListItems:(id)fp32 text:(id)fp36 timestampMs:(long long)fp40 shouldFlush:(_Bool)fp48 forUtterance:(id)fp52;

@end

