/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"
#import "NSFastEnumeration-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@interface PBArray : _AVAudioSessionCategoryPlayback <NSCopying, NSMutableCopying, NSFastEnumeration>
{
    int _valueType;
    unsigned int _capacity;
    unsigned int _count;
    void *_data;
}

+ (id)arrayWithInt32s:(int)fp8;
+ (id)arrayWithInt32:(int)fp8;
+ (id)arrayWithObjects:(id)fp8;
+ (id)arrayWithObject:(id)fp8;
+ (id)arrayWithArray:(id)fp8 valueType:(int)fp12;
+ (id)arrayWithValues:(const void *)fp8 count:(unsigned int)fp12 valueType:(int)fp16;
+ (id)arrayWithValueType:(int)fp8;
- (unsigned int)count;
- (int)valueType;
- (id)initWithInt32:(int)fp8;
- (id)initWithObject:(id)fp8;
- (id)initWithArray:(id)fp8 valueType:(int)fp12;
- (id)initWithValues:(const void *)fp8 count:(unsigned int)fp12 valueType:(int)fp16;
- (id)initWithValueType:(int)fp8;
- (id)arrayByAppendingArray:(id)fp8;
- (id)array;
- (double)doubleAtIndex:(unsigned int)fp8;
- (float)floatAtIndex:(unsigned int)fp8;
- (unsigned long long)uint64AtIndex:(unsigned int)fp8;
- (long long)int64AtIndex:(unsigned int)fp8;
- (unsigned int)uint32AtIndex:(unsigned int)fp8;
- (int)int32AtIndex:(unsigned int)fp8;
- (BOOL)boolAtIndex:(unsigned int)fp8;
- (id)objectAtIndex:(unsigned int)fp8;
- (id)description;
- (void)dealloc;
- (id)mutableCopyWithZone:(struct _NSZone *)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)isEqual:(id)fp8;
- (void)enumerateInt32sUsingBlock:(id)fp(null);
- (void)enumerateObjectsUsingBlock:(id)fp(null);
- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct6 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (const void *)data;
- (unsigned int)hash;
- (id)initWithCount:(unsigned int)fp8 valueType:(int)fp12;

@end

