/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSInputStream, NSMutableData;

@interface PBCodedInputStream : _AVAudioSessionCategoryPlayback
{
    NSMutableData *buffer;
    unsigned int bufferSize;
    unsigned int bufferSizeAfterLimit;
    unsigned int bufferPos;
    NSInputStream *input;
    int lastTag;
    unsigned int totalBytesRetired;
    unsigned int currentLimit;
    unsigned int recursionDepth;
}

+ (id)streamWithInputStream:(id)fp8;
+ (id)streamWithData:(id)fp8;
- (void)setInput:(id)fp8;
- (id)input;
- (void)setBuffer:(id)fp8;
- (id)buffer;
- (void)skipRawData:(unsigned int)fp8;
- (id)readRawData:(unsigned int)fp8;
- (BOOL)readRawByte;
- (BOOL)refillBuffer:(BOOL)fp8;
- (BOOL)isAtEnd;
- (unsigned int)bytesUntilLimit;
- (void)popLimit:(unsigned int)fp8;
- (void)recomputeBufferSizeAfterLimit;
- (unsigned int)pushLimit:(unsigned int)fp8;
- (void)resetSizeCounter;
- (long long)readRawLittleEndian64;
- (int)readRawLittleEndian32;
- (long long)readRawVarint64;
- (int)readRawVarint32;
- (long long)readSInt64;
- (int)readSInt32;
- (long long)readSFixed64;
- (int)readSFixed32;
- (int)readEnum;
- (int)readUInt32;
- (id)readData;
- (void)readMessage:(id)fp8 extensionRegistry:(id)fp12;
- (void)readUnknownGroup:(int)fp8 builder:(id)fp12;
- (void)readGroup:(int)fp8 builder:(id)fp12 extensionRegistry:(id)fp16;
- (id)readString;
- (BOOL)readBool;
- (int)readFixed32;
- (long long)readFixed64;
- (int)readInt32;
- (long long)readInt64;
- (long long)readUInt64;
- (float)readFloat;
- (double)readDouble;
- (void)skipMessage;
- (BOOL)skipField:(int)fp8;
- (void)checkLastTagWas:(int)fp8;
- (int)readTag;
- (id)initWithInputStream:(id)fp8;
- (id)initWithData:(id)fp8;
- (void)dealloc;

@end

