/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableData, NSOutputStream;

@interface PBCodedOutputStream : _AVAudioSessionCategoryPlayback
{
    NSMutableData *buffer_;
    unsigned int position_;
    NSOutputStream *output_;
}

+ (id)streamWithData:(id)fp8;
+ (id)streamWithOutputStream:(id)fp8;
+ (id)streamWithOutputStream:(id)fp8 bufferSize:(int)fp12;
- (void)writeRawLittleEndian64:(long long)fp8;
- (void)writeRawLittleEndian32:(int)fp8;
- (void)writeRawVarint64:(long long)fp8;
- (void)writeRawVarint32:(int)fp8;
- (void)writeTag:(int)fp8 format:(int)fp12;
- (void)writeRawPtr:(const void *)fp8 offset:(unsigned int)fp12 length:(unsigned int)fp16;
- (void)writeRawData:(id)fp8;
- (void)writeRawByte:(unsigned char)fp8;
- (void)checkNoSpaceLeft;
- (int)spaceLeft;
- (void)flush;
- (void)refreshBuffer;
- (void)writeRawMessageSetExtension:(int)fp8 value:(id)fp12;
- (void)writeMessageSetExtension:(int)fp8 value:(id)fp12;
- (void)writeUnknownGroups:(int)fp8 values:(id)fp12;
- (void)writeGroups:(int)fp8 values:(id)fp12;
- (void)writeDatas:(int)fp8 values:(id)fp12;
- (void)writeMessages:(int)fp8 values:(id)fp12;
- (void)writeStrings:(int)fp8 values:(id)fp12;
- (void)writeEnums:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeBools:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeSFixed32s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeSFixed64s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeSInt64s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeSInt32s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeFixed32s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeFixed64s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeUInt32s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeInt32s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeInt64s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeUInt64s:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeFloats:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeDoubles:(int)fp8 values:(id)fp12 tag:(unsigned int)fp16;
- (void)writeSInt64:(int)fp8 value:(long long)fp12;
- (void)writeSInt64NoTag:(long long)fp8;
- (void)writeSInt32:(int)fp8 value:(int)fp12;
- (void)writeSInt32NoTag:(int)fp8;
- (void)writeSFixed64:(int)fp8 value:(long long)fp12;
- (void)writeSFixed64NoTag:(long long)fp8;
- (void)writeSFixed32:(int)fp8 value:(int)fp12;
- (void)writeSFixed32NoTag:(int)fp8;
- (void)writeEnum:(int)fp8 value:(int)fp12;
- (void)writeEnumNoTag:(int)fp8;
- (void)writeUInt32:(int)fp8 value:(unsigned int)fp12;
- (void)writeUInt32NoTag:(unsigned int)fp8;
- (void)writeData:(int)fp8 value:(id)fp12;
- (void)writeDataNoTag:(id)fp8;
- (void)writeMessage:(int)fp8 value:(id)fp12;
- (void)writeMessageNoTag:(id)fp8;
- (void)writeUnknownGroup:(int)fp8 value:(id)fp12;
- (void)writeUnknownGroupNoTag:(int)fp8 value:(id)fp12;
- (void)writeGroup:(int)fp8 value:(id)fp12;
- (void)writeGroupNoTag:(int)fp8 value:(id)fp12;
- (void)writeString:(int)fp8 value:(id)fp12;
- (void)writeStringNoTag:(id)fp8;
- (void)writeBool:(int)fp8 value:(BOOL)fp12;
- (void)writeBoolNoTag:(BOOL)fp8;
- (void)writeFixed32:(int)fp8 value:(unsigned int)fp12;
- (void)writeFixed32NoTag:(unsigned int)fp8;
- (void)writeFixed64:(int)fp8 value:(unsigned long long)fp12;
- (void)writeFixed64NoTag:(unsigned long long)fp8;
- (void)writeInt32:(int)fp8 value:(int)fp12;
- (void)writeInt32NoTag:(int)fp8;
- (void)writeInt64:(int)fp8 value:(long long)fp12;
- (void)writeInt64NoTag:(long long)fp8;
- (void)writeUInt64:(int)fp8 value:(unsigned long long)fp12;
- (void)writeUInt64NoTag:(unsigned long long)fp8;
- (void)writeFloat:(int)fp8 value:(float)fp12;
- (void)writeFloatNoTag:(float)fp8;
- (void)writeDouble:(int)fp8 value:(double)fp12;
- (void)writeDoubleNoTag:(double)fp8;
- (id)initWithOutputStream:(id)fp8 data:(id)fp12;
- (void)dealloc;

@end

