/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@protocol PBDescriptor <NSObject, NSCopying>
- (id)extensionRanges;
- (id)extensions;
- (id)enums;
- (id)fields;
- (id)name;
- (id)extensionWithName:(id)fp8;
- (id)extensionWithNumber:(unsigned int)fp8;
- (id)enumWithName:(id)fp8;
- (id)enumWithNumber:(unsigned int)fp8;
- (id)fieldWithName:(id)fp8;
- (id)fieldWithNumber:(unsigned int)fp8;
@end

