/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol PBExtensionField
- (id)descriptor;
- (CDAnonymousUnion1)defaultPBValue;
- (id)defaultValue;
- (id)containingType;
- (BOOL)isRepeated;
- (int)wireType;
- (int)fieldNumber;
- (void)writeValue:(id)fp8 includingTagToCodedOutputStream:(id)fp12;
- (unsigned int)computeSerializedSizeIncludingTag:(id)fp8;
- (unsigned int)computePBSerializedSizesIncludingTags:(id)fp8;
- (unsigned int)computePBSerializedSizeIncludingTag:(CDAnonymousUnion1)fp8;
- (void)writePBValues:(id)fp8 includingTagsToCodedOutputStream:(id)fp12;
- (void)writePBValue:(CDAnonymousUnion1)fp8 includingTagToCodedOutputStream:(id)fp16;
- (void)mergeFromCodedInputStream:(id)fp8 unknownFields:(id)fp12 extensionRegistry:(id)fp16 builder:(id)fp20 tag:(int)fp24;
@end

