/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableDictionary;

@interface PBExtensionRegistry : _AVAudioSessionCategoryPlayback
{
    NSMutableDictionary *mutableClassMap_;
}

+ (id)registry;
- (void)addExtensions:(id)fp8;
- (id)getExtension:(id)fp8 fieldNumber:(int)fp12;
- (void)addExtension:(id)fp8;
- (id)extensionMapForContainingType:(id)fp8;
- (void)dealloc;
- (id)init;

@end

