/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface PBExtensionRange : _AVAudioSessionCategoryPlayback
{
    unsigned int start_;
    unsigned int end_;
}

- (unsigned int)end;
- (unsigned int)start;
- (id)initWithRangeDescription:(CDAnonymousStruct2 *)fp8;

@end

