/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "PBFieldDescriptor-Protocol.h"

@class PBFieldOptions;

@interface PBFieldDescriptor : _AVAudioSessionCategoryPlayback <PBFieldDescriptor>
{
    unsigned int number_;
    CDAnonymousUnion2 defaultValue_;
    SEL nameSel_;
    SEL clearSel_;
    unsigned long offset_;
    unsigned int flags_;
    unsigned int tag_;
    BOOL hasDefaultValue_;
    int type_;
    SEL setSel_;
    PBFieldOptions *fieldOptions_;
    SEL hasSel_;
    unsigned int hasIndex_;
    SEL valueAtIndexSel_;
    SEL replaceAtIndexWithSel_;
    SEL addValueSel_;
    SEL addAllValuesSel_;
    SEL mergeSel_;
    Class msgClass_;
    void *enumVerifier_;
}

+ (void)initialize;
+ (id)defaultNSData;
- (Class)msgClass;
- (SEL)mergeSel;
- (SEL)addAllValuesSel;
- (SEL)addValueSel;
- (SEL)replaceAtIndexWithSel;
- (SEL)valueAtIndexSel;
- (unsigned int)hasIndex;
- (SEL)setSel;
- (SEL)hasSel;
- (id)fieldOptions;
- (BOOL)hasDefaultValue;
- (unsigned int)tag;
- (unsigned long)offset;
- (SEL)clearSel;
- (SEL)nameSel;
- (int)type;
- (unsigned int)number;
- (CDAnonymousUnion1)defaultValue;
- (id)setToNilValue;
- (BOOL)isValidEnumValue:(int)fp8;
- (BOOL)isMessage;
- (BOOL)isPackable;
- (BOOL)isRepeated;
- (BOOL)isOptional;
- (BOOL)isRequired;
- (id)name;
- (void)dealloc;
- (id)initWithFieldDescription:(CDAnonymousStruct5 *)fp8 rootClass:(Class)fp12;

@end

