/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol PBFieldDescriptor <NSObject>
- (BOOL)isMessage;
- (BOOL)isPackable;
- (BOOL)isRepeated;
- (BOOL)isOptional;
- (BOOL)isRequired;
- (CDAnonymousUnion1)defaultValue;
- (BOOL)hasDefaultValue;
- (int)type;
- (unsigned int)number;
- (id)name;
- (BOOL)isValidEnumValue:(int)fp8;
@end

