/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PBRootObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSMutableCopying-Protocol.h"
#import "PBMessage-Protocol.h"

@class NSMutableDictionary, PBUnknownFieldSet_Builder;

@interface PBGeneratedMessage : PBRootObject <PBMessage, NSCoding, NSCopying, NSMutableCopying>
{
    struct PBGeneratedMessage_Storage *messageStorage_;
    PBUnknownFieldSet_Builder *unknownFields_;
    NSMutableDictionary *extensionMap_;
    NSMutableDictionary *extensionRegistry_;
}

+ (BOOL)resolveInstanceMethod:(SEL)fp8;
+ (id)builderWithPrototype:(id)fp8;
+ (id)builder;
+ (id)parseDelimitedFromCodedInputStream:(id)fp8 extensionRegistry:(id)fp12;
+ (id)parseDelimitedFromCodedInputStream:(id)fp8;
+ (id)parseFromCodedInputStream:(id)fp8 extensionRegistry:(id)fp12;
+ (id)parseFromCodedInputStream:(id)fp8;
+ (id)parseFromInputStream:(id)fp8 extensionRegistry:(id)fp12;
+ (id)parseFromInputStream:(id)fp8;
+ (id)parseFromData:(id)fp8 extensionRegistry:(id)fp12;
+ (id)parseFromData:(id)fp8;
+ (id)defaultInstance;
+ (id)descriptor;
+ (id)allocAsDefaultInstance;
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (void)initialize;
- (void)setExtensionRegistry:(id)fp8;
- (id)extensionRegistry;
- (id)unknownFields;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (unsigned int)serializedSize;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (id)mergeFrom:(id)fp8;
- (id)mergeFromCodedInputStream:(id)fp8 extensionRegistry:(id)fp12;
- (BOOL)parseUnknownField:(id)fp8 extensionRegistry:(id)fp12 tag:(int)fp16;
- (id)mergeUnknownFields:(id)fp8;
- (id)mutableUnknownFields;
- (void)setUnknownFields:(id)fp8;
- (id)buildPartial;
- (id)build;
- (id)toBuilder;
- (id)builder;
- (id)mergeDelimitedFromCodedInputStream:(id)fp8 extensionRegistry:(id)fp12;
- (id)mergeDelimitedFromCodedInputStream:(id)fp8;
- (id)mergeFromInputStream:(id)fp8 extensionRegistry:(id)fp12;
- (id)mergeFromInputStream:(id)fp8;
- (id)mergeFromData:(id)fp8 extensionRegistry:(id)fp12;
- (id)mergeFromData:(id)fp8;
- (id)mergeFromCodedInputStream:(id)fp8;
- (id)clearExtension:(id)fp8;
- (id)setExtension:(id)fp8 index:(unsigned int)fp12 value:(id)fp16;
- (id)addExtension:(id)fp8 value:(id)fp12;
- (id)setExtension:(id)fp8 value:(id)fp12;
- (unsigned int)extensionsSerializedSize;
- (id)extensionsDescriptionForRange:(id)fp8;
- (void)writeExtensionsToCodedOutputStream:(id)fp8 range:(id)fp12;
- (BOOL)hasExtension:(id)fp8;
- (void)ensureExtensionIsRegistered:(id)fp8;
- (id)getExtension:(id)fp8;
- (BOOL)isInitialized:(id)fp8;
- (void)writeField:(id)fp8 toCodedOutputStream:(id)fp12;
- (void)writeDelimitedToCodedOutputStream:(id)fp8;
- (void)writeDelimitedToOutputStream:(id)fp8;
- (void)writeToCodedOutputStream:(id)fp8;
- (void)writeToOutputStream:(id)fp8;
- (id)delimitedData;
- (id)data;
- (id)defaultInstance;
- (id)descriptor;
- (BOOL)isInitialized;
- (void)internalClear;
- (void)clear;
- (id)mutableCopyWithZone:(struct _NSZone *)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)copyFieldsInto:(id)fp8 zone:(struct _NSZone *)fp12 mutable:(BOOL)fp16;
- (void)dealloc;
- (id)initAsDefaultInstance;
- (id)init;

@end

