/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "PBRootObject-Protocol.h"

@interface PBRootObject : _AVAudioSessionCategoryPlayback <PBRootObject>
{
}

+ (BOOL)resolveClassMethod:(SEL)fp8;
+ (void)registerExtension:(id)fp8 byName:(const char *)fp12;
+ (void)initialize;

@end

