/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSData, NSString;

@interface PBString : _AVAudioSessionCategoryPlayback
{
    NSString *string_;
    NSData *data_;
    int lock_;
}

- (void)getCharacters:(unsigned short *)fp8 range:(struct _NSRange)fp12;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (id)mutableCopyWithZone:(struct _NSZone *)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (unsigned short)characterAtIndex:(unsigned int)fp8;
- (unsigned int)length;
- (void)initStringValue;
- (void)dealloc;
- (id)initWithData:(id)fp8;

@end

