/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class NSMutableArray, UIPopoverController, UIScrollView, UIView;

@interface PhotoPickerController : _AVAudioSessionCategoryPlayback <UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIPopoverControllerDelegate>
{
    UIView *buttonsView_;
    NSMutableArray *images_;
    UIScrollView *previewScrollView_;
    NSMutableArray *imageViews_;
    UIView *previewView_;
    UIPopoverController *popoverController_;
    BOOL hasPickedPhoto_;
    id <PhotoPickerDelegate> delegate_;
}

+ (id)buttonWithTitle:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)imagePickerControllerDidCancel:(id)fp8;
- (void)imagePickerController:(id)fp8 didFinishPickingMediaWithInfo:(id)fp12;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)setImages:(id)fp8;
- (void)removePhoto:(id)fp8;
- (void)drawImageViews;
- (void)flushImageViews;
- (void)layoutImagePreviews;
- (void)didPressPick;
- (void)didPressCancel;
- (void)choosePhoto:(id)fp8;
- (void)takePhoto:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (void)dealloc;

@end

