/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol PhotoPickerDelegate
- (void)photoPickerDidCancel:(id)fp8;
- (void)photoPicker:(id)fp8 didPickImages:(id)fp12;
@end

