/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "AudiencePickerDelegate-Protocol.h"
#import "GooglePlusDelegate-Protocol.h"
#import "PhotoPickerDelegate-Protocol.h"
#import "ShareboxViewDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class AudiencePickerController, NSArray, NSString, NSURL, PhotoPickerController, ShareboxView, UIImage;

@interface ShareboxController : _AVAudioSessionCategoryPlayback <ShareboxViewDelegate, AudiencePickerDelegate, PhotoPickerDelegate, GooglePlusDelegate, UINavigationControllerDelegate>
{
    ShareboxView *shareboxView_;
    AudiencePickerController *audiencePicker_;
    PhotoPickerController *photoPicker_;
    NSArray *jpegDataToShare_;
    NSArray *circles_;
    NSArray *selectedCircles_;
    NSArray *selectedMetaCircles_;
    id <ShareboxDelegate> delegate_;
    NSURL *linkToShare_;
    NSString *textToShare_;
    NSString *applicationName_;
    UIImage *previewImage_;
    NSString *previewText_;
    NSString *previewTitle_;
    UIImage *avatar_;
    NSString *displayName_;
    BOOL loadedACLs_;
    BOOL finished_;
}

- (id)applicationName;
- (id)textToShare;
- (void)setJpegDataToShare:(id)fp8;
- (id)jpegDataToShare;
- (id)linkToShare;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)shareboxViewPickACLs:(id)fp8;
- (void)shareboxViewPickPhoto:(id)fp8 fromView:(id)fp12;
- (void)didPressPost:(id)fp8;
- (void)didPressCancel:(id)fp8;
- (void)photoPickerDidCancel:(id)fp8;
- (void)photoPicker:(id)fp8 didPickImages:(id)fp12;
- (void)googlePlusDidGetUserInfo:(id)fp8;
- (void)googlePlusDidLogOut:(id)fp8;
- (void)clearSharebox;
- (void)googlePlusDidFinishAuth:(id)fp8;
- (void)googlePlusDidReceiveError:(id)fp8;
- (void)dismissGooglePlusViewController:(id)fp8;
- (void)presentGooglePlusViewController:(id)fp8;
- (BOOL)shouldEnableShareButton;
- (id)addDefaultScheme:(id)fp8;
- (void)showPhotoPickerFromView:(id)fp8;
- (void)audiencePicker:(id)fp8 didPickCircles:(id)fp12 metaCircles:(id)fp16;
- (void)audiencePickerDidCancel:(id)fp8;
- (void)showAudiencePicker;
- (void)getACLs:(id)fp(null);
- (void)clearACLs;
- (void)insertActivityToStream;
- (void)finishInsertingWithObject:(id)fp8 jpegData:(id)fp12;
- (void)insertActivityToStreamWithJPEGData:(id)fp8;
- (id)selectedAcl;
- (void)loadPreviewForLink;
- (void)setApplicationName:(id)fp8;
- (id)imagesToShare;
- (void)setImagesToShare:(id)fp8;
- (void)setLinkToShare:(id)fp8;
- (void)setTextToShare:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)setNavigationItem;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithCoder:(id)fp8;
- (id)init;
- (void)initState;

@end

