/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPPlaceholderTextView, ShareboxCirclesOptionsView, ShareboxPhotosOptionsView, UIImageView, UILabel, UIView;

@interface ShareboxView : _AVAudioSessionCategoryPlayback
{
    UIView *inputPane_;
    UIView *buttonBorder_;
    UIView *textViewPane_;
    UIImageView *avatar_;
    UILabel *displayNameLabel_;
    UILabel *fromLabel_;
    UILabel *applicationNameLabel_;
    GIPPlaceholderTextView *textView_;
    UIView *previewPane_;
    UIView *previewBorder_;
    UILabel *previewText_;
    UILabel *previewTitle_;
    UIImageView *previewImage_;
    UIView *buttonPane_;
    ShareboxCirclesOptionsView *circlesOptionsView_;
    ShareboxPhotosOptionsView *photosOptionsView_;
    id <ShareboxViewDelegate> delegate_;
    BOOL showPhotosOptionView_;
}

- (BOOL)showPhotosOptionView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)resignFirstResponder;
- (void)reset;
- (void)pickACLs;
- (void)chooseAPhoto:(id)fp8;
- (void)layoutSubviews;
- (void)addButtonPane;
- (void)addInputPane;
- (void)addSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setShowPhotosOptionView:(BOOL)fp8;
- (void)setApplicationName:(id)fp8;
- (id)applicationName;
- (void)setImages:(id)fp8;
- (id)images;
- (id)displayName;
- (void)setDisplayName:(id)fp8;
- (id)placeholder;
- (void)setPlaceholder:(id)fp8;
- (id)avatar;
- (void)setAvatar:(id)fp8;
- (void)setMetaCircles:(id)fp8 circles:(id)fp12;
- (id)previewTitle;
- (void)setPreviewTitle:(id)fp8;
- (id)previewText;
- (void)setPreviewText:(id)fp8;
- (id)previewImage;
- (void)setPreviewImage:(id)fp8;
- (id)textToShare;
- (void)setTextToShare:(id)fp8;

@end

