/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ShareboxOptionsView.h"

@class AudienceScrollView;

@interface ShareboxCirclesOptionsView : ShareboxOptionsView
{
    AudienceScrollView *audienceScrollView_;
}

- (void)setMetaCircles:(id)fp8 circles:(id)fp12;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithMetaCircles:(id)fp8 circles:(id)fp12 target:(id)fp16 selector:(SEL)fp20;

@end

