/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface ShareboxNavigationController : _AVAudioSessionCategoryPlayback
{
}

- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (BOOL)disablesAutomaticKeyboardDismissal;
- (id)popViewControllerAnimated:(BOOL)fp8;
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (void)viewDidLoad;

@end

