/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ShareboxOptionsView.h"

@class NSArray, NSMutableArray, UIScrollView;

@interface ShareboxPhotosOptionsView : ShareboxOptionsView
{
    NSMutableArray *imageViews_;
    UIScrollView *imagesScrollView_;
    NSArray *photos_;
}

- (id)photos;
- (void)setPhotos:(id)fp8;
- (void)layoutImages;
- (void)flushImageViews;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithPhotos:(id)fp8 target:(id)fp12 selector:(SEL)fp16;

@end

