/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSOperationQueue, UIViewController;

@interface SHK : _AVAudioSessionCategoryPlayback
{
    UIViewController *currentView;
    UIViewController *pendingView;
    BOOL isDismissingView;
    NSOperationQueue *offlineQueue;
    UIViewController *rootViewController;
    UIViewController *currentRootViewController;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (BOOL)connected;
+ (id)error:(id)fp8;
+ (void)flushOfflineQueue;
+ (BOOL)addToOfflineQueue:(id)fp8 forSharer:(id)fp12;
+ (void)saveOfflineQueueList:(id)fp8;
+ (id)getOfflineQueueList;
+ (id)offlineQueueListPath;
+ (id)offlineQueuePath;
+ (id)sharersDictionary;
+ (void)logoutOfService:(id)fp8;
+ (void)logoutOfAll;
+ (void)removeAuthValueForKey:(id)fp8 forSharer:(id)fp12;
+ (void)setAuthValue:(id)fp8 forKey:(id)fp12 forSharer:(id)fp16;
+ (id)getAuthValueForKey:(id)fp8 forSharer:(id)fp12;
+ (void)setUserExclusions:(id)fp8;
+ (id)getUserExclusions;
+ (void)setFavorites:(id)fp8 forType:(int)fp12;
+ (void)pushOnFavorites:(id)fp8 forType:(int)fp12;
+ (id)favoriteSharersForType:(int)fp8;
+ (int)modalTransitionStyle;
+ (int)modalPresentationStyle;
+ (int)barStyle;
+ (void)setRootViewController:(id)fp8;
+ (void)initialize;
+ (id)currentHelper;
- (void)setOfflineQueue:(id)fp8;
- (id)offlineQueue;
- (void)setCurrentRootViewController:(id)fp8;
- (id)currentRootViewController;
- (void)setRootViewController:(id)fp8;
- (id)rootViewController;
- (void)setIsDismissingView:(BOOL)fp8;
- (BOOL)isDismissingView;
- (void)setPendingView:(id)fp8;
- (id)pendingView;
- (void)setCurrentView:(id)fp8;
- (id)currentView;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)getTopViewController:(id)fp8;
- (void)viewWasDismissed;
- (void)showPendingView;
- (void)hideCurrentViewControllerAnimated:(BOOL)fp8;
- (void)hideCurrentViewController;
- (id)getCurrentRootViewController;
- (void)showViewController:(id)fp8;
- (BOOL)dismissViewControllerAnimated:(BOOL)fp8 completion:(id)fp(null);
- (id)rootViewForCustomUIDisplay;
- (void)dealloc;

@end

