/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString, SHKFormController, SHKFormFieldSettings, UISwitch, UITextField;

@interface SHKFormFieldCell : _AVAudioSessionCategoryPlayback
{
    SHKFormFieldSettings *settings;
    float labelWidth;
    UITextField *textField;
    UISwitch *toggle;
    NSString *tmpValue;
    SHKFormController *form;
}

- (void)setForm:(id)fp8;
- (id)form;
- (void)setTmpValue:(id)fp8;
- (id)tmpValue;
- (void)setToggle:(id)fp8;
- (id)toggle;
- (void)setTextField:(id)fp8;
- (void)setLabelWidth:(float)fp8;
- (float)labelWidth;
- (id)settings;
- (id)getValue;
- (void)setValue:(id)fp8;
- (void)setSettings:(id)fp8;
- (void)setSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (void)layoutSubviews;
- (id)getTextField;
- (void)dealloc;

@end

