/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITextViewDelegate-Protocol.h"

@class UITextView;

@interface SHKFormControllerLargeTextField : _AVAudioSessionCategoryPlayback <UITextViewDelegate>
{
    id <SHKFormControllerLargeTextFieldDelegate> delegate;
    UITextView *textView;
}

- (void)setTextView:(id)fp8;
- (id)textView;
- (id)delegate;
- (void)save;
- (void)cancel;
- (void)keyboardWillShow:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)loadView;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12 delegate:(id)fp16;
- (void)dealloc;

@end

