/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface SHKFormFieldSettings : _AVAudioSessionCategoryPlayback
{
    NSString *label;
    NSString *key;
    int type;
    NSString *start;
}

+ (id)label:(id)fp8 key:(id)fp12 type:(int)fp16 start:(id)fp20;
- (void)setStart:(id)fp8;
- (id)start;
- (void)setType:(int)fp8;
- (int)type;
- (void)setKey:(id)fp8;
- (id)key;
- (void)setLabel:(id)fp8;
- (id)label;
- (void)dealloc;

@end

