/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSData, NSMutableDictionary, NSString, NSURL, UIImage;

@interface SHKItem : _AVAudioSessionCategoryPlayback
{
    int shareType;
    NSURL *URL;
    UIImage *image;
    NSString *title;
    NSString *text;
    NSString *tags;
    NSData *data;
    NSString *mimeType;
    NSString *filename;
    NSMutableDictionary *custom;
}

+ (id)itemFromDictionary:(id)fp8;
+ (id)file:(id)fp8 filename:(id)fp12 mimeType:(id)fp16 title:(id)fp20;
+ (id)text:(id)fp8;
+ (id)image:(id)fp8 title:(id)fp12;
+ (id)image:(id)fp8;
+ (id)URL:(id)fp8 title:(id)fp12;
+ (id)URL:(id)fp8;
- (void)setCustom:(id)fp8;
- (id)custom;
- (void)setFilename:(id)fp8;
- (id)filename;
- (void)setMimeType:(id)fp8;
- (id)mimeType;
- (void)setData:(id)fp8;
- (id)data;
- (void)setTags:(id)fp8;
- (id)tags;
- (void)setText:(id)fp8;
- (id)text;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setURL:(id)fp8;
- (id)URL;
- (void)setShareType:(int)fp8;
- (int)shareType;
- (id)shareTypeToString:(int)fp8;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)customBoolForSwitchKey:(id)fp8;
- (id)customValueForKey:(id)fp8;
- (void)setCustomValue:(id)fp8 forKey:(id)fp12;
- (void)dealloc;

@end

