/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "SHKSharerDelegate-Protocol.h"

@class NSString, NSThread, SHKItem, SHKSharer;

@interface SHKOfflineSharer : _AVAudioSessionCategoryPlayback <SHKSharerDelegate>
{
    SHKItem *item;
    NSString *sharerId;
    NSString *uid;
    BOOL readyToFinish;
    NSThread *runLoopThread;
    SHKSharer *sharer;
}

- (void)setSharer:(id)fp8;
- (id)sharer;
- (void)setRunLoopThread:(id)fp8;
- (id)runLoopThread;
- (void)setReadyToFinish:(BOOL)fp8;
- (BOOL)readyToFinish;
- (void)setUid:(id)fp8;
- (id)uid;
- (void)setSharerId:(id)fp8;
- (id)sharerId;
- (void)setItem:(id)fp8;
- (id)item;
- (void)sharerAuthDidFinish:(id)fp8 success:(BOOL)fp12;
- (void)sharerCancelledSending:(id)fp8;
- (void)sharer:(id)fp8 failedWithError:(id)fp12 shouldRelogin:(BOOL)fp16;
- (void)sharerFinishedSending:(id)fp8;
- (void)sharerStartedSending:(id)fp8;
- (void)lastSpin;
- (void)finish;
- (BOOL)shouldRun;
- (void)share;
- (void)main;
- (id)initWithItem:(id)fp8 forSharer:(id)fp12 uid:(id)fp16;
- (void)dealloc;

@end

