/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "SHKSharerDelegate-Protocol.h"

@class NSError, SHKFormController, SHKItem, SHKRequest;

@interface SHKSharer : _AVAudioSessionCategoryPlayback <SHKSharerDelegate>
{
    id shareDelegate;
    SHKItem *item;
    SHKFormController *pendingForm;
    SHKRequest *request;
    NSError *lastError;
    BOOL quiet;
    int pendingAction;
    BOOL isRetainingSelf;
}

+ (BOOL)isServiceAuthorized;
+ (void)logout;
+ (id)authorizationFormCaption;
+ (id)authorizationFormFields;
+ (id)getUserInfo;
+ (id)shareFile:(id)fp8 filename:(id)fp12 mimeType:(id)fp16 title:(id)fp20;
+ (id)shareText:(id)fp8;
+ (id)shareImage:(id)fp8 title:(id)fp12;
+ (id)shareURL:(id)fp8 title:(id)fp12;
+ (id)shareURL:(id)fp8;
+ (id)shareItem:(id)fp8;
+ (BOOL)canShare;
+ (BOOL)canAutoShare;
+ (BOOL)canShareType:(int)fp8;
+ (BOOL)requiresAuthentication;
+ (BOOL)canShareOffline;
+ (BOOL)shareRequiresInternetConnection;
+ (BOOL)canGetUserInfo;
+ (BOOL)canShareFile;
+ (BOOL)canShareImage;
+ (BOOL)canShareURL;
+ (BOOL)canShareText;
+ (id)sharerId;
+ (id)sharerTitle;
- (void)setPendingAction:(int)fp8;
- (int)pendingAction;
- (void)setQuiet:(BOOL)fp8;
- (BOOL)quiet;
- (void)setLastError:(id)fp8;
- (id)lastError;
- (void)setRequest:(id)fp8;
- (id)request;
- (void)setPendingForm:(id)fp8;
- (id)pendingForm;
- (void)setItem:(id)fp8;
- (id)item;
- (void)setIsRetainingSelf:(BOOL)fp8;
- (BOOL)isRetainingSelf;
- (void)setShareDelegate:(id)fp8;
- (id)shareDelegate;
- (void)authDidFinish:(BOOL)fp8;
- (void)sendDidCancel;
- (void)sendDidFailWithError:(id)fp8 shouldRelogin:(BOOL)fp12;
- (void)sendDidFailWithError:(id)fp8;
- (void)sendDidFailShouldRelogin;
- (void)sendDidFinish;
- (void)sendDidStart;
- (void)viewDidDisappear:(BOOL)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)tryPendingAction;
- (void)sharerAuthDidFinish:(id)fp8 success:(BOOL)fp12;
- (void)sharerCancelledSending:(id)fp8;
- (void)sharer:(id)fp8 failedWithError:(id)fp12 shouldRelogin:(BOOL)fp16;
- (void)sharerFinishedSending:(id)fp8;
- (void)sharerStartedSending:(id)fp8;
- (BOOL)send;
- (BOOL)tryToSend;
- (BOOL)validateItem;
- (void)shareFormCancel:(id)fp8;
- (void)shareFormSave:(id)fp8;
- (void)shareFormValidate:(id)fp8;
- (id)shareFormFieldsForType:(int)fp8;
- (void)show;
- (id)authorizationFormCaption;
- (id)authorizationFormFields;
- (void)authorizationFormCancel:(id)fp8;
- (void)authorizationFormSave:(id)fp8;
- (void)authorizationFormValidate:(id)fp8;
- (void)authorizationFormShow;
- (void)setShouldAutoShare:(BOOL)fp8;
- (id)getAuthValueForKey:(id)fp8;
- (void)promptAuthorization;
- (BOOL)authorize;
- (BOOL)isAuthorized;
- (void)share;
- (void)loadItem:(id)fp8;
- (id)init;
- (BOOL)shouldAutoShare;
- (id)sharerId;
- (id)sharerTitle;
- (void)dealloc;

@end

