/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SHKFormControllerLargeTextField.h"

@class UILabel;

@interface SHKTwitterForm : SHKFormControllerLargeTextField
{
    UILabel *counter;
    BOOL hasAttachment;
}

- (void)setHasAttachment:(BOOL)fp8;
- (BOOL)hasAttachment;
- (void)setCounter:(id)fp8;
- (id)counter;
- (void)save;
- (void)textViewDidEndEditing:(id)fp8;
- (void)textViewDidChange:(id)fp8;
- (void)textViewDidBeginEditing:(id)fp8;
- (void)layoutCounter;
- (void)updateCounter;
- (void)keyboardWillShow:(id)fp8;
- (void)dealloc;

@end

