/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface TBXML : _AVAudioSessionCategoryPlayback
{
    struct _TBXMLElement *rootXMLElement;
    struct _TBXMLElementBuffer *currentElementBuffer;
    struct _TBXMLAttributeBuffer *currentAttributeBuffer;
    long currentElement;
    long currentAttribute;
    char *bytes;
    long bytesLength;
}

+ (id)tbxmlWithXMLFile:(id)fp8 fileExtension:(id)fp12 error:(id *)fp16;
+ (id)tbxmlWithXMLFile:(id)fp8 fileExtension:(id)fp12;
+ (id)tbxmlWithXMLFile:(id)fp8 error:(id *)fp12;
+ (id)tbxmlWithXMLFile:(id)fp8;
+ (id)tbxmlWithXMLData:(id)fp8 error:(id *)fp12;
+ (id)tbxmlWithXMLData:(id)fp8;
+ (id)tbxmlWithXMLString:(id)fp8 error:(id *)fp12;
+ (id)tbxmlWithXMLString:(id)fp8;
- (struct _TBXMLElement *)rootXMLElement;
- (void)decodeData:(id)fp8 withError:(id *)fp12;
- (void)decodeData:(id)fp8;
- (id)initWithXMLFile:(id)fp8 fileExtension:(id)fp12 error:(id *)fp16;
- (id)initWithXMLFile:(id)fp8 fileExtension:(id)fp12;
- (id)initWithXMLFile:(id)fp8 error:(id *)fp12;
- (id)initWithXMLFile:(id)fp8;
- (id)initWithXMLData:(id)fp8 error:(id *)fp12;
- (id)initWithXMLData:(id)fp8;
- (id)initWithXMLString:(id)fp8 error:(id *)fp12;
- (id)initWithXMLString:(id)fp8;
- (id)init;

@end

