/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TBXML.h"

@interface TBXML (StaticFunctions)
+ (void)iterateAttributesOfElement:(struct _TBXMLElement *)fp8 withBlock:(id)fp(null);
+ (void)iterateElementsForQuery:(id)fp8 fromElement:(struct _TBXMLElement *)fp12 withBlock:(id)fp(null);
+ (struct _TBXMLElement *)nextSiblingNamed:(id)fp8 searchFromElement:(struct _TBXMLElement *)fp12 error:(id *)fp16;
+ (struct _TBXMLElement *)nextSiblingNamed:(id)fp8 searchFromElement:(struct _TBXMLElement *)fp12;
+ (struct _TBXMLElement *)childElementNamed:(id)fp8 parentElement:(struct _TBXMLElement *)fp12 error:(id *)fp16;
+ (struct _TBXMLElement *)childElementNamed:(id)fp8 parentElement:(struct _TBXMLElement *)fp12;
+ (id)valueOfAttributeNamed:(id)fp8 forElement:(struct _TBXMLElement *)fp12 error:(id *)fp16;
+ (id)valueOfAttributeNamed:(id)fp8 forElement:(struct _TBXMLElement *)fp12;
+ (id)textForElement:(struct _TBXMLElement *)fp8 error:(id *)fp12;
+ (id)textForElement:(struct _TBXMLElement *)fp8;
+ (id)attributeValue:(struct _TBXMLAttribute *)fp8 error:(id *)fp12;
+ (id)attributeValue:(struct _TBXMLAttribute *)fp8;
+ (id)attributeName:(struct _TBXMLAttribute *)fp8 error:(id *)fp12;
+ (id)attributeName:(struct _TBXMLAttribute *)fp8;
+ (id)elementName:(struct _TBXMLElement *)fp8 error:(id *)fp12;
+ (id)elementName:(struct _TBXMLElement *)fp8;
@end

