/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TBXML.h"

@interface TBXML (TBXML_HTTP)
+ (id)tbxmlWithURL:(id)fp8 success:(id)fp(null) failure:(void)fp12;
- (id)initWithURL:(id)fp8 success:(id)fp(null) failure:(void)fp12;
@end

