/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton, UIImageView;

@interface YTAccountFooterView_iPhone : _AVAudioSessionCategoryPlayback
{
    UIImageView *backgroundView_;
    UIButton *signOutButton_;
}

- (id)signOutButton;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8;

@end

