/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton, UITableView, YTTopShadowView;

@interface YTAccountView_iPhone : _AVAudioSessionCategoryPlayback
{
    YTTopShadowView *containerView_;
    UITableView *accountSectionsView_;
    UIButton *signOutButton_;
}

- (id)signOutButton;
- (id)accountSectionsView;
- (id)channelHeaderView;
- (void)layoutSubviews;
- (void)setThumbnail:(id)fp8;
- (void)setUserProfile:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8;

@end

