/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton, UILabel, YTPlayerControlsView;

@interface YTAdView : _AVAudioSessionCategoryPlayback
{
    UIButton *skipButton_;
    UIButton *learnMoreButton_;
    UIButton *titleButton_;
    UILabel *skipLabel_;
    UILabel *learnMoreLabel_;
    UILabel *titleLabel_;
    YTPlayerControlsView *controlsView_;
    int playerViewLayout_;
}

- (id)controlsView;
- (id)learnMoreLabel;
- (id)titleLabel;
- (id)skipLabel;
- (id)learnMoreButton;
- (id)titleButton;
- (id)skipButton;
- (void)setAdTitle:(id)fp8 totalTime:(double)fp12 mediaTime:(double)fp20 playerViewLayout:(int)fp28;
- (void)setSkipAdButtonTitleWithSeconds:(int)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)init;
- (id)initWithResourceLoader:(id)fp8;

@end

