/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseService.h"

@class YTAdsService, YTVASTAd;

@interface YTAdTrackingService : YTBaseService
{
    YTVASTAd *ad_;
    YTAdsService *adsService_;
    BOOL pingedImpression_;
    BOOL pingedEngagedView_;
    int nextQuartile_;
}

- (void)ping:(id)fp8;
- (void)adDidClickthrough;
- (void)adDidClickVideoTitle;
- (void)adDidSkip;
- (void)adDidShowSkip;
- (void)adDidClose;
- (void)adDidComplete;
- (void)adDidPause;
- (void)adDidPlay;
- (void)adDidProgressWithMediaTime:(double)fp8 totalTime:(double)fp16;
- (void)adDidImpression;
- (void)dealloc;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12;
- (id)initWithAd:(id)fp8 operationQueue:(id)fp12 HTTPFetcherService:(id)fp16 adsService:(id)fp20;

@end

