/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIAlertViewDelegate-Protocol.h"

@class UIAlertView, YTVideo;

@interface YTAdultFlow : _AVAudioSessionCategoryPlayback <UIAlertViewDelegate>
{
    SEL confirmAction_;
    id confirmTarget_;
    YTVideo *video_;
    id <YTServices> services_;
    id <YTNavigation> navigation_;
    UIAlertView *loginAlert_;
    UIAlertView *confirmAlert_;
}

- (id)confirmAlert;
- (id)loginAlert;
- (void)done;
- (void)checkConfirmation;
- (void)checkAge;
- (void)checkAuthenticated;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)verify;
- (void)setConfirmTarget:(id)fp8 confirmAction:(SEL)fp12;
- (void)dealloc;
- (id)initWithVideo:(id)fp8 navigation:(id)fp12 services:(id)fp16;

@end

