/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIView<YTArtistViewProtocol>, YTMusicVideoTableController, YTRelatedArtistTableController;

@interface YTArtistController : _AVAudioSessionCategoryPlayback
{
    UIView<YTArtistViewProtocol> *view_;
    Class trackCellClass_;
    Class artistCellClass_;
    id <YTNavigation> navigation_;
    id <YTServices> services_;
    YTMusicVideoTableController *musicVideoTableController_;
    YTRelatedArtistTableController *relatedArtistTableController_;
}

- (void)showWatchWithVideoID:(id)fp8 fromView:(id)fp12;
- (void)loadWithArtistBundle:(id)fp8;
- (void)dealloc;
- (id)initWithArtistView:(id)fp8 trackCellClass:(Class)fp12 artistCellClass:(Class)fp16 services:(id)fp20 navigation:(id)fp24;

@end

