/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTArtistViewProtocol-Protocol.h"

@class UITableView, YTArtistBioView_iPhone;

@interface YTArtistView_iPhone : _AVAudioSessionCategoryPlayback <YTArtistViewProtocol>
{
    YTArtistBioView_iPhone *artistBioView_;
    UITableView *musicVideosTable_;
    UITableView *relatedArtistsTable_;
}

- (id)relatedArtistsTable;
- (id)musicVideosTable;
- (void)setArtist:(id)fp8;
- (id)initWithResourceLoader:(id)fp8;

@end

