/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTBrowseCellProtocol-Protocol.h"

@class GIPResourceLoader, UIImageView;

@interface YTArtistBrowseCell_iPhone : _AVAudioSessionCategoryPlayback <YTBrowseCellProtocol>
{
    UIImageView *disclosureView_;
    GIPResourceLoader *loader_;
}

+ (float)cellHeight;
- (void)setText:(id)fp8 secondaryText:(id)fp12;
- (void)setHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12 showSeparator:(BOOL)fp16;

@end

