/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface YTAttributedTextLabel : _AVAudioSessionCategoryPlayback
{
    struct __CFAttributedString *attributedString_;
    struct CGSize cachedConstraintResult_;
    struct CGSize cachedConstraint_;
}

+ (id)attributesWithFont:(id)fp8 color:(id)fp12 paragraphSpacingBefore:(float)fp16 textAlignment:(unsigned char)fp20;
+ (id)attributesWithFont:(id)fp8 color:(id)fp12 paragraphSpacingBefore:(float)fp16;
- (id)text;
- (struct CGSize)sizeConstrainedToSize:(struct CGSize)fp8;
- (void)appendTextWithFont:(id)fp8 color:(id)fp12 paragraphSpacingBefore:(float)fp16 format:(id)fp20;
- (void)appendTextWithFont:(id)fp8 color:(id)fp12 format:(id)fp16;
- (void)appendText:(id)fp8 withAttributes:(id)fp12;
- (void)clearText;
- (id)accessibilityLabel;
- (void)drawRect:(struct CGRect)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 shadowColor:(id)fp24 shadowOffset:(float)fp28;
- (id)initWithFrame:(struct CGRect)fp8;

@end

