/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTVideoCellProtocol-Protocol.h"

@class GIPResourceLoader, UILabel, YTBadge;

@interface YTBaseVideoCell_iPhone : _AVAudioSessionCategoryPlayback <YTVideoCellProtocol>
{
    UILabel *titleLabel_;
    UILabel *uploaderLabel_;
    UILabel *unplayableVideoLabel_;
    UILabel *viewsLabel_;
    YTBadge *durationBadge_;
    GIPResourceLoader *loader_;
}

+ (float)cellHeight;
+ (struct CGSize)thumbnailSizeForEntry:(id)fp8;
- (void)setEntry:(id)fp8;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

