/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTBrowseCellProtocol-Protocol.h"

@interface YTBrowseCell_iPhone : _AVAudioSessionCategoryPlayback <YTBrowseCellProtocol>
{
}

+ (float)cellHeight;
- (void)setText:(id)fp8 secondaryText:(id)fp12;
- (void)layoutSubviews;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

