/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDate;

@interface YTCacheValueWrapper : _AVAudioSessionCategoryPlayback
{
    id value_;
    NSDate *timestamp_;
}

+ (id)wrapperWithValue:(id)fp8;
- (void)setTimestamp:(id)fp8;
- (id)timestamp;
- (void)setValue:(id)fp8;
- (id)value;
- (void)dealloc;

@end

