/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTSubscribableChannelCellProtocol-Protocol.h"

@class UIControl<YTSubscribeSwitchProtocol>, UIImageView, UILabel, YTImageView;

@interface YTChannelCell_iPhone : _AVAudioSessionCategoryPlayback <YTSubscribableChannelCellProtocol>
{
    UIImageView *cellBackgroundView_;
    YTImageView *thumbnailImageView_;
    UIImageView *thumbnailMaskView_;
    UILabel *titleLabel_;
    UILabel *videosCountLabel_;
    UILabel *subscribersCountLabel_;
    UIControl<YTSubscribeSwitchProtocol> *subscribeSwitch_;
    BOOL layoutChanged_;
}

+ (struct CGSize)thumbnailSizeForEntry:(id)fp8;
+ (float)cellHeight;
- (void)setEntry:(id)fp8;
- (id)subscribeSwitch;
- (void)setThumbnail:(id)fp8 animated:(BOOL)fp12;
- (void)enableSubscribeSwitchWithResourceLoader:(id)fp8;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)fp8;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

