/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTChannelHeaderViewProtocol-Protocol.h"

@class UIImageView, UILabel, UIView, YTImageView, YTSubscribeSwitch;

@interface YTChannelHeaderView_iPhone : _AVAudioSessionCategoryPlayback <YTChannelHeaderViewProtocol>
{
    UIImageView *backgroundImageView_;
    YTImageView *thumbnailImageView_;
    UIImageView *thumbnailMaskView_;
    UIView *labelContainer_;
    UILabel *titleLabel_;
    UILabel *subscribersCountLabel_;
    YTSubscribeSwitch *subscribeSwitch_;
}

+ (float)preferredHeight;
- (void)setDisplayname:(id)fp8 subscribersCount:(unsigned long long)fp12;
- (id)subscribeSwitch;
- (void)resetThumbnailToPlaceholder;
- (void)setThumbnail:(id)fp8 animated:(BOOL)fp12;
- (void)setChannel:(id)fp8;
- (void)setDisplayName:(id)fp8;
- (void)setUserProfile:(id)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8 createSubscribeSwitch:(BOOL)fp12;

@end

