/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIView<YTChannelHeaderViewProtocol>, UIView<YTChannelViewProtocol>, YTEventsFeedController, YTPlaylistsFeedController, YTSubscribeSwitchController, YTVideosFeedController;

@interface YTChannelController : _AVAudioSessionCategoryPlayback
{
    UIView<YTChannelViewProtocol> *channelView_;
    UIView<YTChannelHeaderViewProtocol> *headerView_;
    id <YTServices> services_;
    id <YTNavigation> navigation_;
    YTPlaylistsFeedController *playlistsController_;
    YTEventsFeedController *activitiesFeedController_;
    YTVideosFeedController *uploadsFeedController_;
    YTSubscribeSwitchController *subscribeSwitchController_;
}

- (void)didSelectEvent:(id)fp8 source:(int)fp12 fromView:(id)fp16;
- (void)loadPlaylistsWithChannelID:(id)fp8;
- (void)loadUploadsWithChannelID:(id)fp8;
- (void)loadEventsWithChannelID:(id)fp8;
- (void)loadHeaderWithChannel:(id)fp8;
- (void)dealloc;
- (id)initWithChannelView:(id)fp8 headerView:(id)fp12 services:(id)fp16 navigation:(id)fp20;

@end

