/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTFeedViewCellProtocol-Protocol.h"

@class UILabel, UIView;

@interface YTCommentCell_iPhone : _AVAudioSessionCategoryPlayback <YTFeedViewCellProtocol>
{
    UIView *titleView_;
    UILabel *authorLabel_;
    UILabel *ageLabel_;
    UILabel *contentLabel_;
    BOOL layoutChanged_;
}

+ (struct CGSize)contentSize:(id)fp8 width:(float)fp12 font:(id)fp16;
+ (float)cellHeightForEntry:(id)fp8 width:(float)fp12;
- (void)setEntry:(id)fp8;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

