/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSString;

@interface YTComment : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *title_;
    NSString *content_;
    NSString *authorDisplayName_;
    NSDate *publishedDate_;
}

- (id)publishedDate;
- (id)authorDisplayName;
- (id)content;
- (id)title;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithTitle:(id)fp8 content:(id)fp12 authorDisplayName:(id)fp16 publishedDate:(id)fp20;

@end

