/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class UIPanGestureRecognizer, UIView;

@interface YTConveyorView : _AVAudioSessionCategoryPlayback <UIGestureRecognizerDelegate>
{
    UIView *contentView_;
    UIPanGestureRecognizer *panRecognizer_;
    id <YTConveyorViewDelegate> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (float)contentOriginXToMakeViewVisible:(id)fp8;
- (id)viewsVisibleWithContentOriginX:(float)fp8;
- (BOOL)isViewVisible:(id)fp8 withContentOriginX:(float)fp12;
- (void)updateFrameOfView:(id)fp8;
- (float)closestSnapContentViewOriginX:(float)fp8;
- (float)originXForViewAtIndex:(unsigned int)fp8;
- (void)setContentViewOriginX:(float)fp8 animated:(BOOL)fp12 appearingView:(id)fp16 completion:(id)fp(null);
- (void)setContentViewOriginX:(float)fp8 animated:(BOOL)fp12;
- (void)updateContentViewSize;
- (void)handlePanFrom:(id)fp8;
- (void)layoutSubviews;
- (void)popView:(id)fp8;
- (void)pushView:(id)fp8 animated:(BOOL)fp12 completion:(id)fp(null);
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

