/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIPopoverControllerDelegate-Protocol.h"

@class NSString, UIPopoverController;

@interface YTCreatePlaylistPopoverController : _AVAudioSessionCategoryPlayback <UIPopoverControllerDelegate>
{
    UIPopoverController *popoverController_;
    id doneTarget_;
    SEL doneAction_;
    NSString *playlistTitle_;
    BOOL isPlaylistPrivate_;
}

- (void)didCreatePlaylistWithTitle:(id)fp8 isPrivate:(id)fp12;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)showPopoverFromView:(id)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithNavigation:(id)fp8 resourceLoader:(id)fp12 doneTarget:(id)fp16 doneAction:(SEL)fp20;

@end

