/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSData, NSString;

@interface YTDeviceAuth : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSString *deviceId_;
    NSData *deviceKey_;
}

+ (id)signatureForRequestPathQuery:(id)fp8 decryptedKey:(id)fp12;
- (id)getXGDataDeviceHeaderValue:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (id)initWithDeviceId:(id)fp8 deviceKey:(id)fp12;

@end

