/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray, NSString, NSUserDefaults, YTDeviceAuth;

@interface YTDeviceAuthorizer : _AVAudioSessionCategoryPlayback
{
    NSMutableArray *requestQueue_;
    NSString *developerKey_;
    YTDeviceAuth *deviceAuth_;
    NSString *secret_;
    NSUserDefaults *storage_;
    NSString *uniqueInstallationID_;
}

+ (id)decryptDeviceKey:(id)fp8 secret:(id)fp12;
- (void)saveRegistrationToStorage;
- (void)loadRegistrationFromStorage;
- (id)parseRegistrationResponse:(id)fp8 error:(id *)fp12;
- (void)enqueueSignURLRequest:(id)fp8 completionBlock:(id)fp(null);
- (void)performRequestQueueWithError:(id)fp8;
- (void)performQueuedRequest:(id)fp8;
- (void)beginDeviceRegistration;
- (id)fetcherWithRequest:(id)fp8;
- (void)signURLRequest:(id)fp8 completionBlock:(id)fp(null);
- (void)dealloc;
- (id)init;
- (id)initWithUniqueInstallationID:(id)fp8;
- (id)initWithDeveloperKey:(id)fp8 uniqueInstallationID:(id)fp12 secret:(id)fp16 storage:(id)fp20;

@end

