/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GTMOAuth2Authentication, NSString, NSURL;

@interface YTDRMStreamConverter : _AVAudioSessionCategoryPlayback
{
    NSURL *URL_;
    NSString *videoID_;
    GTMOAuth2Authentication *auth_;
    NSURL *decryptedURL_;
}

- (id)decryptedVideoStreamURL;
- (id)decryptedURL;
- (void)restart;
- (void)stop;
- (void)start;
- (void)dealloc;
- (id)initWithEncryptedURL:(id)fp8 videoID:(id)fp12 auth:(id)fp16;

@end

