/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSString, NSURL, YTVideo;

@interface YTEvent : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *authorDisplayName_;
    NSString *authorUserID_;
    int action_;
    NSString *target_;
    NSDate *when_;
    YTVideo *video_;
    NSString *groupID_;
    NSURL *feedURL_;
}

- (id)feedURL;
- (id)groupID;
- (id)video;
- (id)when;
- (id)target;
- (int)action;
- (id)authorUserID;
- (id)authorDisplayName;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithAuthorDisplayName:(id)fp8 authorUserID:(id)fp12 action:(int)fp16 target:(id)fp20 when:(id)fp24 video:(id)fp28 groupID:(id)fp32 feedURL:(id)fp36;

@end

