/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPPullRefreshDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "YTFeedViewProtocol-Protocol.h"

@class GIPResourceLoader, UIControl<YTStatusViewProtocol>, YTPullRefreshHeader;

@interface YTFeedTableView : _AVAudioSessionCategoryPlayback <GIPPullRefreshDelegate, YTFeedViewProtocol, UITableViewDelegate, UITableViewDataSource>
{
    Class cellClass_;
    BOOL variableCellHeight_;
    UIControl<YTStatusViewProtocol> *statusView_;
    GIPResourceLoader *resourceLoader_;
    YTPullRefreshHeader *pullRefreshHeader_;
    id <YTFeedViewDelegate> feedViewDelegate_;
    BOOL autoFill_;
}

- (void)didSelectStatusView;
- (void)refreshStatus;
- (BOOL)respondsToSelector:(SEL)fp8;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (struct CGSize)thumbnailSizeForEntry:(id)fp8;
- (void)showError:(id)fp8 onRefresh:(BOOL)fp12;
- (void)showLoading;
- (void)layoutSubviews;
- (void)reload;
- (void)deleteCellsAtIndices:(id)fp8;
- (void)insertCellsAtIndices:(id)fp8;
- (id)cellAtIndex:(int)fp8;
- (void)setFeedViewDelegate:(id)fp8;
- (void)pullToRefreshDidFire:(id)fp8;
- (void)dealloc;
- (id)pullRefreshHeader;
- (id)initWithCellClass:(Class)fp8 resourceLoader:(id)fp12 emptyMessage:(id)fp16;
- (id)initWithCellClass:(Class)fp8 resourceLoader:(id)fp12 emptyMessage:(id)fp16 pullRefreshStyle:(int)fp20;
- (id)initWithCellClass:(Class)fp8 statusView:(id)fp12 resourceLoader:(id)fp16;
- (id)initWithCellClass:(Class)fp8 statusView:(id)fp12 resourceLoader:(id)fp16 pullRefreshStyle:(int)fp20;

@end

