/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTFeedViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, UIView<YTFeedViewProtocol>, YTGDataRequest;

@interface YTFeedController : _AVAudioSessionCategoryPlayback <YTFeedViewDelegate>
{
    UIView<YTFeedViewProtocol> *feedView_;
    id <YTServices> services_;
    SEL didSelectEntryAction_;
    id didSelectEntryTarget_;
    BOOL requestInProgress_;
    BOOL refreshInProgress_;
    SEL serviceSelector_;
    SEL refreshServiceSelector_;
    YTGDataRequest *nextRequest_;
    SEL extraServiceSelector_;
    YTGDataRequest *extraRequest_;
    NSMutableArray *entries_;
    NSMutableSet *uniqueEntries_;
    NSMutableDictionary *thumbnails_;
    NSMutableDictionary *selectedThumbnails_;
    NSMutableDictionary *indices_;
    YTGDataRequest *refreshRequest_;
    YTGDataRequest *refreshExtraRequest_;
}

- (void)setRefreshExtraRequest:(id)fp8;
- (id)refreshExtraRequest;
- (void)setRefreshRequest:(id)fp8;
- (id)refreshRequest;
- (void)setExtraRequest:(id)fp8;
- (id)extraRequest;
- (void)setNextRequest:(id)fp8;
- (id)nextRequest;
- (void)onError:(id)fp8;
- (void)onResponse:(id)fp8;
- (void)maybeMakeNextRequest;
- (void)feedViewDidAskForRefresh:(id)fp8;
- (void)feedViewDidAskForMore:(id)fp8;
- (void)feedView:(id)fp8 didSelectEntryAtIndex:(int)fp12;
- (void)updateCell:(id)fp8 atIndex:(int)fp12;
- (id)entryAtIndex:(int)fp8;
- (int)entryCount;
- (void)clear;
- (void)refresh;
- (void)updateCell:(id)fp8 forEntry:(id)fp12 animated:(BOOL)fp16;
- (void)handleEntries:(id)fp8;
- (void)makeThumbnailRequestWithURL:(id)fp8 forEntry:(id)fp12;
- (void)removeEntriesMatchingBlock:(id)fp(null);
- (void)insertEntry:(id)fp8 atIndex:(unsigned int)fp12;
- (void)addEntry:(id)fp8;
- (void)insertEntriesFromArray:(id)fp8 atIndex:(unsigned int)fp12;
- (void)addEntriesFromArray:(id)fp8;
- (void)updateCellForEntry:(id)fp8 animated:(BOOL)fp12;
- (id)cellForEntry:(id)fp8;
- (id)thumbnailForEntry:(id)fp8;
- (void)setSelectedThumbnail:(id)fp8 forEntry:(id)fp12;
- (void)setThumbnail:(id)fp8 forEntry:(id)fp12;
- (void)setDidSelectEntryTarget:(id)fp8 action:(SEL)fp12;
- (void)makeRequest:(id)fp8 serviceSelector:(SEL)fp12 extraRequest:(id)fp16 extraServiceSelector:(SEL)fp20;
- (void)makeRequest:(id)fp8 serviceSelector:(SEL)fp12;
- (void)setAllowDuplicates:(BOOL)fp8;
- (BOOL)allowDuplicates;
- (void)reset;
- (void)dealloc;
- (id)init;
- (id)initWithFeedView:(id)fp8 services:(id)fp12;

@end

