/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTStatusViewProtocol-Protocol.h"

@class NSString, UIActivityIndicatorView, UIImageView, UILabel;

@interface YTFeedTableStatusView : _AVAudioSessionCategoryPlayback <YTStatusViewProtocol>
{
    UIActivityIndicatorView *indicator_;
    UIImageView *errorImageView_;
    UILabel *label_;
    NSString *emptyMessage_;
    float topMargin_;
    float rightMargin_;
}

- (float)rightMargin;
- (float)topMargin;
- (void)setEmptyMessage:(id)fp8;
- (id)emptyMessage;
- (void)showErrorMessage:(id)fp8;
- (void)showEmpty;
- (void)showLoading;
- (void)setRightMargin:(float)fp8;
- (void)setTopMargin:(float)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8 style:(int)fp12;
- (id)initWithResourceLoader:(id)fp8;

@end

