/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol YTFeedViewProtocol <NSObject>
- (void)showError:(id)fp8 onRefresh:(BOOL)fp12;
- (void)showLoading;
- (void)deleteCellsAtIndices:(id)fp8;
- (void)insertCellsAtIndices:(id)fp8;
- (void)reload;
- (id)cellAtIndex:(int)fp8;
- (void)setFeedViewDelegate:(id)fp8;
@end

