/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIAlertViewDelegate-Protocol.h"

@class NSString, UIAlertView;

@interface YTFlagController : _AVAudioSessionCategoryPlayback <UIAlertViewDelegate>
{
    id <YTNavigation> navigation_;
    id <YTServices> services_;
    UIAlertView *alertView_;
    NSString *videoID_;
}

- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)show;
- (void)dealloc;
- (id)init;
- (id)initWithVideoID:(id)fp8 navigation:(id)fp12 services:(id)fp16;

@end

