/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTContainerViewController.h"

@interface YTFullscreenViewController_iPad : YTContainerViewController
{
    BOOL childControllerFrontmost_;
    float statusBarHeight_;
}

- (void)layoutChildControllerView;
- (id)childController;
- (BOOL)childVisibleInView:(id)fp8;
- (void)moveViewFromFullscreen:(id)fp8 toFrame:(struct CGRect)fp12 inView:(id)fp28;
- (void)showViewFullscreen:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)loadView;
- (id)initWithViewController:(id)fp8;

@end

