/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseService.h"

@class YTBrandingParser, YTCache, YTCategoryParser, YTChannelParser, YTChannelRecommendationParser, YTCommentParser, YTDeviceAuthorizer, YTEventParser, YTListParser, YTPageParser, YTPlaylistParser, YTPurchaseParser, YTSubscriptionParser, YTUserAuthenticator, YTUserProfileParser, YTVideoParser;

@interface YTGDataService : YTBaseService
{
    YTCache *defaultCache_;
    YTCache *commentPageCache_;
    YTCache *videoCache_;
    YTCache *videoPageCache_;
    YTCache *subscriptionCache_;
    YTCache *subscriptionPageCache_;
    YTCache *playlistPageCache_;
    YTCache *eventPageCache_;
    YTUserAuthenticator *userAuthenticator_;
    YTDeviceAuthorizer *deviceAuthorizer_;
    YTBrandingParser *brandingParser_;
    YTCategoryParser *categoryParser_;
    YTCommentParser *commentParser_;
    YTPlaylistParser *playlistParser_;
    YTPurchaseParser *purchaseParser_;
    YTSubscriptionParser *subscriptionParser_;
    YTUserProfileParser *userProfileParser_;
    YTVideoParser *videoParser_;
    YTPageParser *commentPageParser_;
    YTEventParser *eventParser_;
    YTChannelParser *channelParser_;
    YTPageParser *channelPageParser_;
    YTChannelRecommendationParser *channelRecommendationParser_;
    YTPageParser *channelRecommendationPageParser_;
    YTPageParser *eventPageParser_;
    YTPageParser *purchasePageParser_;
    YTPageParser *playlistPageParser_;
    YTPageParser *subscriptionPageParser_;
    YTPageParser *videoPageParser_;
    YTListParser *categoriesListParser_;
}

- (void)authenticationDidChange:(id)fp8;
- (void)evictElementsFromCache:(id)fp8 forRequest:(id)fp12;
- (void)clearSubscriptionDependentCaches;
- (void)cacheSubscriptionsFromSubscriptionPage:(id)fp8;
- (void)cacheVideosFromPurchasePage:(id)fp8;
- (void)cacheVideosFromEventPage:(id)fp8;
- (void)cacheVideosFromVideoPage:(id)fp8;
- (void)makeDELETERequest:(id)fp8 withParser:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makePOSTRequest:(id)fp8 withParser:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeWriteRequest:(id)fp8 method:(id)fp12 parser:(id)fp16 responseBlock:(id)fp(null) errorBlock:(void)fp20;
- (void)makeGETRequest:(id)fp8 withParser:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeGETRequest:(id)fp8 withParser:(id)fp12 cache:(id)fp16 responseBlock:(id)fp(null) errorBlock:(void)fp20;
- (void)makeFlagRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMyPurchasesRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeAddToFavoritesRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeRateVideoRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeBrandingRequestWithChannelID:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeEventsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeAddCommentRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeCommentsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMyUserProfileRequestWithAuth:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeChannelRequestWithID:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMySubscriptionRequestWithChannelID:(id)fp8 authentication:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeMySubscriptionsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeAddToPlaylistRequestWithVideoID:(id)fp8 contentURL:(id)fp12 authentication:(id)fp16 responseBlock:(id)fp(null) errorBlock:(void)fp20;
- (void)makeAddPlaylistRequestWithTitle:(id)fp8 description:(id)fp12 isPrivate:(BOOL)fp16 auth:(id)fp20 responseBlock:(id)fp(null) errorBlock:(void)fp24;
- (void)makeMyPlaylistsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makePlaylistsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makePlaylistRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMyPlaylistVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makePlaylistVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeAddToWatchLaterRequestWithVideoID:(id)fp8 authentication:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeMyWatchLaterVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeClearWatchHistoryRequestWithAuth:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeAddToWatchHistoryRequestWithVideoID:(id)fp8 authentication:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeMyWatchHistoryVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeUnsubscribeRequestWithSubscription:(id)fp8 authentication:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeSubscribeRequestWithChannelID:(id)fp8 authentication:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeMySubscriptionUploadsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMySubscriptionEventsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMyUploadedVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeUploadedVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMyChannelRecommendationsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMyFavoriteVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeFavoriteVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeRelatedVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeChannelsStandardFeedRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeVideosStandardFeedRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeSearchChannelsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeSearchVideosRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeVideoRequestWithVideoID:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeCategoriesRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12 deviceAuthorizer:(id)fp16 userAuthenticator:(id)fp20;

@end

