/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPResourceLoader, UIImageView;

@interface YTGroupedCell : _AVAudioSessionCategoryPlayback
{
    UIImageView *backgroundView_;
    int style_;
    GIPResourceLoader *loader_;
}

- (void)setCheckmarkVisible:(BOOL)fp8;
- (void)setHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setStyleForRow:(int)fp8 rowsInSection:(int)fp12;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)fp8 loader:(id)fp12;

@end

