/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol YTGuideTableViewDelegate <NSObject>
- (BOOL)showSignedInEntries;
- (BOOL)showCategories;
- (unsigned int)categoriesCount;
- (unsigned int)subscriptionsCount;
- (void)didSelectPopular;
- (void)didSelectRiver;
- (void)didSelectSettings;
- (void)didSelectChannelStore;
- (void)didSelectAccount;
- (void)updatePopularCell:(id)fp8;
- (void)updateRiverCell:(id)fp8;
- (void)updateSettingsCell:(id)fp8;
- (void)updateChannelStoreCell:(id)fp8;
- (void)updateAccountCell:(id)fp8;
@end

