/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPPullRefreshDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "YTFeedViewProtocol-Protocol.h"

@class GIPResourceLoader, UIControl<YTStatusViewProtocol>, YTPullRefreshHeader;

@interface YTGuideTableView : _AVAudioSessionCategoryPlayback <YTFeedViewProtocol, GIPPullRefreshDelegate, UITableViewDelegate, UITableViewDataSource>
{
    GIPResourceLoader *resourceLoader_;
    Class cellClass_;
    UIControl<YTStatusViewProtocol> *statusView_;
    YTPullRefreshHeader *pullRefreshHeader_;
    id <YTGuideTableViewDelegate> guideFeedViewDelegate_;
    id <YTFeedViewDelegate> feedViewDelegate_;
    BOOL autoFill_;
}

- (void)didSelectStatusView;
- (void)refreshStatus;
- (int)categoriesSection;
- (BOOL)showSubscriptionsSection;
- (id)indexPathForFeedEntryIndex:(int)fp8;
- (int)feedEntryIndexWithIndexPath:(id)fp8;
- (BOOL)isPopularIndexPath:(id)fp8;
- (BOOL)isRiverIndexPath:(id)fp8;
- (BOOL)isSettingsIndexPath:(id)fp8;
- (BOOL)isChannelStoreIndexPath:(id)fp8;
- (BOOL)isAccountIndexPath:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (struct CGSize)thumbnailSizeForEntry:(id)fp8;
- (void)showError:(id)fp8 onRefresh:(BOOL)fp12;
- (void)showLoading;
- (void)reload;
- (void)deleteCellsAtIndices:(id)fp8;
- (void)insertCellsAtIndices:(id)fp8;
- (id)cellAtIndex:(int)fp8;
- (void)setFeedViewDelegate:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)pullToRefreshDidFire:(id)fp8;
- (id)cellForPopular;
- (id)cellForRiver;
- (id)cellForSettings;
- (id)cellForChannelStore;
- (id)cellForAccount;
- (void)setGuideFeedViewDelegate:(id)fp8;
- (void)layoutSubviews;
- (id)pullRefreshHeader;
- (void)setContentWidth:(float)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 style:(int)fp24;
- (id)initWithCellClass:(Class)fp8 resourceLoader:(id)fp12;

@end

