/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

#import "UINavigationControllerDelegate-Protocol.h"
#import "YTGuideFeedControllerDelegate-Protocol.h"
#import "YTGuideViewDelegate-Protocol.h"

@class UINavigationController, UIView, YTGuideFeedController;

@interface YTGuideViewController_iPhone : YTBaseViewController_iPhone <UINavigationControllerDelegate, YTGuideViewDelegate, YTGuideFeedControllerDelegate>
{
    YTGuideFeedController *guideController_;
    UIView *overlayView_;
    UINavigationController *navigationController_;
}

- (id)navigationController;
- (void)updateScrollsToTop;
- (id)guideView;
- (void)didTapEntry:(id)fp8;
- (void)navigationController:(id)fp8 didShowViewController:(id)fp12 animated:(BOOL)fp16;
- (void)guideViewDidMinimize:(id)fp8;
- (void)guideViewDidMaximize:(id)fp8;
- (void)selectPopular;
- (void)selectRiver;
- (void)hideGuide;
- (void)showGuide;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithServices:(id)fp8 navigation:(id)fp12 overlayView:(id)fp16;

@end

