/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class GIPResourceLoader, UIControl, UIImageView, UIPanGestureRecognizer, UIView, YTGuideTableView;

@interface YTGuideView : _AVAudioSessionCategoryPlayback <UIGestureRecognizerDelegate>
{
    GIPResourceLoader *resourceLoader_;
    UIImageView *backgroundView_;
    UIView *contentView_;
    UIView *overlayView_;
    UIControl *contentViewTouchShield_;
    UIPanGestureRecognizer *panRecognizer_;
    UIView *panContainerView_;
    id <YTGuideViewDelegate> delegate_;
    struct CGPoint panOrigin_;
    YTGuideTableView *guideTableView_;
    BOOL guideVisible_;
}

- (BOOL)guideVisible;
- (id)guideTableView;
- (void)maximizeFromSwipe:(BOOL)fp8;
- (void)minimizeWithBounce:(BOOL)fp8;
- (void)pan:(id)fp8;
- (void)bounceContentViewToMakeGuideVisible:(BOOL)fp8 bounce:(BOOL)fp12;
- (void)orientationDidChange:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)maximize;
- (void)minimize;
- (void)setDelegate:(id)fp8;
- (void)minimizeWithBlock:(id)fp(null);
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8 contentView:(id)fp12 overlayView:(id)fp16;

@end

