/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView, UILabel;

@interface YTGuideSectionHeader : _AVAudioSessionCategoryPlayback
{
    UIImageView *backgroundView_;
    UILabel *textLabel_;
}

- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithText:(id)fp8 resourceLoader:(id)fp12;

@end

