/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTFeedController.h"

#import "YTGuideTableViewDelegate-Protocol.h"

@class UIImage, YTGuideEntry, YTGuideTableView;

@interface YTGuideFeedController : YTFeedController <YTGuideTableViewDelegate>
{
    YTGuideTableView *guideTableView_;
    YTGuideEntry *accountEntry_;
    YTGuideEntry *channelStoreEntry_;
    YTGuideEntry *settingsEntry_;
    YTGuideEntry *riverEntry_;
    YTGuideEntry *popularEntry_;
    int categoriesCount_;
    UIImage *accountThumbnail_;
    id <YTGuideFeedControllerDelegate> delegate_;
    YTGuideEntry *selectedEntry_;
}

- (id)selectedEntry;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)didReceiveSubscriptionChangeNotification:(id)fp8;
- (void)updateViews:(id)fp8;
- (BOOL)showSignedInEntries;
- (BOOL)showCategories;
- (unsigned int)categoriesCount;
- (unsigned int)subscriptionsCount;
- (void)didSelectPopular;
- (void)didSelectRiver;
- (void)didSelectSettings;
- (void)didSelectChannelStore;
- (void)didSelectAccount;
- (void)updatePopularCell:(id)fp8;
- (void)updateRiverCell:(id)fp8;
- (void)updateSettingsCell:(id)fp8;
- (void)updateChannelStoreCell:(id)fp8;
- (void)updateAccountCell:(id)fp8;
- (void)loadAccountThumbnail;
- (void)selectPopularVideosEntry;
- (void)selectRiverEntry;
- (id)cellForEntry:(id)fp8;
- (void)updateCell:(id)fp8 forEntry:(id)fp12 animated:(BOOL)fp16;
- (void)feedView:(id)fp8 didSelectEntryAtIndex:(int)fp12;
- (void)setThumbnail:(id)fp8 forEntry:(id)fp12;
- (void)setSelectedEntry:(id)fp8;
- (void)refresh;
- (void)clear;
- (void)handleEntries:(id)fp8;
- (void)dealloc;
- (id)initWithFeedView:(id)fp8 services:(id)fp12;
- (id)initWithGuideTableView:(id)fp8 services:(id)fp12;

@end

