/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView;

@interface YTImageView : _AVAudioSessionCategoryPlayback
{
    UIImageView *placeholderImageView_;
    UIImageView *imageView_;
    BOOL adjustThumbnails_;
    BOOL cropToFaces_;
}

- (void)setCropToFaces:(BOOL)fp8;
- (void)setAdjustThumbnails:(BOOL)fp8;
- (void)resetToPlaceholder;
- (void)setHighlightedImage:(id)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setContentMode:(int)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)setImage:(id)fp8 animated:(BOOL)fp12;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithPlaceholder:(id)fp8;

@end

