/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseService.h"

@class NSCache;

@interface YTMusicService : YTBaseService
{
    NSCache *musicVideoDataCache_;
    NSCache *artistBundleCache_;
}

- (void)makeArtistDataRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeMusicDataRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)dealloc;
- (id)initWithOperationQueue:(id)fp8;

@end

