/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSArray, NSURL;

@interface YTPage : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSArray *entries_;
    int totalResults_;
    int entriesPerPage_;
    int startIndex_;
    NSURL *nextURL_;
    NSURL *previousURL_;
}

- (id)previousURL;
- (id)nextURL;
- (int)startIndex;
- (int)entriesPerPage;
- (int)totalResults;
- (id)entries;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithEntries:(id)fp8 totalResults:(int)fp12 entriesPerPage:(int)fp16 startIndex:(int)fp20 nextURL:(id)fp24 previousURL:(id)fp28;

@end

