/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPResourceLoader, MPVolumeView, NSTimer, UIButton, UIImage, UILabel, UISlider;

@interface YTPlayerControlsView : _AVAudioSessionCategoryPlayback
{
    UIButton *playPauseButton_;
    UIButton *subtitlesButton_;
    UIButton *fullscreenButton_;
    UIButton *replayButton_;
    MPVolumeView *airPlayView_;
    UILabel *secondsPlayedLabel_;
    UILabel *totalSecondsLabel_;
    UISlider *scrubber_;
    UISlider *playingProgress_;
    UISlider *downloadingProgress_;
    double totalSeconds_;
    double mediaTime_;
    double downloadedSeconds_;
    BOOL airPlayButtonVisible_;
    BOOL portraitMode_;
    BOOL userScrubbing_;
    UIImage *playLandscapeImage_;
    UIImage *playPortraitImage_;
    UIImage *pauseLandscapeImage_;
    UIImage *pausePortraitImage_;
    float buttonWidth_;
    id <YTPlayerControlsViewDelegate> delegate_;
    NSTimer *airplayCheckTimer_;
    GIPResourceLoader *resourceLoader_;
}

- (void)didScrubbingEnd:(id)fp8;
- (void)didScrubbingProgress:(id)fp8;
- (void)didScrubbingStart:(id)fp8;
- (void)didPressReplay:(id)fp8;
- (void)didPressSubtitles:(id)fp8;
- (void)didPressFullscreen:(id)fp8;
- (void)didPressPlayPause:(id)fp8;
- (void)updateAirPlayButtonVisibility;
- (void)setDelegate:(id)fp8;
- (float)preferredHeight;
- (void)setMode:(int)fp8;
- (void)setLayout:(int)fp8;
- (void)setReplayButtonHidden:(BOOL)fp8;
- (void)setSubtitlesButtonEnabled:(BOOL)fp8;
- (void)setSubtitlesButtonHidden:(BOOL)fp8;
- (void)setSubtitlesButtonSelected:(BOOL)fp8;
- (void)updateScrubberAndTime;
- (void)setMediaTime:(double)fp8;
- (void)setDownloadedTime:(double)fp8;
- (void)setTotalTime:(double)fp8;
- (void)showPauseButton;
- (void)showPlayButton;
- (void)layoutSubviews;
- (void)setAirPlayAllowed:(BOOL)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8;

@end

