/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol YTPlayerControlsViewDelegate
- (void)didEndScrubbing;
- (void)didStartScrubbing;
- (void)didPressReplay;
- (void)didPressSmallscreen;
- (void)didPressFullscreen;
- (void)didPressSubtitlesInRect:(struct CGRect)fp8 inView:(id)fp24;
- (void)didSeekToTime:(double)fp8;
- (void)didPressPause;
- (void)didPressPlay;
@end

