/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol YTPlayerDelegate
- (void)playbackDidFailWithError:(id)fp8;
- (void)playbackRenderingDidChangeToView:(id)fp8;
- (void)playbackReadyToDisplay;
- (void)playbackLoadingDidStop;
- (void)playbackLoadingDidStart;
- (void)playbackDidProgress;
- (void)playbackDidPause;
- (void)playbackDidPlay;
- (void)playbackNotReadyToReplay;
- (void)playbackReadyToReplay;
- (void)playbackDidFinish;
@end

