/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSObject<YTPlayerViewDelegate>, NSString, UIActivityIndicatorView, UIImageView, UILabel, UIPinchGestureRecognizer, UITapGestureRecognizer, UIView, YTAdView, YTImageView, YTPlayerControlsView;

@interface YTPlayerView : _AVAudioSessionCategoryPlayback <UIGestureRecognizerDelegate>
{
    UIView *renderingView_;
    UIActivityIndicatorView *spinner_;
    UILabel *subtitlesLabel_;
    UILabel *errorLabel_;
    UIImageView *airPlayActiveImageView_;
    UIImageView *currentFrameImageView_;
    NSObject<YTPlayerViewDelegate> *playerViewDelegate_;
    YTAdView *adView_;
    double skipAdTime_;
    double totalTime_;
    double mediaTime_;
    NSString *adTitle_;
    YTImageView *watermarkImageView_;
    YTPlayerControlsView *playerControlsView_;
    int state_;
    int layout_;
    float lastPinchScale_;
    UIPinchGestureRecognizer *pinchRecognizer_;
    UITapGestureRecognizer *tapRecognizer_;
}

+ (id)styledErrorLabel;
+ (id)styledSubtitlesLabel;
- (void)setSkipAdNow;
- (void)didTap:(id)fp8;
- (void)didPinch:(id)fp8;
- (void)didPressAdTitleButton:(id)fp8;
- (void)didPressAdLearnMoreButton:(id)fp8;
- (void)didPressSkipAd:(id)fp8;
- (void)setWatermark:(id)fp8;
- (void)setReplayButtonHidden:(BOOL)fp8;
- (void)setSubtitlesButtonEnabled:(BOOL)fp8;
- (void)setSubtitlesButtonHidden:(BOOL)fp8;
- (void)setSubtitlesButtonSelected:(BOOL)fp8;
- (void)setMediaTime:(double)fp8;
- (void)setDownloadedTime:(double)fp8;
- (void)setTotalTime:(double)fp8;
- (void)showPauseButton;
- (void)showPlayButton;
- (void)setAirPlayAllowed:(BOOL)fp8;
- (float)controlsAlpha;
- (void)setControlsAlpha:(float)fp8;
- (void)setControlsViewDelegate:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)setViewLayout:(int)fp8;
- (void)setState:(int)fp8;
- (void)setVideoRenderingView:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)setAdTitle:(id)fp8;
- (void)enableSkipAdWithTime:(double)fp8;
- (void)setAirPlayActive:(BOOL)fp8;
- (void)setCurrentFrame:(id)fp8;
- (void)setStateToErrorWithMessage:(id)fp8;
- (void)setSubtitlesText:(id)fp8;
- (BOOL)isSpinnerAnimating;
- (void)setLoading:(BOOL)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8;

@end

