/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UILabel;

@interface YTPlaylistHeaderView_iPad : _AVAudioSessionCategoryPlayback
{
    UILabel *videoCountNumberLabel_;
    UILabel *videoCountTextLabel_;
    UILabel *summaryLabel_;
}

- (float)preferredHeightForWidth:(float)fp8;
- (void)loadWithPlaylist:(id)fp8;
- (void)layoutSubviews;
- (id)initWithResourceLoader:(id)fp8;

@end

