/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseService.h"

@class NSString, YTVideo;

@interface YTPTrackingService : YTBaseService
{
    YTVideo *video_;
    YTVideo *adVideo_;
    NSString *CPN_;
}

- (void)pingWithCPN:(id)fp8 builder:(id)fp12;
- (void)pingWithVideo:(id)fp8 CPN:(id)fp12;
- (void)pingWithAdVideo:(id)fp8 video:(id)fp12 CPN:(id)fp16;
- (void)ping;
- (void)dealloc;
- (id)initWithAdVideo:(id)fp8 video:(id)fp12 CPN:(id)fp16 operationQueue:(id)fp20 HTTPFetcherService:(id)fp24;
- (id)initWithVideo:(id)fp8 CPN:(id)fp12 operationQueue:(id)fp16 HTTPFetcherService:(id)fp20;

@end

