/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSString, YTVideo;

@interface YTPurchase : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *ID_;
    int itemType_;
    YTVideo *video_;
    NSDate *purchaseDate_;
    NSDate *expirationDate_;
    int status_;
    BOOL streamable_;
}

- (BOOL)isStreamable;
- (int)status;
- (id)expirationDate;
- (id)purchaseDate;
- (id)video;
- (int)itemType;
- (id)ID;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithID:(id)fp8 itemType:(int)fp12 video:(id)fp16 purchaseDate:(id)fp20 expirationDate:(id)fp24 status:(int)fp28 streamable:(BOOL)fp32;

@end

