/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIScrollViewDelegate-Protocol.h"

@class GIPPullRefreshView, UIView;

@interface YTPullRefreshHeader : _AVAudioSessionCategoryPlayback <UIScrollViewDelegate>
{
    UIView *headerView_;
    int contentWidth_;
    float pullHeight_;
    GIPPullRefreshView *pullRefresh_;
}

- (id)pullRefresh;
- (BOOL)isLoading;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)setEnabled:(BOOL)fp8;
- (BOOL)enabled;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)setHeaderView:(id)fp8;
- (id)headerView;
- (void)close;
- (void)setPullRefreshDrag:(int)fp8;
- (void)setContentWidth:(float)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8 style:(int)fp12;

@end

