/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class Reachability;

@interface YTReachability : _AVAudioSessionCategoryPlayback
{
    Reachability *wiFiReachability_;
    BOOL onWiFi_;
}

- (BOOL)onWiFi;
- (void)reachabilityChanged:(id)fp8;
- (void)dealloc;
- (id)init;

@end

