/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class GIPResourceLoader, NSArray, UITableView;

@interface YTRelatedArtistTableController : _AVAudioSessionCategoryPlayback <UITableViewDataSource, UITableViewDelegate>
{
    GIPResourceLoader *resourceLoader_;
    int selectedRow_;
    NSArray *relatedArtists_;
    SEL didSelectArtistAction_;
    id didSelectArtistTarget_;
    UITableView *tableView_;
    Class cellClass_;
}

- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)setDidSelectArtistIDTarget:(id)fp8 action:(SEL)fp12;
- (void)dealloc;
- (id)initWithRelatedArtists:(id)fp8 tableView:(id)fp12 cellClass:(Class)fp16 resourceLoader:(id)fp20;

@end

