/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

@class YTEventsFeedController;

@interface YTRiverViewController_iPhone : YTBaseViewController_iPhone
{
    YTEventsFeedController *eventsController_;
}

- (void)didSelectEvent:(id)fp8 source:(int)fp12 fromView:(id)fp16;
- (void)requestFeedWithContent:(int)fp8;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;

@end

