/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol YTServices <NSObject>
- (void)didReceiveMemoryWarning;
- (id)settings;
- (id)reachability;
- (id)resourceLoader;
- (id)userAuthenticator;
- (id)PTrackingServiceWithAdVideo:(id)fp8 video:(id)fp12 CPN:(id)fp16;
- (id)PTrackingServiceWithVideo:(id)fp8 CPN:(id)fp12;
- (id)videoStatsServiceWithSource:(int)fp8;
- (id)subtitlesService;
- (id)suggestService;
- (id)searchHistory;
- (id)musicService;
- (id)imageService;
- (id)gDataService;
- (id)adTrackingServiceForAd:(id)fp8;
- (id)adsService;
@end

