/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPSpeechControllerDelegate-Protocol.h"
#import "YTSearchViewDelegate-Protocol.h"

@class GIPSpeechController, NSArray, UIView<YTSearchViewProtocol>;

@interface YTSearchController : _AVAudioSessionCategoryPlayback <YTSearchViewDelegate, GIPSpeechControllerDelegate>
{
    UIView<YTSearchViewProtocol> *searchView_;
    id <YTServices> services_;
    id <YTNavigation> navigation_;
    GIPSpeechController *speechController_;
    NSArray *suggestions_;
}

- (void)authenticationDidChange:(id)fp8;
- (void)updateSuggestions;
- (void)performSearch:(id)fp8;
- (void)beginRecognition;
- (void)searchSuggestionAddDidPress:(id)fp8;
- (void)searchSuggestionDidPress:(id)fp8;
- (void)voiceSearchButtonDidPress;
- (void)submitQuery:(id)fp8;
- (void)queryDidChange:(id)fp8;
- (void)speechControllerDialogDidDismiss:(id)fp8;
- (void)speechControllerRecognitionDidCancel:(id)fp8;
- (void)speechController:(id)fp8 resultsDidUpdate:(id)fp12 isFinal:(BOOL)fp16;
- (void)viewWillAppear;
- (void)dealloc;
- (id)initWithSearchView:(id)fp8 services:(id)fp12 navigation:(id)fp16;

@end

