/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, UITableView, YTSettingsPickerViewController;

@interface YTSettingsViewController : YTBaseViewController_iPhone <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *tableView_;
    NSArray *sectionNames_;
    YTSettingsPickerViewController *safeSearchPicker_;
    YTSettingsPickerViewController *homeFeedContentPicker_;
}

+ (id)openSourceLicensesURL;
+ (id)privacyPolicyURL;
+ (id)termsOfServiceURL;
+ (id)helpURL;
- (void)dismissModalViewControllerWithAnimation;
- (id)reuseableCellForTableView:(id)fp8;
- (id)youtubeCellForRow:(int)fp8;
- (id)aboutCellForRow:(int)fp8;
- (id)getSafeSearchString:(int)fp8;
- (id)getHomeFeedContentString:(int)fp8;
- (void)showWebViewWithURL:(id)fp8;
- (void)presentModalViewController:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)showSendFeedbackPopup;
- (void)didSelectItemAtIndex:(id)fp8 inPicker:(id)fp12;
- (void)dealloc;
- (id)initWithServices:(id)fp8 navigation:(id)fp12;

@end

