/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray;

@interface YTSearchHistory : _AVAudioSessionCategoryPlayback
{
    NSMutableArray *history_;
}

- (void)authenticationDidChange:(id)fp8;
- (void)userDidSearch:(id)fp8;
- (void)clear;
- (id)history;
- (void)dealloc;
- (id)init;

@end

