/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton, UILabel;

@interface YTSearchSuggestionCell : _AVAudioSessionCategoryPlayback
{
    UIButton *appendButton_;
    UILabel *textLabel_;
}

+ (float)cellHeight;
- (id)appendButton;
- (void)setResult:(id)fp8;
- (void)setHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

