/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton, YTFeedTableView, YTTabsView;

@interface YTSearchResultsView_iPhone : _AVAudioSessionCategoryPlayback
{
    YTTabsView *tabsView_;
    YTFeedTableView *videosFeedView_;
    YTFeedTableView *channelsFeedView_;
    UIButton *refineButton_;
}

- (id)refineButton;
- (id)channelsFeedView;
- (id)videosFeedView;
- (void)setScrollsToTop:(BOOL)fp8;
- (void)layoutSubviews;
- (id)initWithResourceLoader:(id)fp8;

@end

