/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol YTSearchViewProtocol
- (void)setSearchViewDelegate:(id)fp8;
- (id)searchViewDelegate;
- (void)setQuery:(id)fp8;
- (id)query;
- (void)loseFocus;
- (void)gainFocus;
- (void)setEnableVoiceSearch:(BOOL)fp8;
- (void)setSuggestions:(id)fp8;
@end

