/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface YTSettings : _AVAudioSessionCategoryPlayback
{
}

- (void)authenticationDidChange:(id)fp8;
- (void)setSignInPromoDismissed:(BOOL)fp8;
- (BOOL)isSignInPromoDismissed;
- (void)deleteUserSettings;
- (id)uniqueInstallationID;
- (void)setSubtitlesLanguageCode:(id)fp8;
- (id)subtitlesLanguageCode;
- (void)setAdultContentConfirmed:(BOOL)fp8;
- (BOOL)adultContentConfirmed;
- (void)setHomeFeedContent:(int)fp8;
- (int)homeFeedContent;
- (void)setSafeSearch:(int)fp8;
- (int)safeSearch;
- (void)dealloc;
- (id)init;

@end

