/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@interface YTSearchFilters : _AVAudioSessionCategoryPlayback <NSCopying>
{
    int sortBy_;
    int uploadDate_;
    int duration_;
    BOOL CC_;
}

- (void)setCC:(BOOL)fp8;
- (BOOL)hasCC;
- (void)setDuration:(int)fp8;
- (int)duration;
- (void)setUploadDate:(int)fp8;
- (int)uploadDate;
- (void)setSortBy:(int)fp8;
- (int)sortBy;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

