/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "YTSearchViewProtocol-Protocol.h"

@class GIPInputShieldView, GIPResourceLoader, NSArray, UIButton, UIImageView, UITableView, UIView, YTSearchTextField;

@interface YTSearchView_iPhone : _AVAudioSessionCategoryPlayback <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate, YTSearchViewProtocol>
{
    GIPInputShieldView *inputShield_;
    UITableView *suggestionsView_;
    GIPResourceLoader *resourceLoader_;
    NSArray *suggestions_;
    UIView *searchBackgroundView_;
    UIImageView *searchTextFieldBackgroundImageView_;
    YTSearchTextField *searchTextField_;
    UIButton *voiceButton_;
    float searchBarHeight_;
    BOOL hasFocus_;
    id <YTSearchViewDelegate> searchViewDelegate_;
}

- (float)searchBarHeight;
- (void)setSearchViewDelegate:(id)fp8;
- (id)searchViewDelegate;
- (void)editingChanged:(id)fp8;
- (void)editingDidEndOnExit:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)shieldDidReceiveTouch:(id)fp8;
- (void)didPressAppend:(id)fp8;
- (void)didPressVoice:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)loseFocus;
- (void)gainFocus;
- (void)setEnableVoiceSearch:(BOOL)fp8;
- (void)setQuery:(id)fp8;
- (id)query;
- (void)setSuggestions:(id)fp8;
- (void)layoutSuggestionsView;
- (void)setSearchBarHeight:(float)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8;

@end

