/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

@class NSString, UIButton, YTFeedController, YTSearchFilters, YTVideosFeedController;

@interface YTSearchResultsViewController_iPhone : YTBaseViewController_iPhone
{
    NSString *query_;
    YTSearchFilters *searchFilters_;
    YTVideosFeedController *videosFeedController_;
    YTFeedController *channelsFeedController_;
    UIButton *refineButton_;
}

- (void)searchWithFilters:(id)fp8;
- (void)didPressRefineButton;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithServices:(id)fp8 navigation:(id)fp12 query:(id)fp16;

@end

