/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DefaultSHKConfigurator.h"

@interface YTSHKConfigurator : DefaultSHKConfigurator
{
}

- (id)twitterUseXAuth;
- (id)twitterCallbackUrl;
- (id)twitterSecret;
- (id)twitterConsumerKey;
- (id)facebookAppId;
- (id)googlePlusClientSecret;
- (id)googlePlusClientId;
- (id)appURL;
- (id)appName;
- (id)getAppName;

@end

