/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIActionSheetDelegate-Protocol.h"

@class NSMutableArray, YTUserAuthenticator, YTVideo;

@interface YTSharingActionSheet : _AVAudioSessionCategoryPlayback <UIActionSheetDelegate>
{
    NSMutableArray *sharers_;
    YTVideo *video_;
    YTUserAuthenticator *authenticator_;
}

- (void)dismissWithClickedButtonIndex:(int)fp8 animated:(BOOL)fp12;
- (void)showFromRect:(struct CGRect)fp8 inRotatedView:(id)fp24 animated:(BOOL)fp28;
- (void)dealloc;
- (id)initWithVideo:(id)fp8 userAuthenticator:(id)fp12;

@end

