/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView, UIView;

@interface YTStackedView_iPad : _AVAudioSessionCategoryPlayback
{
    UIImageView *borderView_;
    UIView *headerView_;
    UIView *contentView_;
}

+ (float)headerViewHeight;
+ (id)stackedViewWithHeaderView:(id)fp8 contentView:(id)fp12 resourceLoader:(id)fp16;
- (id)contentView;
- (id)headerView;
- (void)setContentView:(id)fp8;
- (void)setHeaderView:(id)fp8;
- (void)layoutSubviews;
- (id)initWithResourceLoader:(id)fp8;

@end

