/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTContainerViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class UIPanGestureRecognizer, UIScrollView;

@interface YTStackViewController : YTContainerViewController <UIGestureRecognizerDelegate>
{
    UIPanGestureRecognizer *panRecognizer_;
    UIScrollView *hitScrollView_;
    float contentOffsetY_;
    id <YTStackViewControllerDelegate> delegate_;
    unsigned int maximumDepth_;
}

- (id)scrollViewContainingTouch:(id)fp8;
- (void)popView:(id)fp8 animated:(BOOL)fp12 completion:(id)fp(null);
- (void)pushView:(id)fp8 isRootView:(BOOL)fp12 animated:(BOOL)fp16 completion:(id)fp(null);
- (id)topView;
- (void)handlePanFrom:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)setDelegate:(id)fp8;
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (void)popViewControllerAnimated:(BOOL)fp8;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)init;
- (id)initWithMaximumDepth:(unsigned int)fp8;

@end

