/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class YTPlayerView, YTVideoActionBarView;

@interface YTStageView : _AVAudioSessionCategoryPlayback
{
    YTVideoActionBarView *actionBarView_;
    YTPlayerView *playerView_;
}

- (id)playerView;
- (id)actionBarView;
- (void)layoutSubviews;
- (id)initWithResourceLoader:(id)fp8;

@end

