/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTSubscribeSwitchProtocol-Protocol.h"

@class NSString, UIActivityIndicatorView, UIImage, UIImageView, UILabel;

@interface YTSubscribeSwitch : _AVAudioSessionCategoryPlayback <YTSubscribeSwitchProtocol>
{
    UIImageView *buttonImageView_;
    UILabel *statusLabel_;
    UIActivityIndicatorView *statusIndicator_;
    NSString *subscribeOffText_;
    NSString *subscribeOnText_;
    NSString *unsubscribeText_;
    UIImage *subscribeOffImage_;
    UIImage *subscribeOnImage_;
    UIImage *unsubscribeImage_;
    int subscribeState_;
}

- (int)subscribeState;
- (void)setHidden:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setSubscribeState:(int)fp8;
- (void)setHidden:(BOOL)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8;

@end

