/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface YTSubtitlesLine : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *text_;
    unsigned int startTime_;
    unsigned int endTime_;
}

- (unsigned int)endTime;
- (unsigned int)startTime;
- (id)text;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithText:(id)fp8 startTime:(unsigned int)fp12 endTime:(unsigned int)fp16;

@end

