/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPPickerDelegate-Protocol.h"
#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"

@class GIPPicker, NSArray, YTPlayerView, YTSubtitles, YTVideo;

@interface YTSubtitlesController : _AVAudioSessionCategoryPlayback <UIPickerViewDelegate, UIPickerViewDataSource, GIPPickerDelegate>
{
    YTVideo *video_;
    YTPlayerView *playerView_;
    GIPPicker *subtitlesTrackPicker_;
    BOOL subtitlesTrackPickerVisible_;
    id <YTServices> services_;
    id <YTNavigation> navigation_;
    id <YTSubtitlesControllerDelegate> delegate_;
    YTSubtitles *subtitles_;
    NSArray *subtitlesTracks_;
}

- (void)setSubtitlesTracks:(id)fp8;
- (id)subtitlesTracks;
- (void)setSubtitles:(id)fp8;
- (id)subtitles;
- (void)subtitlePickerDidClose;
- (void)loadSubtitles:(id)fp8;
- (void)loadUserSubtitles;
- (void)loadSubtitlesTracksWithBlock:(id)fp(null);
- (int)pickerView:(id)fp8 numberOfRowsInComponent:(int)fp12;
- (int)numberOfComponentsInPickerView:(id)fp8;
- (id)pickerView:(id)fp8 titleForRow:(int)fp12 forComponent:(int)fp16;
- (void)pickerDidCancel:(id)fp8;
- (void)picker:(id)fp8 didSelectItemAtIndex:(int)fp12;
- (void)updateSubtitlesPositionWithMediaTime:(double)fp8;
- (void)showSubtitlesPickerFromRect:(struct CGRect)fp8 inView:(id)fp24;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithVideo:(id)fp8 playerView:(id)fp12 services:(id)fp16 navigation:(id)fp20;

@end

