/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "YTTabTitlesViewDelegate-Protocol.h"

@class UIImageView, UIScrollView, YTTabTitlesView;

@interface YTTabsView : _AVAudioSessionCategoryPlayback <UIScrollViewDelegate, YTTabTitlesViewDelegate>
{
    YTTabTitlesView *tabTitlesView_;
    UIScrollView *scrollView_;
    UIImageView *topShadowImageView_;
    BOOL inLayout_;
    BOOL layoutNeeded_;
    BOOL scrollsToTop_;
    id <YTTabsViewDelegate> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)updateScrollsToTop;
- (unsigned int)currentVisibleTabIndex;
- (void)updateTabIndex:(unsigned int)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (void)didTouchTitleAtIndex:(int)fp8;
- (void)setScrollsToTop:(BOOL)fp8;
- (id)currentTabView;
- (id)tabTitlesView;
- (void)addTabView:(id)fp8 withTitle:(id)fp12;
- (void)insertTabView:(id)fp8 withTitle:(id)fp12 atIndex:(int)fp16;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8;

@end

