/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTParser-Protocol.h"

@class NSDateFormatter;

@interface YTTBParser : _AVAudioSessionCategoryPlayback <YTParser>
{
    NSDateFormatter *dateFormatter_;
}

- (id)parseElement:(id)fp8 error:(id *)fp12;
- (id)dateOrNilFromString:(id)fp8 error:(id *)fp12;
- (id)dateFromString:(id)fp8 error:(id *)fp12;
- (id)parse:(id)fp8 error:(id *)fp12;
- (void)dealloc;
- (id)init;

@end

