/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPResourceLoader, UIButton, UILabel, UIView, YTImageView;

@interface YTTitleBar_iPad : _AVAudioSessionCategoryPlayback
{
    UIView *backgroundView_;
    UIButton *button_;
    UILabel *titleLabel_;
    GIPResourceLoader *resourceLoader_;
    YTImageView *thumbnailView_;
}

- (id)thumbnailView;
- (void)setButton:(id)fp8;
- (void)setThumbnail:(id)fp8;
- (void)setTitle:(id)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8;

@end

