/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView, UILabel, UIView;

@interface YTToastView : _AVAudioSessionCategoryPlayback
{
    UIView *background_;
    UIImageView *infoImage_;
    UIImageView *errorImage_;
    UILabel *label_;
}

- (void)setMessage:(id)fp8 isError:(BOOL)fp12;
- (void)setErrorMessage:(id)fp8;
- (void)setMessage:(id)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8 resourceLoader:(id)fp24;

@end

