/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class YTToastView;

@interface YTToastController : _AVAudioSessionCategoryPlayback
{
    YTToastView *toastView_;
}

- (void)adjustOrientation;
- (void)showError:(id)fp8 withMessage:(id)fp12;
- (void)showMessage:(id)fp8;
- (void)dealloc;
- (id)initWithToastView:(id)fp8;

@end

