/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPResourceLoader, UIImageView, UILabel;

@interface YTUpdatesIndicatorView : _AVAudioSessionCategoryPlayback
{
    UIImageView *backgroundView_;
    UILabel *labelView_;
    GIPResourceLoader *loader_;
}

- (void)setText:(id)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)init;
- (id)initWithResourceLoader:(id)fp8;

@end

