/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GTMOAuth2Authentication;

@interface YTUserAuthenticator : _AVAudioSessionCategoryPlayback
{
    GTMOAuth2Authentication *userAuth_;
    id <YTNavigation> navigation_;
}

+ (id)standardGoogleAuthentication;
- (void)unAuthenticate;
- (BOOL)isAuthenticated;
- (id)authentication;
- (void)authenticateWithBlock:(id)fp(null);
- (void)authenticateWithBlock:(id)fp(null) failedBlock:(void)fp8 canceledBlock:(id)fp(null);
- (void)authenticateWithBlock:(id)fp(null) showSignInFromRect:(void)fp8 inView:(struct CGRect)fp12;
- (void)authenticateWithBlock:(id)fp(null) failedBlock:(void)fp8 canceledBlock:(id)fp(null) showSignInFromRect:(void)fp12 inView:(id)fp(null);
- (void)dealloc;
- (void)setNavigation:(id)fp8;
- (id)init;

@end

