/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSString, NSURL;

@interface YTUserProfile : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *username_;
    NSString *displayName_;
    NSURL *uploadsURL_;
    NSURL *playlistsURL_;
    unsigned int age_;
    NSURL *thumbnailURL_;
    unsigned long long uploadedCount_;
    unsigned long long favoritesCount_;
    unsigned long long subscriptionsCount_;
    unsigned long long uploadViewsCount_;
    unsigned long long channelViewsCount_;
    unsigned long long subscribersCount_;
}

- (unsigned long long)subscribersCount;
- (unsigned long long)channelViewsCount;
- (unsigned long long)uploadViewsCount;
- (unsigned long long)subscriptionsCount;
- (unsigned long long)favoritesCount;
- (unsigned long long)uploadedCount;
- (id)thumbnailURL;
- (unsigned int)age;
- (id)playlistsURL;
- (id)uploadsURL;
- (id)displayName;
- (id)username;
- (BOOL)hasLegalAge;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithUsername:(id)fp8 displayName:(id)fp12 age:(unsigned int)fp16 thumbnailURL:(id)fp20 uploadsURL:(id)fp24 playlistsURL:(id)fp28 uploadedCount:(unsigned long long)fp32 favoritesCount:(unsigned long long)fp40 subscriptionsCount:(unsigned long long)fp48 uploadViewsCount:(unsigned long long)fp56 channelViewsCount:(unsigned long long)fp64 subscribersCount:(unsigned long long)fp72;

@end

