/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MobileMusicVideoData, UIImageView, UITableView, YTBranding, YTSubscribeSwitchController, YTVideo, YTVideoInfoCell_iPhone, YTVideoInfoChannelCell_iPhone;

@interface YTVideoInfoTableController_iPhone : _AVAudioSessionCategoryPlayback <UITableViewDataSource, UITableViewDelegate>
{
    id <YTServices> services_;
    id <YTNavigation> navigation_;
    YTVideo *video_;
    YTBranding *branding_;
    MobileMusicVideoData *musicVideoData_;
    YTSubscribeSwitchController *subscribeSwitchController_;
    UITableView *tableView_;
    YTVideoInfoChannelCell_iPhone *channelCell_;
    YTVideoInfoCell_iPhone *videoInfoCell_;
    UIImageView *brandingImageView_;
}

- (void)loadWithChannelID:(id)fp8;
- (void)loadMusicVideoDataForVideo:(id)fp8;
- (int)tableRowFromIndexPath:(id)fp8;
- (id)artistInfoCellWithTableView:(id)fp8;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)setBranding:(id)fp8;
- (void)setVideo:(id)fp8;
- (void)dealloc;
- (id)initWithTableView:(id)fp8 services:(id)fp12 navigation:(id)fp16;

@end

