/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol YTVideoActionBarViewDelegate
- (void)didPressBarButton:(int)fp8 inRect:(struct CGRect)fp12 inView:(id)fp28;
@end

