/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSArray;

@interface YTViewGroup : _AVAudioSessionCategoryPlayback
{
    NSArray *groupViews_;
}

+ (id)groupWithViews:(id)fp8;
- (struct CGRect)boundingBox;
- (void)alignCenterToCenterOfView:(id)fp8;
- (void)alignCenterLeftToCenterRightOfView:(id)fp8 paddingX:(float)fp12;
- (void)dealloc;
- (id)initWithViewArray:(id)fp8;

@end

