/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "YTPlayerControlsVisibilityDelegate-Protocol.h"

@class GIPResourceLoader, NSArray, UIImageView, UILabel;

@interface YTVideoActionBarView : _AVAudioSessionCategoryPlayback <UIActionSheetDelegate, YTPlayerControlsVisibilityDelegate>
{
    GIPResourceLoader *resourceLoader_;
    NSArray *buttons_;
    UIImageView *backgroundImageView_;
    UILabel *titleLabel_;
    float preferredHeight_;
    BOOL fullscreen_;
    id <YTVideoActionBarViewDelegate> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)addButtonsWithIcons:(id)fp8 selectedIcons:(id)fp12 size:(struct CGSize)fp16;
- (void)actionButtonPressed:(id)fp8;
- (void)playerControlsDidDisappearForState:(int)fp8;
- (void)playerControlsDidAppearForState:(int)fp8;
- (void)setBarButton:(int)fp8 selected:(BOOL)fp12;
- (float)preferredHeight;
- (void)setFullscreen:(BOOL)fp8;
- (void)setTitle:(id)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8;

@end

