/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseVideoCell_iPhone.h"

@class UIImageView, YTImageView, YTVideo;

@interface YTVideoCell_iPhone : YTBaseVideoCell_iPhone
{
    YTVideo *video_;
    YTImageView *thumbnailView_;
    UIImageView *metaView_;
}

+ (float)cellHeight;
+ (struct CGSize)thumbnailSizeForEntry:(id)fp8;
- (void)setThumbnail:(id)fp8 animated:(BOOL)fp12;
- (void)setEntry:(id)fp8;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

