/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSURL;

@interface YTVideoPro : _AVAudioSessionCategoryPlayback <NSCopying>
{
    int type_;
    NSURL *posterURL_;
    NSDate *releaseDate_;
    NSDate *availabilityStart_;
    NSDate *availabilityEnd_;
    NSURL *trailersURL_;
}

- (id)trailersURL;
- (id)availabilityEnd;
- (id)availabilityStart;
- (id)releaseDate;
- (id)posterURL;
- (int)type;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithType:(int)fp8 posterURL:(id)fp12 releaseDate:(id)fp16 availabilityStart:(id)fp20 availabilityEnd:(id)fp24 trailersURL:(id)fp28;

@end

