/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "YTVideoActionBarViewDelegate-Protocol.h"

@class UIActionSheet, UIView, YTVideo, YTVideoActionBarView;

@interface YTVideoActionBarController : _AVAudioSessionCategoryPlayback <YTVideoActionBarViewDelegate, UIActionSheetDelegate>
{
    YTVideoActionBarView *view_;
    YTVideo *video_;
    id <YTNavigation> navigation_;
    id <YTServices> services_;
    UIView *fromView_;
    struct CGRect fromRect_;
    UIActionSheet *moreSheet_;
}

- (void)authenticateWithBlock:(id)fp(null);
- (void)addToPlaylist;
- (void)addToFavorites;
- (void)addToWatchLater;
- (void)share;
- (void)flag;
- (void)actionSheet:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)didPressBarButton:(int)fp8 inRect:(struct CGRect)fp12 inView:(id)fp28;
- (void)dealloc;
- (id)init;
- (id)initWithActionBarView:(id)fp8 video:(id)fp12 navigation:(id)fp16 services:(id)fp20;

@end

