/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UITableView, YTAddCommentView, YTFeedTableStatusView, YTFeedTableView, YTTabsView;

@interface YTVideoView_iPhone : _AVAudioSessionCategoryPlayback
{
    YTFeedTableStatusView *commentsStatusView_;
    YTTabsView *tabsView_;
    UITableView *videoInfoView_;
    YTFeedTableView *suggestionsFeedView_;
    YTFeedTableView *commentsFeedView_;
    YTAddCommentView *addCommentView_;
}

- (id)addCommentView;
- (id)commentsFeedView;
- (id)suggestionsFeedView;
- (id)videoInfoView;
- (id)tabsView;
- (void)setCommentsAllowed:(BOOL)fp8;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8;

@end

