/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface YTVideoState : _AVAudioSessionCategoryPlayback <NSCopying>
{
    int code_;
    NSString *reason_;
}

- (id)reason;
- (int)code;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithCode:(int)fp8 reason:(id)fp12;

@end

