/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "YTAddCommentViewDelegate-Protocol.h"
#import "YTPlayerControllerDelegate-Protocol.h"
#import "YTStackViewControllerDelegate-Protocol.h"
#import "YTTabsViewDelegate-Protocol.h"
#import "YTWatchViewDelegate_iPhone-Protocol.h"

@class NSMutableSet, NSString, UIPanGestureRecognizer, YTAdultFlow, YTBranding, YTPlayerController, YTStackViewController, YTVideo, YTVideoActionBarController, YTVideoViewController_iPhone, YTVideoView_iPhone, YTWatchView_iPhone;

@interface YTWatchViewController_iPhone : YTBaseViewController_iPhone <YTPlayerControllerDelegate, YTStackViewControllerDelegate, YTTabsViewDelegate, UIGestureRecognizerDelegate, YTWatchViewDelegate_iPhone, YTAddCommentViewDelegate>
{
    NSString *videoID_;
    int source_;
    YTVideo *video_;
    YTBranding *branding_;
    BOOL viewAppeared_;
    YTWatchView_iPhone *watchView_;
    YTVideoView_iPhone *videoView_;
    YTStackViewController *stackController_;
    YTVideoViewController_iPhone *videoViewController_;
    YTPlayerController *playerController_;
    YTVideoActionBarController *actionBarController_;
    YTAdultFlow *adultFlow_;
    NSMutableSet *portraitRequesters_;
    UIPanGestureRecognizer *verticalPanRecognizer_;
    int lastLayoutOrientation_;
}

- (void)playVideo;
- (void)confirmVideo;
- (void)setBranding:(id)fp8;
- (void)loadVideo;
- (void)layoutViewForOrientation:(int)fp8;
- (void)receivedRotation:(id)fp8;
- (void)animateToInterfaceOrientation:(int)fp8;
- (void)releasePortraitOrientation:(id)fp8;
- (void)requestPortraitOrientation:(id)fp8;
- (void)handlePanWithRecognizer:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)didCommentInputLoseFocus;
- (void)didCommentInputGainFocus;
- (void)didTouchStageShield;
- (void)didChangeToTab:(id)fp8;
- (void)willPushSubviewWithIndex:(unsigned int)fp8;
- (void)willPopSubviewWithIndex:(unsigned int)fp8;
- (void)showVideoPlaybackSmallscreen;
- (void)showVideoPlaybackFullscreen;
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (void)popViewControllerAnimated;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithVideoID:(id)fp8 source:(int)fp12 services:(id)fp16 navigation:(id)fp20;

@end

