/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIControl, UIView, YTStageView;

@interface YTWatchView_iPhone : _AVAudioSessionCategoryPlayback
{
    struct CGRect stageViewFrame_;
    UIControl *stageShield_;
    UIView *stackView_;
    struct CGRect stackViewFrame_;
    float panY_;
    float extraContentHeight_;
    id <YTWatchViewDelegate_iPhone> delegate_;
    int layout_;
    YTStageView *stageView_;
    UIView *guardView_;
}

- (id)guardView;
- (id)stageView;
- (int)layout;
- (void)didTouchStageShield;
- (void)adjustFrames;
- (void)endPanWithOffset:(float)fp8;
- (void)adjustScollViewInsetsFromView:(id)fp8;
- (BOOL)isOffsetNearestTopEdge:(float)fp8;
- (void)panWithOffset:(float)fp8;
- (void)panDown;
- (void)panUp;
- (void)setDelegate:(id)fp8;
- (void)setLayout:(int)fp8;
- (void)layoutSubviews;
- (id)initWithResourceLoader:(id)fp8 stackView:(id)fp12;

@end

