#import <Foundation/Foundation.h>

@interface GTMHTTPFetcher : NSObject
+ (void)setConnectionClass:(Class)fp8;
+ (Class)connectionClass;
+ (BOOL)doesSupportSentDataCallback;
+ (id)staticCookieStorage;
+ (void)initialize;
+ (id)fetcherWithURLString:(id)fp8;
+ (id)fetcherWithURL:(id)fp8;
+ (id)fetcherWithRequest:(id)fp8;
- (void)setShouldFetchInBackground:(BOOL)fp8;
- (BOOL)shouldFetchInBackground;
- (void)setRetryBlock:(id)fp;
- (id)retryBlock;
- (void)setReceivedDataBlock:(id)fp;
- (id)receivedDataBlock;
- (void)setSentDataBlock:(id)fp;
- (id)sentDataBlock;
- (void)setCompletionBlock:(id)fp;
- (id)completionBlock;
- (void)setCookieStorage:(id)fp8;
- (id)cookieStorage;
- (void)setLog:(id)fp8;
- (id)log;
- (void)setComment:(id)fp8;
- (id)comment;
- (void)setRunLoopModes:(id)fp8;
- (id)runLoopModes;
- (void)setDownloadFileHandle:(id)fp8;
- (id)downloadFileHandle;
- (void)setTemporaryDownloadPath:(id)fp8;
- (id)temporaryDownloadPath;
- (void)setDownloadPath:(id)fp8;
- (id)downloadPath;
- (void)setDownloadedData:(id)fp8;
- (id)downloadedData;
- (unsigned long long)downloadedLength;
- (void)setResponse:(id)fp8;
- (id)response;
- (void)setRetryFactor:(double)fp8;
- (double)retryFactor;
- (void)setRetrySelector:(SEL)fp8;
- (SEL)retrySelector;
- (void)setReceivedDataSelector:(SEL)fp8;
- (SEL)receivedDataSelector;
- (void)setSentDataSelector:(SEL)fp8;
- (SEL)sentDataSelector;
- (void)setThread:(id)fp8;
- (id)thread;
- (void)setServicePriority:(int)fp8;
- (int)servicePriority;
- (void)setServiceHost:(id)fp8;
- (id)serviceHost;
- (void)setService:(id)fp8;
- (id)service;
- (void)setAuthorizer:(id)fp8;
- (id)authorizer;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setPostStream:(id)fp8;
- (id)postStream;
- (void)setPostData:(id)fp8;
- (id)postData;
- (void)setProxyCredential:(id)fp8;
- (id)proxyCredential;
- (void)setCredential:(id)fp8;
- (id)credential;
- (void)setMutableRequest:(id)fp8;
- (id)mutableRequest;
- (void)setCommentWithFormat:(id)fp8;
- (void)addPropertiesFromDictionary:(id)fp8;
- (id)propertyForKey:(id)fp8;
- (void)setProperty:(id)fp8 forKey:(id)fp12;
- (id)properties;
- (void)setProperties:(id)fp8;
- (void)setUserData:(id)fp8;
- (id)userData;
- (void)setFetchHistory:(id)fp8;
- (id)fetchHistory;
- (void)setCookieStorageMethod:(int)fp8;
- (int)cookieStorageMethod;
- (void)setMinRetryInterval:(double)fp8;
- (double)minRetryInterval;
- (void)setMaxRetryInterval:(double)fp8;
- (double)maxRetryInterval;
- (void)setRetryEnabled:(BOOL)fp8;
- (BOOL)isRetryEnabled;
- (double)nextRetryInterval;
- (unsigned int)retryCount;
- (void)destroyRetryTimer;
- (void)retryTimerFired:(id)fp8;
- (void)primeRetryTimerWithNewTimeInterval:(double)fp8;
- (void)beginRetryTimer;
- (BOOL)shouldRetryNowForStatus:(int)fp8 error:(id)fp12;
- (BOOL)isRetryError:(id)fp8;
- (void)logNowWithError:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (BOOL)shouldReleaseCallbacksUponCompletion;
- (void)connectionDidFinishLoading:(id)fp8;
- (int)statusAfterHandlingNotModifiedError;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didSendBodyData:(int)fp12 totalBytesWritten:(int)fp16 totalBytesExpectedToWrite:(int)fp20;
- (BOOL)invokeRetryCallback:(SEL)fp8 target:(id)fp12 willRetry:(BOOL)fp16 error:(id)fp20;
- (void)invokeSentDataCallback:(SEL)fp8 target:(id)fp12 didSendBodyData:(int)fp16 totalBytesWritten:(int)fp20 totalBytesExpectedToWrite:(int)fp24;
- (void)invokeFetchCallback:(SEL)fp8 target:(id)fp12 data:(id)fp16 error:(id)fp20;
- (void)invokeFetchCallbacksWithData:(id)fp8 error:(id)fp12;
- (void)connection:(id)fp8 didReceiveAuthenticationChallenge:(id)fp12;
- (void)handleCookiesForResponse:(id)fp8;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (id)fileManager;
- (void)waitForCompletionWithTimeout:(double)fp8;
- (void)retryFetch;
- (void)sendStopNotificationIfNeeded;
- (void)stopFetching;
- (void)stopFetchReleasingCallbacks:(BOOL)fp8;
- (void)releaseCallbacks;
- (id)responseHeaders;
- (int)statusCode;
- (BOOL)isFetching;
- (void)addCookiesToRequest:(id)fp8;
- (id)createTempDownloadFilePathForPath:(id)fp8;
- (BOOL)beginFetchWithCompletionHandler:(id)fp;
- (void)authorizer:(id)fp8 request:(id)fp12 finishedWithError:(id)fp16;
- (BOOL)authorizeRequest;
- (void)endBackgroundTask;
- (void)backgroundFetchExpired;
- (void)failToBeginFetchWithError:(id)fp8;
- (BOOL)beginFetchMayDelay:(BOOL)fp8 mayAuthorize:(BOOL)fp12;
- (BOOL)beginFetchWithDelegate:(id)fp8 didFinishSelector:(SEL)fp12;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithRequest:(id)fp8;
- (id)init;

-(id)delegateQueue;
-(void)setDelegateQueue:(id)queue;

@end

@interface GTMOAuth2Authentication : NSObject
+ (id)scopeWithStrings:(id)fp8;
+ (id)dictionaryWithResponseData:(id)fp8;
+ (id)dictionaryWithResponseString:(id)fp8;
+ (id)unencodedOAuthParameterForString:(id)fp8;
+ (void)invokeDelegate:(id)fp8 selector:(SEL)fp12 object:(id)fp16 object:(id)fp20 object:(id)fp24;
+ (id)encodedQueryParametersForDictionary:(id)fp8;
+ (id)encodedOAuthValueForString:(id)fp8;
+ (id)authenticationWithServiceProvider:(id)fp8 tokenURL:(id)fp12 redirectURI:(id)fp16 clientID:(id)fp20 clientSecret:(id)fp24;
- (void)setAuthorizationQueue:(id)fp8;
- (id)authorizationQueue;
- (void)setProperties:(id)fp8;
- (id)properties;
- (void)setUserData:(id)fp8;
- (id)userData;
- (void)setShouldAuthorizeAllRequests:(BOOL)fp8;
- (BOOL)shouldAuthorizeAllRequests;
- (void)setParserClass:(Class)fp8;
- (Class)parserClass;
- (void)setFetcherService:(id)fp8;
- (id)fetcherService;
- (void)setRefreshFetcher:(id)fp8;
- (id)refreshFetcher;
- (void)setAdditionalTokenRequestParameters:(id)fp8;
- (id)additionalTokenRequestParameters;
- (void)setExpirationDate:(id)fp8;
- (id)expirationDate;
- (void)setTokenURL:(id)fp8;
- (id)tokenURL;
- (void)setParameters:(id)fp8;
- (id)parameters;
- (void)setRedirectURI:(id)fp8;
- (id)redirectURI;
- (void)setClientSecret:(id)fp8;
- (id)clientSecret;
- (void)setClientID:(id)fp8;
- (id)clientID;
- (id)propertyForKey:(id)fp8;
- (void)setProperty:(id)fp8 forKey:(id)fp12;
- (void)setUserEmailIsVerified:(id)fp8;
- (id)userEmailIsVerified;
- (void)setUserEmail:(id)fp8;
- (id)userEmail;
- (void)setServiceProvider:(id)fp8;
- (id)serviceProvider;
- (void)updateExpirationDate;
- (void)setExpiresIn:(id)fp8;
- (id)expiresIn;
- (void)setScope:(id)fp8;
- (id)scope;
- (void)setTokenType:(id)fp8;
- (id)tokenType;
- (void)setErrorString:(id)fp8;
- (id)errorString;
- (void)setAssertion:(id)fp8;
- (id)assertion;
- (void)setCode:(id)fp8;
- (id)code;
- (void)setRefreshToken:(id)fp8;
- (id)refreshToken;
- (void)setAccessToken:(id)fp8;
- (id)accessToken;
- (void)reset;
- (BOOL)primeForRefresh;
- (id)persistenceResponseString;
- (void)setKeysForPersistenceResponseString:(id)fp8;
- (void)notifyFetchIsRunning:(BOOL)fp8 fetcher:(id)fp12 type:(id)fp16;
- (void)tokenFetcher:(id)fp8 finishedWithData:(id)fp12 error:(id)fp16;
- (id)beginTokenFetchWithDelegate:(id)fp8 didFinishSelector:(SEL)fp12;
- (id)userAgent;
- (void)waitForCompletionWithTimeout:(double)fp8;
- (BOOL)shouldRefreshAccessToken;
- (BOOL)canAuthorize;
- (BOOL)authorizeRequest:(id)fp8;
- (void)invokeCallbackArgs:(id)fp8;
- (BOOL)authorizeRequestImmediateArgs:(id)fp8;
- (void)stopAuthorization;
- (BOOL)isAuthorizedRequest:(id)fp8;
- (BOOL)isAuthorizingRequest:(id)fp8;
- (void)auth:(id)fp8 finishedRefreshWithFetcher:(id)fp12 error:(id)fp16;
- (BOOL)authorizeRequestArgs:(id)fp8;
- (void)authorizeRequest:(id)fp8 delegate:(id)fp12 didFinishSelector:(SEL)fp16;
- (void)authorizeRequest:(id)fp8 completionHandler:(id)fp;
- (id)dictionaryWithJSONData:(id)fp8;
- (void)setKeysForResponseJSONData:(id)fp8;
- (void)setKeysForResponseString:(id)fp8;
- (void)setKeysForResponseDictionary:(id)fp8;
- (void)dealloc;
- (id)description;
- (id)init;

@end

@interface GTMOAuth2Authentication (TubeReplacer)
- (NSString*)sid;
- (NSString*)hsid;
- (NSString*)ssid;
- (NSString*)sidcc;
- (NSString*)sapisid;
- (NSString*)datasyncID;
- (NSString*)channelID;
-(void)fillInTokenExtraDataWithParameters:(NSDictionary*)params;
@end