/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTString)
+ (id)notWebSafeBase64Chars;
+ (id)spaces:(int)fp8;
- (BOOL)containsWebSafeBase64CharsOnly;
- (id)validURL;
- (id)escapedURL;
- (id)escapedURLString;
- (BOOL)containsString:(id)fp8;
- (BOOL)containsString:(id)fp8 options:(unsigned int)fp12;
- (id)lines;
- (id)trim;
@end

