/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTPositioning)
+ (struct CGRect)boundsForView:(id)fp8;
+ (struct CGRect)frameForView:(id)fp8;
- (struct CGRect)positioningRectOfView:(id)fp8;
- (void)sizeHeightToFitWithWidth:(float)fp8;
- (void)sizeWidthToFitAspectRatioWithHeight:(float)fp8;
- (void)sizeWidthToFitWithHeight:(float)fp8;
- (void)alignCenterToCenterOfView:(id)fp8;
- (void)alignCenterBottomToCenterBottomOfView:(id)fp8 paddingY:(float)fp12;
- (void)alignCenterTopToCenterBottomOfView:(id)fp8 paddingY:(float)fp12;
- (void)alignCenterTopToCenterTopOfView:(id)fp8 paddingY:(float)fp12;
- (void)alignCenterLeftToCenterRightOfView:(id)fp8 paddingX:(float)fp12;
- (void)alignCenterRightToCenterRightOfView:(id)fp8 paddingX:(float)fp12;
- (void)alignCenterRightToCenterLeftOfView:(id)fp8 paddingX:(float)fp12;
- (void)alignCenterLeftToCenterLeftOfView:(id)fp8 paddingX:(float)fp12;
- (void)alignBottomRightToBottomRightOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignBottomRightToBottomLeftOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignBottomRightToTopRightOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignBottomLeftToTopRightOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignBottomLeftToBottomRightOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignBottomLeftToBottomLeftOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignBottomLeftToTopLeftOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignTopRightToBottomRightOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignTopRightToTopRightOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignTopLeftToBottomRightOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignTopRightToTopLeftOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignTopLeftToBottomLeftOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignTopLeftToTopRightOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)alignTopLeftToTopLeftOfView:(id)fp8 paddingX:(float)fp12 paddingY:(float)fp16;
- (void)enableSubviewsFrameDebugging;
- (void)enableFrameDebugging;
- (struct CGPoint)origin;
- (void)setOrigin:(struct CGPoint)fp8;
- (float)height;
- (void)setHeight:(float)fp8;
- (float)width;
- (void)setWidth:(float)fp8;
- (struct CGSize)size;
- (void)setSize:(struct CGSize)fp8;
@end

