/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (LocalizedQuantities)
- (id)localizedQuantityStringForKey:(id)fp8 quantity:(unsigned int)fp12 table:(id)fp16;
@end

