/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (Blocks)
- (void)performBlock:(id)fp(null);
- (void)performSelector:(SEL)fp8 withArgument:(void *)fp12 withArgument:(void *)fp16 withArgument:(void *)fp20;
- (void)performBlock:(id)fp(null) onThread:(void)fp8 waitUntilDone:(id)fp12;
@end

