/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTColors)
+ (id)colorWith8BitRed:(int)fp8 green:(int)fp12 blue:(int)fp16;
+ (id)backgroundColor;
+ (id)toastColor;
+ (id)guidePromoMessageColor;
+ (id)titleBarColorIPad;
+ (id)channelHeaderStatColorIPad;
+ (id)channelHeaderTitleColorIPad;
+ (id)sparkleBarShadowColor;
+ (id)sparkleBarSeparatorColor;
+ (id)sparkleBarNoValueColorLighter;
+ (id)sparkleBarNoValueColor;
+ (id)sparkleBarNegativeColorLighter;
+ (id)sparkleBarNegativeColor;
+ (id)sparkleBarPositiveColorLighter;
+ (id)sparkleBarPositiveColor;
+ (id)subtitlesBackgroundColor;
+ (id)backgroundDarkColor;
+ (id)cellRiverEventColorIPad;
+ (id)cellRiverSubjectColorIPad;
+ (id)cellGuideTitleSelectedColor;
+ (id)cellGuideSelectedTitleColor;
+ (id)cellGuideTitleColor;
+ (id)cellPurchaseExpiresSoonColor;
+ (id)cellViewsColorIPad;
+ (id)cellTitleColorIPad;
+ (id)cellVideoCountBadgeColorIPad;
@end

