/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTUserAgent)
+ (id)requestWithRequest:(id)fp8;
+ (id)newSendSynchronousRequest:(id)fp8 returningResponse:(id *)fp12 error:(id *)fp16;
+ (id)userAgent;
+ (void)setupUserAgentOverwrite;
- (id)newInitWithRequest:(id)fp8 delegate:(id)fp12 startImmediately:(BOOL)fp16;
- (id)newInitWithRequest:(id)fp8 delegate:(id)fp12;
@end

