/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface _AVAudioSessionCategoryPlayback (YTFonts)
+ (id)fontWithName:(id)fp8 iPadSize:(float)fp12 iPhoneSize:(float)fp16;
+ (id)largeBoldFontTV;
+ (id)XLargeBoldFont;
+ (id)largeBoldFont;
+ (id)mediumBoldFont;
+ (id)smallBoldFont;
+ (id)XSmallBoldFont;
+ (id)XLargeRegularFont;
+ (id)largeRegularFont;
+ (id)mediumRegularFont;
+ (id)smallRegularFont;
+ (id)XSmallRegularFont;
@end

