/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol AudienceScrollViewDelegate
- (void)audienceScrollView:(id)fp8 didToggleCircle:(id)fp12;
- (void)audienceScrollView:(id)fp8 didToggleMetaCircle:(id)fp12;
@end

