/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "AudienceScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AudienceScrollView, NSArray, NSMutableArray, TopShadowView, UITableView;

@interface AudiencePickerController : _AVAudioSessionCategoryPlayback <UITableViewDelegate, UITableViewDataSource, AudienceScrollViewDelegate>
{
    NSArray *circles_;
    NSMutableArray *selectedCircles_;
    NSMutableArray *selectedMetaCircles_;
    AudienceScrollView *audienceScrollView_;
    UITableView *tableView_;
    TopShadowView *shadow_;
    id <AudiencePickerDelegate> delegate_;
}

+ (id)imageForCircle:(id)fp8;
+ (id)localizedNameForMetaCircle:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)updateTableViewSize;
- (void)checkUITableViewCell:(id)fp8 checked:(BOOL)fp12;
- (void)setSelectedCircles:(id)fp8 metaCircles:(id)fp12;
- (void)setCircles:(id)fp8;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)audienceScrollView:(id)fp8 didToggleCircle:(id)fp12;
- (void)audienceScrollView:(id)fp8 didToggleMetaCircle:(id)fp12;
- (void)didPressPick:(id)fp8;
- (void)didPressCancel:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillUnload;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

