/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol AudiencePickerDelegate
- (void)audiencePicker:(id)fp8 didPickCircles:(id)fp12 metaCircles:(id)fp16;
- (void)audiencePickerDidCancel:(id)fp8;
@end

