/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@class NSData, NSString, PBArray, PBGeneratedMessage;

struct AppRequestTimeoutListener;

struct AudioBlock;

struct AudioCaptureInterface;

struct AudioEncoderInterface;

struct AudioParameters;

struct AudioQueueBuffer;

struct AudioResamplerInterface;

struct AudioStreamBasicDescription {
    double mSampleRate;
    unsigned int mFormatID;
    unsigned int mFormatFlags;
    unsigned int mBytesPerPacket;
    unsigned int mFramesPerPacket;
    unsigned int mBytesPerFrame;
    unsigned int mChannelsPerFrame;
    unsigned int mBitsPerChannel;
    unsigned int mReserved;
};

struct AudioTimeStamp {
    double _field1;
    unsigned long long _field2;
    double _field3;
    unsigned long long _field4;
    struct SMPTETime _field5;
    unsigned int _field6;
    unsigned int _field7;
};

struct CGAffineTransform {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
};

struct CGColor;

struct CGContext;

struct CGImage;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct ClientExperimentConfig {
    void **_field1;
    struct ClientParameters *_field2;
    unsigned int :1;
};

struct ClientParameters {
    void **_field1;
    _Bool _field2;
    _Bool _field3;
    double _field4;
    double _field5;
    double _field6;
    _Bool _field7;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};

struct ClientReport;

struct ClockInterface;

struct CookieService;

struct DeferredRequest;

struct GGpsProfile;

struct GLatLng;

struct GList<common_base::SimpleRequestQueue::DeferredRequest> {
    struct GListItem<common_base::SimpleRequestQueue::DeferredRequest> _field1;
    int _field2;
};

struct GListItem<common_base::SimpleRequestQueue::DeferredRequest> {
    struct DeferredRequest *_field1;
    struct DeferredRequest *_field2;
};

struct GLocReply {
    void **_field1;
    int _field2;
    _Bool _field3;
    struct GVector<lbs::GLocReplyElement *> _field4;
    struct GString _field5;
    _Bool _field6;
};

struct GLocation {
    void **_field1;
    struct GLatLng *_field2;
    _Bool _field3;
    struct GString _field4;
    _Bool _field5;
    int _field6;
    _Bool _field7;
    int _field8;
    _Bool _field9;
    struct GVector<lbs::GFeature *> _field10;
    long long _field11;
    _Bool _field12;
    _Bool _field13;
    _Bool _field14;
    int _field15;
    _Bool _field16;
    struct GString _field17;
    _Bool _field18;
    int _field19;
    _Bool _field20;
    int _field21;
    _Bool _field22;
    int _field23;
    _Bool _field24;
    int _field25;
    _Bool _field26;
    struct GGpsProfile *_field27;
    _Bool _field28;
    struct GString _field29;
    _Bool _field30;
    float _field31;
    _Bool _field32;
    _Bool _field33;
    _Bool _field34;
};

struct GString {
    struct GStringStorage *_field1;
};

struct GStringStorage;

struct GTMHTTPCppCallback {
    void **_field1;
};

struct GVector<lbs::GFeature *> {
    void *_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct GVector<lbs::GLocReplyElement *> {
    void *_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct GVector<multimodal::RequestAttributeProto *> {
    void *_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct GVector<unsigned char> {
    void *_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct GVector<wireless_push_apple::ServicePreference *> {
    void *_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct GVector<wireless_push_apple::Subscription *> {
    void *_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct GVector<wireless_push_apple::WeekdayTimes *> {
    void *_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct GenieClientFeedService;

struct GoogleSearchRequestProto {
    void **_field1;
    struct GString _field2;
    struct RecognitionResultSetProto *_field3;
    struct GVector<multimodal::RequestAttributeProto *> _field4;
    struct GString _field5;
    struct GString _field6;
    struct GString _field7;
    int _field8;
    struct GString _field9;
    struct GVector<multimodal::RequestAttributeProto *> _field10;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};

struct HttpRequestFactory;

struct IPhoneNotificationGetNotificationsService;

struct IPhoneNotificationGetSettingsService;

struct IPhoneNotificationSetSettingsService;

struct IdleScreenSearchInfo;

struct JKConstBuffer {
    struct JKConstPtrRange _field1;
};

struct JKConstPtrRange {
    char *_field1;
    unsigned int _field2;
};

struct JKEncodeCache {
    id _field1;
    unsigned int _field2;
    unsigned int _field3;
};

struct JKEncodeState {
    struct JKManagedBuffer _field1;
    struct JKManagedBuffer _field2;
    unsigned int _field3;
    struct JKFastClassLookup _field4;
    struct JKEncodeCache _field5[1024];
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    id _field9;
};

struct JKFastClassLookup {
    void *_field1;
    void *_field2;
    void *_field3;
    void *_field4;
    void *_field5;
};

struct JKHashTableEntry {
    unsigned int _field1;
    id _field2;
    id _field3;
};

struct JKManagedBuffer {
    struct JKPtrRange _field1;
    unsigned int _field2;
    unsigned int _field3;
};

struct JKObjCImpCache {
    Class _field1;
    void *_field2;
    void *_field3;
};

struct JKObjectStack {
    void **_field1;
    void **_field2;
    unsigned int *_field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
};

struct JKParseState {
    unsigned int _field1;
    struct JKConstBuffer _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    struct JKParseToken _field9;
    struct JKObjectStack _field10;
    struct JKTokenCache _field11;
    struct JKObjCImpCache _field12;
    id _field13;
    int _field14;
    char _field15;
};

struct JKParseToken {
    struct JKConstPtrRange _field1;
    unsigned int _field2;
    struct JKTokenValue _field3;
    struct JKManagedBuffer _field4;
};

struct JKPtrRange {
    char *_field1;
    unsigned int _field2;
};

struct JKTokenCache {
    struct JKTokenCacheItem *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned char _field4[1024];
};

struct JKTokenCacheItem;

struct JKTokenValue {
    struct JKConstPtrRange _field1;
    unsigned int _field2;
    unsigned int _field3;
    union {
        long long _field1;
        unsigned long long _field2;
        double _field3;
    } _field4;
    struct JKTokenCacheItem *_field5;
};

struct MASFRequestQueue {
    void **_field1;
    struct ClockInterface *_field2;
    struct GList<common_base::SimpleRequestQueue::DeferredRequest> _field3;
    struct GList<common_base::SimpleRequestQueue::DeferredRequest> _field4;
    id _field5;
};

struct MASFRequestService;

struct MuxConfig {
    struct GString _field1;
    struct GString _field2;
    struct GString _field3;
    struct GString _field4;
    struct GString _field5;
    struct GString _field6;
    struct GString _field7;
    _Bool _field8;
    _Bool _field9;
};

struct Notification {
    void **_field1;
    int _field2;
    struct GString _field3;
    int _field4;
    struct GString _field5;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};

struct OpaqueAudioFileID;

struct OpaqueAudioQueue;

struct PBExtensionDescription {
    int _field1;
    char *_field2;
    int _field3;
    union {
        char _field1;
        unsigned int _field2;
        int _field3;
        float _field4;
        unsigned long long _field5;
        long long _field6;
        double _field7;
        int _field8;
        long long _field9;
        int _field10;
        long long _field11;
        unsigned int _field12;
        unsigned long long _field13;
        id _field14;
        id _field15;
        id _field16;
        id _field17;
        int _field18;
        id _field19;
        id _field20;
    } _field4;
    char *_field5;
    unsigned int _field6;
};

struct PBGeneratedMessage_Storage;

struct PlacesEventInfo;

struct RecognitionParameters {
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
};

struct RecognitionResultSetProto;

struct RequestInterface {
    void **_field1;
};

struct RequestTimeoutListener;

struct RequesterInterfaceBridge;

struct ResourceService;

struct ReverseGeocodeService;

struct RlzService;

struct SMPTETime {
    short _field1;
    short _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    short _field6;
    short _field7;
    short _field8;
    short _field9;
};

struct ScopedPtr<common_base::ClockInterface> {
    struct ClockInterface *_field1;
};

struct ServicePreference {
    void **_field1;
    int _field2;
    struct GVector<wireless_push_apple::Subscription *> _field3;
    unsigned int :1;
};

struct SessionTimeoutListener;

struct Specification;

struct SpeechRecognizerClient {
    void **_field1;
    void **_field2;
    void **_field3;
    struct SpeechTransportChannel *_field4;
    struct SpeechTransportChannel *_field5;
    struct SpeechTransportChannel *_field6;
    struct SpeechRecognizerListener *_field7;
    struct AudioCaptureInterface *_field8;
    int _field9;
    _Bool _field10;
    _Bool _field11;
    _Bool _field12;
    _Bool _field13;
    struct AudioParameters *_field14;
    struct AudioParameters *_field15;
    struct AudioEncoderInterface *_field16;
    struct AudioResamplerInterface *_field17;
    short *_field18;
    unsigned int _field19;
    double _field20;
    double _field21;
    double _field22;
    int _field23;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field24;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field25;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field26;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field27;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field28;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field29;
    struct RecognitionParameters _field30;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field31;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field32;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field33;
    int _field34;
    struct vector<speech::AudioBlock *, std::allocator<speech::AudioBlock *>> _field35;
    struct Timer *_field36;
    struct Timer *_field37;
    struct Timer *_field38;
    struct RequestTimeoutListener *_field39;
    struct SessionTimeoutListener *_field40;
    struct AppRequestTimeoutListener *_field41;
    struct ClientReport *_field42;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field43;
    _Bool _field44;
    unsigned long long _field45;
    unsigned long long _field46;
    _Bool _field47;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field48;
    _Bool _field49;
    int _field50;
    struct SpeechRequestSender *_field51;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field52;
    struct ClientExperimentConfig *_field53;
    _Bool _field54;
    int _field55;
    struct ScopedPtr<common_base::ClockInterface> _field56;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field57;
};

struct SpeechRecognizerListener {
    void **_field1;
};

struct SpeechRequestSender;

struct SpeechTransportChannel;

struct Subscription {
    void **_field1;
    struct GString _field2;
    int _field3;
    struct GString _field4;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};

struct Timer;

struct UIEdgeInsets {
    float top;
    float left;
    float bottom;
    float right;
};

struct UserEventLogService<IdleScreenSearchInfo>;

struct UserEventLogService<PlacesEventInfo>;

struct UserIdentification {
    void **_field1;
    struct GString _field2;
    struct GString _field3;
    unsigned int :1;
    unsigned int :1;
};

struct UserServicePreferences {
    void **_field1;
    struct UserIdentification *_field2;
    struct GVector<wireless_push_apple::ServicePreference *> _field3;
    struct GVector<wireless_push_apple::WeekdayTimes *> _field4;
    struct GString _field5;
    struct GString _field6;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};

struct UserSettingsResponse {
    void **_field1;
    int _field2;
    struct GString _field3;
    struct GVector<unsigned char> _field4;
    struct GString _field5;
    struct GVector<wireless_push_apple::ServicePreference *> _field6;
    struct GVector<wireless_push_apple::WeekdayTimes *> _field7;
    struct GString _field8;
    struct GString _field9;
    struct GString _field10;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};

struct _Alloc_hider {
    char *_field1;
};

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct _NSZone;

struct _TBXMLAttribute {
    char *_field1;
    char *_field2;
    struct _TBXMLAttribute *_field3;
};

struct _TBXMLAttributeBuffer {
    struct _TBXMLAttribute *_field1;
    struct _TBXMLAttributeBuffer *_field2;
    struct _TBXMLAttributeBuffer *_field3;
};

struct _TBXMLElement {
    char *_field1;
    char *_field2;
    struct _TBXMLAttribute *_field3;
    struct _TBXMLElement *_field4;
    struct _TBXMLElement *_field5;
    struct _TBXMLElement *_field6;
    struct _TBXMLElement *_field7;
    struct _TBXMLElement *_field8;
};

struct _TBXMLElementBuffer {
    struct _TBXMLElement *_field1;
    struct _TBXMLElementBuffer *_field2;
    struct _TBXMLElementBuffer *_field3;
};

struct _Vector_impl {
    struct AudioBlock **_field1;
    struct AudioBlock **_field2;
    struct AudioBlock **_field3;
};

struct __CFAttributedString;

struct __MASFCookieRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct CookieService *_field2;
};

struct __MASFGenieClientFeedRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct GenieClientFeedService *_field2;
};

struct __MASFGoogleMobileEventLogRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct UserEventLogService<IdleScreenSearchInfo> *_field2;
    struct IdleScreenSearchInfo *_field3;
    struct RequestInterface *_field4;
};

struct __MASFGooglePlacesEventLogRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct UserEventLogService<PlacesEventInfo> *_field2;
    struct PlacesEventInfo *_field3;
    struct RequestInterface *_field4;
};

struct __MASFMuxConfigPrivate {
    struct MuxConfig *_field1;
};

struct __MASFNotificationGetNotificationsRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct IPhoneNotificationGetNotificationsService *_field2;
    struct RequestInterface *_field3;
};

struct __MASFNotificationGetSettingsRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct IPhoneNotificationGetSettingsService *_field2;
    struct RequestInterface *_field3;
};

struct __MASFNotificationSetSettingsRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct IPhoneNotificationSetSettingsService *_field2;
    struct RequestInterface *_field3;
};

struct __MASFRLZRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct RlzService *_field2;
};

struct __MASFRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct MASFRequestService *_field2;
};

struct __MASFResourceRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct ResourceService *_field2;
    struct Specification *_field3;
    struct RequestInterface *_field4;
};

struct __MASFReverseGeocodeRequestPrivate {
    struct RequesterInterfaceBridge *_field1;
    struct ReverseGeocodeService *_field2;
};

struct __MASFServiceMuxPrivate {
    struct HttpRequestFactory *_field1;
    struct ClockInterface *_field2;
    struct MASFRequestQueue *_field3;
    struct RequesterInterfaceBridge *_field4;
};

struct __SCNetworkReachability;

struct basic_string<char, std::char_traits<char>, std::allocator<char>> {
    struct _Alloc_hider _field1;
};

struct in_addr {
    unsigned int _field1;
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct vector<speech::AudioBlock *, std::allocator<speech::AudioBlock *>> {
    struct _Vector_impl _field1;
};

typedef struct {
    long long _field1;
    int _field2;
    unsigned int _field3;
    long long _field4;
} CDAnonymousStruct1;

typedef struct {
    id _field1;
    unsigned short _field2;
} CDAnonymousStruct4;

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
} CDAnonymousStruct2;

typedef struct {
    int _field1;
    int _field2;
} CDAnonymousStruct3;

typedef struct {
    unsigned int _field1;
    char *_field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    int _field6;
    unsigned int _field7;
    char _field8;
    char *_field9;
    char *_field10;
    char *_field11;
    char *_field12;
    char *_field13;
    union {
        char _field1;
        unsigned int _field2;
        int _field3;
        float _field4;
        unsigned long long _field5;
        long long _field6;
        double _field7;
        int _field8;
        long long _field9;
        int _field10;
        long long _field11;
        unsigned int _field12;
        unsigned long long _field13;
        id _field14;
        id _field15;
        id _field16;
        id _field17;
        int _field18;
        id _field19;
        id _field20;
    } _field14;
    char *_field15;
    char *_field16;
    void *_field17;
} CDAnonymousStruct5;

typedef struct {
    unsigned long _field1;
    id *_field2;
    unsigned long *_field3;
    unsigned long _field4[5];
} CDAnonymousStruct6;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
} CDAnonymousStruct7;

typedef union {
    char _field1;
    unsigned int _field2;
    int _field3;
    float _field4;
    unsigned long long _field5;
    long long _field6;
    double _field7;
    int _field8;
    long long _field9;
    int _field10;
    long long _field11;
    unsigned int _field12;
    unsigned long long _field13;
    id _field14;
    id _field15;
    id _field16;
    id _field17;
    int _field18;
    id _field19;
    id _field20;
} CDAnonymousUnion1;

typedef union {
    char valueBool;
    unsigned int valueFixed32;
    int valueSFixed32;
    float valueFloat;
    unsigned long long valueFixed64;
    long long valueSFixed64;
    double valueDouble;
    int valueInt32;
    long long valueInt64;
    int valueSInt32;
    long long valueSInt64;
    unsigned int valueUInt32;
    unsigned long long valueUInt64;
    NSData *valueData;
    NSString *valueString;
    PBGeneratedMessage *valueMessage;
    PBGeneratedMessage *valueGroup;
    int valueEnum;
    PBArray *valueArray;
    id valueObject;
} CDAnonymousUnion2;

