/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIAccelerometerDelegate-Protocol.h"

@interface GADGestureUtil : _AVAudioSessionCategoryPlayback <UIAccelerometerDelegate>
{
}

+ (void)reachability:(unsigned int *)fp8;
+ (id)viewInheritenceHierarchy:(id)fp8 maxSize:(unsigned int)fp12;
+ (id)walkViews:(id)fp8;
+ (void)chainAccDelegatesIfNeeded;
+ (void)initGestures;
+ (void)accelerometer:(id)fp8 didAccelerate:(id)fp12;

@end

