/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString, NSURL;

@interface GIPAudioPlayer : _AVAudioSessionCategoryPlayback
{
    struct OpaqueAudioFileID *audioFile_;
    struct OpaqueAudioQueue *audioQueue_;
    struct AudioQueueBuffer **audioQueueBuffers_;
    struct AudioStreamBasicDescription audioFormat_;
    int state_;
    long long currentPacketNumber_;
    unsigned long bufferByteSize_;
    unsigned long numPacketsToRead_;
    NSString *fileName_;
    NSString *soundId_;
    NSURL *audioFileURL_;
    id <GIPAudioPlayerDelegate> delegate_;
    unsigned long long finishedTime_;
    unsigned long bufferCount_;
    double secondsPerBuffer_;
    BOOL tinyBuffers_;
}

+ (void)printAudioFileInfo:(struct OpaqueAudioFileID *)fp8;
+ (void)printTimeStamp:(struct AudioTimeStamp *)fp8;
+ (void)printAudioFormat:(struct AudioStreamBasicDescription *)fp8;
- (struct AudioStreamBasicDescription)audioFormat;
- (long long)currentPacketNumber;
- (unsigned long)numPacketsToRead;
- (void)setFinishedTime:(unsigned long long)fp8;
- (unsigned long long)finishedTime;
- (void)setSoundId:(id)fp8;
- (id)soundId;
- (id)fileName;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (struct OpaqueAudioFileID *)audioFile;
- (BOOL)shouldContinueRunning;
- (BOOL)isRunning;
- (void)incrementCurrentPacketNumberBy:(unsigned long)fp8;
- (void)calculateSizesFor:(double)fp8;
- (void)playbackDidComplete;
- (BOOL)pause;
- (BOOL)stop;
- (BOOL)play;
- (BOOL)primeAudioQueue;
- (BOOL)copyAudioFileProperties;
- (void)setupAudioQueueBuffers;
- (BOOL)setupPlaybackAudioQueueObject;
- (BOOL)openPlaybackFile:(id)fp8 fileType:(unsigned long)fp12;
- (BOOL)prepareToPlay;
- (void)releaseAudioQueue;
- (void)releaseAudioFile;
- (void)dealloc;
- (id)initWithFileName:(id)fp8 tinyBuffers:(BOOL)fp12;
- (id)initWithFileName:(id)fp8;

@end

