/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray, NSString;

@interface GIPCrashReportController : _AVAudioSessionCategoryPlayback
{
    NSString *appName_;
    NSString *appVersion_;
    NSString *reportsPath_;
    NSMutableArray *crashReportsStorage_;
    BOOL isRunning_;
    BOOL sendOnCrash_;
    BOOL sendOnException_;
    BOOL attachLogs_;
    unsigned int logsInterval_;
    BOOL finishPump_;
    BOOL logOnSimulator_;
    id <GIPCrashReportHandlerProtocol> crashHandler_;
    id <GIPCrashReportControllerDelegate> delegate_;
    NSMutableArray *storedCrashReports_;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)sharedInstance;
- (BOOL)isRunning;
- (void)setLogOnSimulator:(BOOL)fp8;
- (BOOL)logOnSimulator;
- (void)setLogsInterval:(unsigned int)fp8;
- (unsigned int)logsInterval;
- (void)setAttachLogs:(BOOL)fp8;
- (BOOL)attachLogs;
- (void)setSendOnException:(BOOL)fp8;
- (BOOL)sendOnException;
- (void)setSendOnCrash:(BOOL)fp8;
- (BOOL)sendOnCrash;
- (void)setReportsPath:(id)fp8;
- (id)reportsPath;
- (void)setAppVersion:(id)fp8;
- (id)appVersion;
- (void)setAppName:(id)fp8;
- (id)appName;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)parseEpochDate:(id)fp8;
- (void)pumpRunLoop;
- (void)deleteStoredCrashReports;
- (void)crashReportProcesed:(id)fp8;
- (void)logCrashes:(id)fp8;
- (void)logCrash:(id)fp8;
- (void)sendStoredCrashReports;
- (void)sendCrash;
- (void)sendCrashes:(id)fp8;
- (void)sendCrash:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (id)storedCrashReports;
- (id)loadStoredCrashReports;
- (id)latestLogs;
- (id)callStack;
- (void)handleException:(id)fp8;
- (void)handleSignal:(int)fp8;
- (void)stop;
- (void)start;
- (void)unregisterHandler:(id)fp8;
- (void)registerHandler:(id)fp8;
- (void)dealloc;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

