/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSArray, NSDate, NSException, NSMutableArray, NSString;

@interface GIPCrashReportData : _AVAudioSessionCategoryPlayback
{
    int signal_;
    NSException *exception_;
    NSArray *callStack_;
    NSArray *logs_;
    NSString *appName_;
    NSString *appVersion_;
    NSDate *crashDate_;
    int reportStatus_;
    NSMutableArray *files_;
}

+ (id)signalName:(int)fp8;
+ (id)platform;
- (void)setReportStatus:(int)fp8;
- (int)reportStatus;
- (void)setCrashDate:(id)fp8;
- (id)crashDate;
- (void)setAppVersion:(id)fp8;
- (id)appVersion;
- (void)setAppName:(id)fp8;
- (id)appName;
- (void)setLogs:(id)fp8;
- (id)logs;
- (void)setCallStack:(id)fp8;
- (id)callStack;
- (void)setException:(id)fp8;
- (id)exception;
- (void)setSignal:(int)fp8;
- (int)signal;
- (id)getAllReportFiles;
- (void)addReportFile:(id)fp8;
- (id)stringValue;
- (void)dealloc;
- (id)initWithException:(id)fp8 callStack:(id)fp12;
- (id)initWithSignal:(int)fp8 callStack:(id)fp12;

@end

