/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString, UIDevice;

@interface GIPDevice : _AVAudioSessionCategoryPlayback
{
    UIDevice *currentDevice_;
    NSString *deviceCategory_;
    unsigned int iPhoneOSVersion_;
    struct CGSize keyboardSize_;
    NSString *machineName_;
    NSString *normalizedModel_;
    NSString *generation_;
    BOOL isRecognizedModel_;
}

+ (void)ensureInitialized;
+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)currentDevice;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardWasShown:(id)fp8;
- (void)stopListeningToKeyboardEvents;
- (void)startListeningToKeyboardEvents;
- (BOOL)canPlayH264MainProfile;
- (BOOL)supportsAirPlayMirroring;
- (BOOL)proximityState;
- (BOOL)isProximitySensingEnabled;
- (void)setProximitySensingEnabled:(BOOL)fp8;
- (BOOL)hasInternalMic;
- (BOOL)canRecordAudio;
- (BOOL)canText;
- (BOOL)canCall;
- (id)model;
- (float)screenScaleFactor;
- (struct CGSize)screenDimensions;
- (unsigned int)iPhoneOSVersion;
- (BOOL)isRecognizedModel;
- (id)generation;
- (id)normalizedModel;
- (void)setModelAndGeneration;
- (struct CGSize)keyboardSize;
- (id)deviceCategory;
- (id)modelVersion;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

