/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class GIPFeedbackCollectedData, GIPFeedbackPrivacyCell, NSMutableArray, UIColor, UIPickerView, UITableView, UITableViewCell, UITextView;

@interface GIPFeedbackMainViewController : _AVAudioSessionCategoryPlayback <UITableViewDataSource, UITableViewDelegate, UITextViewDelegate>
{
    GIPFeedbackCollectedData *data_;
    UITableView *feedbackItems_;
    UITableViewCell *descriptionCell_;
    UITextView *descriptionTextView_;
    BOOL shouldSendSystemLogs_;
    BOOL shouldSendScreenshot_;
    BOOL shouldSendObfuscatedGaiaID_;
    int privacyPolicyRow_;
    UIColor *navigationBarTintColor_;
    UIColor *backgroundColor_;
    NSMutableArray *privacyControlCells_;
    GIPFeedbackPrivacyCell *sendSystemDataCell_;
    GIPFeedbackPrivacyCell *sendScreenshotCell_;
    GIPFeedbackPrivacyCell *sendUserAccountInfoCell_;
    UIPickerView *userPicker_;
    BOOL useStandardNavigationBackButton_;
}

+ (id)controllerWithCollectedData:(id)fp8;
+ (id)controllerWithReportType:(int)fp8;
- (void)setUseStandardNavigationBackButton:(BOOL)fp8;
- (BOOL)useStandardNavigationBackButton;
- (void)setBackgroundColor:(id)fp8;
- (id)backgroundColor;
- (void)setNavigationBarTintColor:(id)fp8;
- (id)navigationBarTintColor;
- (void)setDescriptionTextView:(id)fp8;
- (id)descriptionTextView;
- (void)setUserPicker:(id)fp8;
- (id)userPicker;
- (void)setFeedbackItems:(id)fp8;
- (id)feedbackItems;
- (void)setDescriptionCell:(id)fp8;
- (id)descriptionCell;
- (id)data;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)textViewDidBeginEditing:(id)fp8;
- (void)textViewDidEndEditing:(id)fp8;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)loadButtons;
- (void)loadToolbar;
- (void)backButtonDidTap:(id)fp8;
- (void)submitButtonDidTap:(id)fp8;
- (void)previewButtonDidTap:(id)fp8;
- (id)dataWithPrivateInfoStripped;
- (void)setSystemLogs:(id)fp8;
- (id)systemLogs;
- (void)setSendUserAccountInfo:(BOOL)fp8;
- (BOOL)sendUserAccountInfo;
- (void)setSendSystemData:(BOOL)fp8;
- (BOOL)sendSystemData;
- (void)setSendScreenshot:(BOOL)fp8;
- (BOOL)sendScreenshot;
- (void)setReportType:(int)fp8;
- (int)reportType;
- (void)setCrashReportDatas:(id)fp8;
- (id)crashReportDatas;
- (void)setScreenshot:(id)fp8;
- (id)screenshot;
- (void)setObfuscatedGaiaID:(id)fp8;
- (id)obfuscatedGaiaID;
- (void)setCategoryTag:(id)fp8;
- (id)categoryTag;
- (void)displayPrivacyAlert;
- (void)dealloc;
- (id)initWithCollectedData:(id)fp8;

@end

