/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GIPFeedbackCommon : _AVAudioSessionCategoryPlayback
{
}

+ (void)setTableHeadingTextColor:(id)fp8;
+ (void)setBackgroundColor:(id)fp8;
+ (void)setNavigationBarTintColor:(id)fp8;

@end

