/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GIPFeedbackLocalizedString : _AVAudioSessionCategoryPlayback
{
}

+ (id)yourReportWillHelpString;
+ (id)pleaseDescribeString;
+ (id)problemAndSystemInformationString;
+ (id)problemReportFormatString;
+ (id)sendReportString;
+ (id)noThanksString;
+ (id)lastSessionClosedString;
+ (id)applicationCrashString;
+ (id)includeUserAccountSubtextString;
+ (id)includeUserAccountHeadingString;
+ (id)includeScreenshotSubtextString;
+ (id)includeScreenshotHeadingString;
+ (id)includeSystemDataSubtextString;
+ (id)includeSystemDataHeadingString;
+ (id)privacyMainHeadingString;
+ (id)feedbackMainHeadingString;
+ (id)reportIssueString;
+ (id)previewString;
+ (id)okString;
+ (id)privacyPolicyHeadingString;
+ (id)privacyBodyString;
+ (id)backString;
+ (id)sendString;
+ (id)previewReportTitleString;
+ (id)screenshotHeadingString;
+ (id)systemLogHeadingString;
+ (id)timeHeadingString;
+ (id)osVersionHeadingString;
+ (id)deviceModelHeadingString;
+ (id)versionHeadingString;
+ (id)applicationNameHeadingString;
+ (id)reportButtonString;
+ (id)closeButtonString;
+ (id)clickReportString;
+ (id)crashedPreviouslyFormatString;
+ (id)sendMessageLaterString;
+ (id)sendMessageString;

@end

