/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class GIPFeedbackCollectedData, NSMutableArray, UIImage, UIImageView, UILabel, UITableView, UITableViewCell;

@interface GIPFeedbackPreviewViewController : _AVAudioSessionCategoryPlayback <UITableViewDataSource, UITableViewDelegate>
{
    GIPFeedbackCollectedData *data_;
    UITableView *previewTable_;
    NSMutableArray *headings_;
    NSMutableArray *subheadings_;
    UIImage *screenshot_;
    UIImageView *screenshotImageView_;
    UITableViewCell *screenshotCell_;
    int systemLogIndex_;
    int screenshotIndex_;
    UILabel *viewScreenshotCellTitle;
    UILabel *viewScreenshotCellTitle_;
}

- (void)setPreviewTable:(id)fp8;
- (id)previewTable;
- (void)setScreenshotImageView:(id)fp8;
- (id)screenshotImageView;
- (void)setViewScreenshotCellTitle:(id)fp8;
- (id)viewScreenshotCellTitle;
- (void)setScreenshotCell:(id)fp8;
- (id)screenshotCell;
- (void)setScreenshot:(id)fp8;
- (id)screenshot;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)fp8;
- (void)submitButtonDidTap:(id)fp8;
- (void)backToMainScreen;
- (void)updateCollectedData:(id)fp8;
- (void)dealloc;

@end

