/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIColor;

@interface GIPFeedbackStyleSet : _AVAudioSessionCategoryPlayback
{
    UIColor *navigationBarTintColor_;
    UIColor *backgroundColor_;
}

+ (id)styleSet;
- (void)setBackgroundColor:(id)fp8;
- (id)backgroundColor;
- (void)setNavigationBarTintColor:(id)fp8;
- (id)navigationBarTintColor;
- (void)dealloc;
- (id)init;

@end

