/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSArray;

@interface GIPInputShieldView : _AVAudioSessionCategoryPlayback
{
    NSArray *passthroughViews_;
}

- (void)setPassthroughViews:(id)fp8;
- (id)passthroughViews;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

