/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPCache-Protocol.h"

@class NSMutableArray, NSMutableDictionary;

@interface GIPLRUCache : _AVAudioSessionCategoryPlayback <GIPCache>
{
    NSMutableArray *access_;
    NSMutableDictionary *cache_;
    unsigned int cacheSize_;
}

- (unsigned int)cacheSize;
- (void)prune;
- (void)touch:(id)fp8;
- (id)allKeys;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)fp8;
- (unsigned int)count;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)objectForKey:(id)fp8;
- (void)flush;
- (id)description;
- (void)dealloc;
- (id)initWithCacheSize:(unsigned int)fp8;
- (id)init;

@end

