/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDictionary, NSString;

@interface GIPLocale : _AVAudioSessionCategoryPlayback
{
    NSString *language_;
    NSString *locale_;
    NSString *countryCode_;
    NSDictionary *appleLanguageToGoogleLanguage_;
}

+ (id)countryCodeForLocale:(id)fp8;
+ (id)countryCodeForRegion:(id)fp8;
+ (id)countryCodeForLanguage:(id)fp8;
+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)googleLocale;
- (id)countryCode;
- (id)locale;
- (id)language;
- (id)currentGoogleCountryCode;
- (id)currentGoogleLocale;
- (id)currentGoogleLanguage;
- (id)googleLocaleWithGoogleLanguage:(id)fp8 appleLocale:(id)fp12;
- (id)googleLanguageWithAppleLanguages:(id)fp8;
- (void)createAppleToGoogleLookups;
- (void)recalculateLocale;
- (void)dealloc;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

