/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITableViewDelegate-Protocol.h"

@class NSObject<GIPPullRefreshDelegate>, NSString, UIActivityIndicatorView, UIImage, UIImageView, UILabel, UIScrollView;

@interface GIPPullRefreshView : _AVAudioSessionCategoryPlayback <UITableViewDelegate>
{
    UIActivityIndicatorView *loadingSpinner_;
    UIScrollView *parentScrollView_;
    UIImageView *pullArrow_;
    int status_;
    UILabel *statusLabel_;
    NSObject<GIPPullRefreshDelegate> *delegate_;
    NSString *releaseText_;
    NSString *dragText_;
    NSString *loadingText_;
    UIImage *arrowImage_;
    float extraVerticalOffset_;
    float pullArrowTopMargin_;
    float pullHeight_;
}

- (void)setPullHeight:(float)fp8;
- (float)pullHeight;
- (void)setPullArrowTopMargin:(float)fp8;
- (float)pullArrowTopMargin;
- (void)setExtraVerticalOffset:(float)fp8;
- (float)extraVerticalOffset;
- (void)setParentScrollView:(id)fp8;
- (id)parentScrollView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setStatus:(int)fp8 animated:(BOOL)fp12;
- (int)status;
- (void)createView;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)fp8;
- (void)setActivityIndicatorViewStyle:(int)fp8;
- (int)activityIndicatorViewStyle;
- (void)setStatusColor:(id)fp8;
- (id)statusColor;
- (void)setStatusFont:(id)fp8;
- (id)statusFont;
- (void)setHidden:(BOOL)fp8 animated:(BOOL)fp12;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 dragText:(id)fp24 releaseText:(id)fp28 loadingText:(id)fp32 arrowImage:(id)fp36;

@end

