/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPToolbarPickerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class GIPContainerActionSheet, GIPToolbarPickerView, UIPopoverController;

@interface GIPPicker : _AVAudioSessionCategoryPlayback <UIActionSheetDelegate, GIPToolbarPickerDelegate, UIPopoverControllerDelegate>
{
    GIPContainerActionSheet *actionSheet_;
    BOOL isRetainingSelf_;
    id <GIPPickerDelegate> pickerDelegate_;
    UIPopoverController *popoverController_;
    GIPToolbarPickerView *toolbarPicker_;
}

- (void)setPickerDelegate:(id)fp8;
- (id)pickerDelegate;
- (void)buildPopover;
- (void)buildActionSheet;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)pickerDidPressClear:(id)fp8;
- (void)pickerDidPressSelect:(id)fp8;
- (void)pickerDidPressCancel:(id)fp8;
- (id)pickerView;
- (void)dismiss:(BOOL)fp8;
- (void)showInView:(id)fp8;
- (void)showFromRect:(struct CGRect)fp8 inView:(id)fp24 animated:(BOOL)fp28;
- (void)dealloc;
- (id)initWithPickerDelegate:(id)fp8 useClearButton:(BOOL)fp12;

@end

