/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class CAGradientLayer, CAShapeLayer, UIView;

@interface GIPPopoverView : _AVAudioSessionCategoryPlayback
{
    float arrowTipX_;
    unsigned int arrowDirection_;
    CAGradientLayer *backgroundLayer_;
    CAShapeLayer *maskLayer_;
    UIView *contentView_;
    struct CGRect popoverRect_;
    unsigned int permittedArrowDirections_;
    float borderCornerRadius_;
    float borderWidth_;
    BOOL shouldAlwaysShowArrow_;
    struct CGRect permittedRect_;
    UIView *topRightAccessoryView_;
    struct CGPoint topRightAccessoryViewOffset_;
}

- (void)setTopRightAccessoryViewOffset:(struct CGPoint)fp8;
- (struct CGPoint)topRightAccessoryViewOffset;
- (id)topRightAccessoryView;
- (void)setPermittedRect:(struct CGRect)fp8;
- (struct CGRect)permittedRect;
- (void)setShouldAlwaysShowArrow:(BOOL)fp8;
- (BOOL)shouldAlwaysShowArrow;
- (void)setArrowDirection:(unsigned int)fp8;
- (unsigned int)arrowDirection;
- (void)setContentView:(id)fp8;
- (id)contentView;
- (float)borderWidth;
- (float)borderCornerRadius;
- (void)layoutAccessoryView;
- (void)repositionLayersAroundContentView;
- (void)positionOverRect:(struct CGRect)fp8 permittedArrowDirections:(unsigned int)fp24;
- (void)layoutSubviews;
- (void)setContentView:(id)fp8 animated:(BOOL)fp12;
- (float)shadowOpacity;
- (void)setShadowOpacity:(float)fp8;
- (struct CGSize)shadowOffset;
- (void)setShadowOffset:(struct CGSize)fp8;
- (id)borderGradientColors;
- (void)setBorderGradientColors:(id)fp8;
- (void)setBorderWidth:(float)fp8;
- (void)setTopRightAccessoryView:(id)fp8;
- (void)setBorderCornerRadius:(float)fp8;
- (void)dealloc;
- (id)init;

@end

