/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPInputShieldView, GIPPopoverView, NSArray, UIViewController;

@interface GIPPopoverController : _AVAudioSessionCategoryPlayback
{
    GIPInputShieldView *inputShield_;
    UIViewController *contentViewController_;
    id <GIPPopoverControllerDelegate> delegate_;
    NSArray *passthroughViews_;
    BOOL popoverDarkensScreen_;
    GIPPopoverView *popoverView_;
}

- (id)popoverView;
- (BOOL)popoverDarkensScreen;
- (id)passthroughViews;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setContentViewController:(id)fp8;
- (id)contentViewController;
- (void)didTouchInputShield;
- (void)removePopoverFromView;
- (void)setPopoverDarkensScreen:(BOOL)fp8;
- (void)setContentViewController:(id)fp8 animated:(BOOL)fp12;
- (void)dismissPopoverAnimated:(BOOL)fp8;
- (void)presentPopoverFromRect:(struct CGRect)fp8 inView:(id)fp24 permittedArrowDirections:(unsigned int)fp28 animated:(BOOL)fp32;
- (void)presentPopoverInSpecificView:(id)fp8 fromRect:(struct CGRect)fp12 permittedArrowDirections:(unsigned int)fp28 animated:(BOOL)fp32;
- (void)setPassthroughViews:(id)fp8;
- (void)dealloc;
- (id)initWithContentViewController:(id)fp8;

@end

