/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIColor;

@interface GIPPageControl : _AVAudioSessionCategoryPlayback
{
    id <GIPPageControlDelegate> delegate_;
    int currentPage_;
    int numberOfPages_;
    BOOL hidesForSinglePage_;
    UIColor *pageColor_;
    UIColor *selectedColor_;
    struct CGSize dotSize_;
    struct CGSize dotFrame_;
    struct CGRect controlFrame_;
}

- (void)setDotFrame:(struct CGSize)fp8;
- (struct CGSize)dotFrame;
- (void)setDotSize:(struct CGSize)fp8;
- (struct CGSize)dotSize;
- (void)setSelectedColor:(id)fp8;
- (id)selectedColor;
- (void)setPageColor:(id)fp8;
- (id)pageColor;
- (BOOL)hidesForSinglePage;
- (int)numberOfPages;
- (int)currentPage;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)drawRect:(struct CGRect)fp8;
- (void)updateControlFrame;
- (void)layoutSubviews;
- (void)setHidesForSinglePage:(BOOL)fp8;
- (void)setCurrentPage:(int)fp8;
- (void)setNumberOfPages:(int)fp8;
- (void)updateHidden;
- (BOOL)shouldHide;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setUp;

@end

