/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPGoogleDialogDelegate-Protocol.h"
#import "GIPSpeechWindowDelegate-Protocol.h"
#import "GSKSessionConfig-Protocol.h"
#import "GSKSpeechRecognizerDelegate-Protocol.h"

@class GIPSpeechRecognitionRequest, GIPSpeechWindowController, GSKSpeechRecognizerClient;

@interface GIPSpeechController : _AVAudioSessionCategoryPlayback <GIPGoogleDialogDelegate, GIPSpeechWindowDelegate, GSKSpeechRecognizerDelegate, GSKSessionConfig>
{
    id <GIPSpeechControllerDelegate> delegate_;
    GIPSpeechWindowController *speechWindowController_;
    GSKSpeechRecognizerClient *speechRecognizer_;
    BOOL fastEnoughForWaveform_;
    double speechRecognizerIdleTimeout_;
    BOOL keepSessionActiveOnResume_;
    GIPSpeechRecognitionRequest *currentRequest_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setCurrentRequest:(id)fp8;
- (id)currentRequest;
- (void)recognitionDidFail:(id)fp8 withError:(id)fp12;
- (void)recognitionTimedOutOrFailed:(id)fp8 withError:(id)fp12 afterInterval:(double)fp16;
- (void)recognitionDidComplete:(id)fp8;
- (void)recognitionProgressDidUpdate:(id)fp8;
- (void)recognitionWasCanceled:(id)fp8;
- (void)captureDidFinish:(id)fp8;
- (void)captureDidStart:(id)fp8;
- (BOOL)startEnvironmentSampling;
- (BOOL)forceHiFi;
- (BOOL)forceLoFi;
- (BOOL)useHiFi;
- (id)clientReportDatabasePath;
- (id)bandwidthEstimatorDatabasePath;
- (id)locale;
- (id)experimentConfigCachePath;
- (id)utteranceDebugDirectory;
- (id)cookie;
- (id)sandboxServerPassword;
- (id)serverURL;
- (id)applicationIdentifier;
- (id)installInstanceKey;
- (float)audioInputLevel;
- (BOOL)isLiveWaveformEnabled;
- (void)dialog:(id)fp8 dialogDidPress:(id)fp12;
- (void)dialog:(id)fp8 rightButtonDidPress:(id)fp12;
- (void)dialog:(id)fp8 leftButtonDidPress:(id)fp12;
- (void)dialog:(id)fp8 defaultButtonDidPress:(id)fp12;
- (void)audioInterruptionDidStart:(id)fp8;
- (void)playSound:(id)fp8;
- (void)audioPlaybackDidComplete:(id)fp8;
- (void)showError:(id)fp8;
- (void)dismissDialogWithDelay;
- (void)dismissDialog;
- (void)suspendSpeechRecognizer;
- (void)cancelSpeechRecognizerIdleTimer;
- (void)startSpeechRecognizerIdleTimer;
- (void)interruptSpeechRecognizer;
- (void)activateSpeechRecognizer:(BOOL)fp8;
- (void)cancelRecognition;
- (void)reallyBeginRecognition:(unsigned long long)fp8;
- (void)beginRecognition:(id)fp8;
- (void)endRecording;
- (void)stop;
- (void)suspend;
- (void)showLoading;
- (void)reallyStart;
- (void)start;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationWillTerminate:(id)fp8;
- (void)applicationDidBecomeActive:(id)fp8;
- (void)applicationWillResignActive:(id)fp8;
- (id)speechRecognizer;
- (BOOL)fastEnoughForWaveform;
- (void)dealloc;
- (id)init;

@end

