/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GIPSpeechWindowConfiguration <NSObject>
- (int)maxSamples;
- (id)workingText;
- (id)finishedText;
- (id)canceledText;
- (id)cancelText;
- (id)stopText;
- (id)tryAgainText;
- (id)listeningText;
- (id)cautionImage;
- (id)shadowImage;
- (id)mainImage;
@end

