/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIActivityIndicatorView, UILabel;

@interface GIPToast : _AVAudioSessionCategoryPlayback
{
    UILabel *message_;
    UIActivityIndicatorView *spinner_;
}

+ (void)showTodo;
+ (void)hide;
+ (void)showToastWithSpinner:(id)fp8;
+ (void)showToast:(id)fp8 forDuration:(double)fp12;
+ (id)toast;
- (void)showMessage:(id)fp8 forDuration:(double)fp12 showIndicator:(BOOL)fp20;
- (void)createView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

