/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GIPToolbarPickerDelegate <NSObject>
- (void)pickerDidPressCancel:(id)fp8;
- (void)pickerDidPressClear:(id)fp8;
- (void)pickerDidPressSelect:(id)fp8;
@end

