/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSDate, NSString, NSTimer, UIWebView;

@interface GIPWebViewPageInfoMonitor : _AVAudioSessionCategoryPlayback
{
    id <GIPWebViewPageInfoMonitorDelegate> delegate_;
    UIWebView *webView_;
    NSString *currentURLString_;
    NSString *currentTitle_;
    NSTimer *timer_;
    NSDate *finishTime_;
}

- (void)setCurrentTitle:(id)fp8;
- (id)currentTitle;
- (void)setCurrentURLString:(id)fp8;
- (id)currentURLString;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)dealloc;
- (void)monitorPageInfoChangesWithInterval:(double)fp8 duration:(double)fp16;
- (void)updatePageInfoWithTimer:(id)fp8;
- (void)stopMonitoring;
- (void)updatePageInfo;
- (int)didObserveURLString:(id)fp8 pageTitle:(id)fp12;
- (int)didObserveURLString:(id)fp8;
- (id)initWithWebView:(id)fp8 delegate:(id)fp12;

@end

