/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class GIPResourceLoader, GIPWebView, GIPWebViewHistory, NSString, NSURL, NSURLRequest, UIActionSheet, UIActivityIndicatorView, UIAlertView, UIBarButtonItem, UIColor, UIToolbar;

@interface GIPWebViewController : _AVAudioSessionCategoryPlayback <UIAlertViewDelegate, UIActionSheetDelegate, UIWebViewDelegate>
{
    id <GIPWebViewControllerDelegate> delegate_;
    GIPWebView *webView_;
    UIBarButtonItem *backItem_;
    UIBarButtonItem *forwardItem_;
    UIBarButtonItem *safariItem_;
    UIBarButtonItem *reloadItem_;
    UIToolbar *internalToolbar_;
    UIActivityIndicatorView *spinner_;
    BOOL detectExternalURLs_;
    BOOL hideToolbarWithoutHistory_;
    BOOL showSpinnerInToolbar_;
    BOOL showsSpinner_;
    BOOL showsToolbar_;
    BOOL alwaysEnableBackButton_;
    BOOL usePageTitleAsViewTitle_;
    BOOL rewriteNewWindowLinks_;
    BOOL showErrorPageOnLoadFail_;
    BOOL showsOpenInSafariInToolbar_;
    BOOL showPromptWhenOpeningSafari_;
    UIAlertView *openInSafariPrompt_;
    NSURL *openInSafariURL_;
    BOOL allowBrowserSelection_;
    UIActionSheet *openInBrowserActionSheet_;
    int safariButtonIndex_;
    int chromeButtonIndex_;
    NSURL *currentURL_;
    NSString *currentPageTitle_;
    BOOL webViewLoaded_;
    NSURLRequest *initialRequest_;
    int numberOfItemsLoading_;
    GIPWebViewHistory *history_;
    id <GIPWebViewToolbarProtocol> toolbar_;
    struct CGRect webViewFrame_;
    GIPResourceLoader *loader_;
    Class webViewClass_;
    unsigned int cachePolicy_;
    double timeoutInterval_;
    UIColor *toolbarColor_;
    BOOL clearHistoryOnLoad_;
}

+ (BOOL)URLValidForSafari:(id)fp8;
- (void)setClearHistoryOnLoad:(BOOL)fp8;
- (BOOL)clearHistoryOnLoad;
- (id)toolbarColor;
- (void)setTimeoutInterval:(double)fp8;
- (double)timeoutInterval;
- (void)setCachePolicy:(unsigned int)fp8;
- (unsigned int)cachePolicy;
- (BOOL)webViewLoaded;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setUsePageTitleAsViewTitle:(BOOL)fp8;
- (BOOL)usePageTitleAsViewTitle;
- (void)setToolbar:(id)fp8;
- (id)toolbar;
- (void)setShowsOpenInSafariInToolbar:(BOOL)fp8;
- (BOOL)showsOpenInSafariInToolbar;
- (BOOL)showsToolbar;
- (void)setShowsSpinner:(BOOL)fp8;
- (BOOL)showsSpinner;
- (void)setShowSpinnerInToolbar:(BOOL)fp8;
- (BOOL)showSpinnerInToolbar;
- (void)setAllowBrowserSelection:(BOOL)fp8;
- (BOOL)allowBrowserSelection;
- (void)setShowPromptWhenOpeningSafari:(BOOL)fp8;
- (BOOL)showPromptWhenOpeningSafari;
- (void)setShowErrorPageOnLoadFail:(BOOL)fp8;
- (BOOL)showErrorPageOnLoadFail;
- (void)setRewriteNewWindowLinks:(BOOL)fp8;
- (BOOL)rewriteNewWindowLinks;
- (void)setOpenInSafariURL:(id)fp8;
- (id)openInSafariURL;
- (int)numberOfItemsLoading;
- (void)setInitialRequest:(id)fp8;
- (id)initialRequest;
- (void)setHistory:(id)fp8;
- (id)history;
- (void)setHideToolbarWithoutHistory:(BOOL)fp8;
- (BOOL)hideToolbarWithoutHistory;
- (void)setDetectExternalURLs:(BOOL)fp8;
- (BOOL)detectExternalURLs;
- (id)delegate;
- (void)setCurrentURL:(id)fp8;
- (id)currentURL;
- (void)setCurrentPageTitle:(id)fp8;
- (id)currentPageTitle;
- (void)setToolbarColor:(id)fp8;
- (void)openExternalURL:(id)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)showBrowserSelectionPrompt;
- (void)showOpenInSafariPrompt;
- (void)openURLInSafari:(id)fp8;
- (id)convertURLToChrome:(id)fp8;
- (BOOL)isChromeInstalled;
- (void)displayErrorMessage:(id)fp8 withReload:(BOOL)fp12;
- (void)hideSpinner;
- (void)showSpinner;
- (void)updateSpinnerFrame;
- (id)spinner;
- (void)didReceiveMemoryWarning;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)openInSafari;
- (id)safariURL;
- (void)goForward;
- (void)goBack;
- (void)reload;
- (void)emptyPage;
- (void)callDidExhaustHistoryStack;
- (BOOL)shouldCallDidExhaustHistoryStack;
- (id)getPageTitle;
- (void)addURLToHistory:(id)fp8;
- (void)recordCurrentRequestInHistory;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)loadRequest:(id)fp8;
- (void)loadURL:(id)fp8;
- (void)loadHTML:(id)fp8 baseURL:(id)fp12;
- (id)createWebViewIfNeeded;
- (void)showsOpenInSafariInToolbar:(BOOL)fp8;
- (void)setShowsToolbar:(BOOL)fp8;
- (void)setDelegate:(id)fp8;
- (struct CGRect)toolbarFrame;
- (struct CGRect)webViewFrame;
- (void)setWebViewFrame:(struct CGRect)fp8;
- (void)updateToolbarState;
- (void)setSafariButtonEnabled:(BOOL)fp8;
- (void)setReloadButtonEnabled:(BOOL)fp8;
- (void)setForwardButtonEnabled:(BOOL)fp8;
- (void)setBackButtonEnabled:(BOOL)fp8;
- (void)unloadToolbar;
- (void)loadToolbar;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 loader:(id)fp12 webViewClass:(Class)fp16 clearHistoryOnLoad:(BOOL)fp20;
- (id)initWithDelegate:(id)fp8 loader:(id)fp12 webViewClass:(Class)fp16;
- (id)initWithDelegate:(id)fp8 loader:(id)fp12;
- (id)initWithDelegate:(id)fp8;
- (id)init;

@end

