/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCoding-Protocol.h"

@class NSMutableArray;

@interface GIPWebViewHistory : _AVAudioSessionCategoryPlayback <NSCoding>
{
    NSMutableArray *history_;
    int position_;
    BOOL loading_;
}

- (void)setLoading:(BOOL)fp8;
- (BOOL)loading;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)description;
- (id)currentURL;
- (id)current;
- (id)back;
- (id)forward;
- (BOOL)canGoForward;
- (BOOL)canGoBack;
- (void)pushHTML:(id)fp8 baseURL:(id)fp12;
- (void)pushRequest:(id)fp8;
- (void)addHistoryEntry:(id)fp8;
- (void)clear;
- (void)dealloc;
- (id)init;

@end

