/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GIPWaveformView : _AVAudioSessionCategoryPlayback
{
    float *levelsArray_;
    unsigned int levelsArraySize_;
    unsigned int maxSamples_;
    BOOL scaleToFit_;
    BOOL scroll_;
}

- (void)setMaxSamples:(unsigned int)fp8;
- (unsigned int)maxSamples;
- (void)setScroll:(BOOL)fp8;
- (BOOL)scroll;
- (void)setScaleToFit:(BOOL)fp8;
- (BOOL)scaleToFit;
- (void)reloadView;
- (void)drawRect:(struct CGRect)fp8;
- (struct CGRect)rectForRange:(struct _NSRange)fp8;
- (void)setLevelsArray:(float *)fp8 ofSize:(int)fp12;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

