/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GSKProtoClientParameters : _AVAudioSessionCategoryPlayback
{
    BOOL enableHifiForWifi_;
    double bandwidthEstimatorMeanRttThresholdSecs_;
    double bandwidthEstimatorStdevRttThresholdSecs_;
    double bandwidthEstimatorPacketLossThreshold_;
}

- (void)setBandwidthEstimatorPacketLossThreshold:(double)fp8;
- (double)bandwidthEstimatorPacketLossThreshold;
- (void)setBandwidthEstimatorStdevRttThresholdSecs:(double)fp8;
- (double)bandwidthEstimatorStdevRttThresholdSecs;
- (void)setBandwidthEstimatorMeanRttThresholdSecs:(double)fp8;
- (double)bandwidthEstimatorMeanRttThresholdSecs;
- (void)setEnableHifiForWifi:(BOOL)fp8;
- (BOOL)enableHifiForWifi;

@end

