/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GSKSessionConfig <NSObject>
- (BOOL)startEnvironmentSampling;
- (BOOL)forceHiFi;
- (BOOL)forceLoFi;
- (BOOL)useHiFi;
- (id)clientReportDatabasePath;
- (id)bandwidthEstimatorDatabasePath;
- (id)locale;
- (id)experimentConfigCachePath;
- (id)utteranceDebugDirectory;
- (id)cookie;
- (id)sandboxServerPassword;
- (id)serverURL;
- (id)applicationIdentifier;
@end

