/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GTLQueryProtocol-Protocol.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary;

@interface GTLBatchQuery : _AVAudioSessionCategoryPlayback <GTLQueryProtocol>
{
    NSMutableArray *queries_;
    NSMutableDictionary *requestIDMap_;
    BOOL skipAuthorization_;
    NSDictionary *additionalHTTPHeaders_;
}

+ (id)batchQueryWithQueries:(id)fp8;
+ (id)batchQuery;
- (void)setAdditionalHTTPHeaders:(id)fp8;
- (id)additionalHTTPHeaders;
- (void)setShouldSkipAuthorization:(BOOL)fp8;
- (BOOL)shouldSkipAuthorization;
- (void)addQuery:(id)fp8;
- (id)queries;
- (void)setQueries:(id)fp8;
- (id)queryForRequestID:(id)fp8;
- (void)executionDidStop;
- (id)uploadParameters;
- (BOOL)isBatchQuery;
- (id)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

