/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSDateComponents, NSTimeZone;

@interface GTLDateTime : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSDateComponents *dateComponents_;
    int milliseconds_;
    int offsetSeconds_;
    BOOL isUniversalTime_;
    NSTimeZone *timeZone_;
}

+ (id)dateTimeWithDateComponents:(id)fp8;
+ (id)dateTimeForAllDayWithDate:(id)fp8;
+ (id)dateTimeWithDate:(id)fp8 timeZone:(id)fp12;
+ (id)dateTimeWithRFC3339String:(id)fp8;
- (void)setUniversalTime:(BOOL)fp8;
- (BOOL)isUniversalTime;
- (void)setOffsetSeconds:(int)fp8;
- (int)offsetSeconds;
- (void)setMilliseconds:(int)fp8;
- (int)milliseconds;
- (void)setDateComponents:(id)fp8;
- (id)dateComponents;
- (void)setHasTime:(BOOL)fp8;
- (BOOL)hasTime;
- (void)setFromRFC3339String:(id)fp8;
- (void)setFromDate:(id)fp8 timeZone:(id)fp12;
- (id)RFC3339String;
- (id)stringValue;
- (id)date;
- (id)calendar;
- (void)setTimeZone:(id)fp8;
- (id)timeZone;
- (id)description;
- (BOOL)isEqual:(id)fp8;
- (BOOL)doesDateComponents:(id)fp8 equalDateComponents:(id)fp12;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;

@end

