/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GTLJSONParser : _AVAudioSessionCategoryPlayback
{
}

+ (id)objectWithData:(id)fp8 error:(id *)fp12;
+ (id)objectWithString:(id)fp8 error:(id *)fp12;
+ (id)dataWithObject:(id)fp8 humanReadable:(BOOL)fp12 error:(id *)fp16;
+ (id)stringWithObject:(id)fp8 humanReadable:(BOOL)fp12 error:(id *)fp16;

@end

