/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GTLRuntimeCommon-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSDictionary, NSMutableDictionary;

@interface GTLObject : _AVAudioSessionCategoryPlayback <GTLRuntimeCommon, NSCopying>
{
    NSMutableDictionary *json_;
    NSDictionary *surrogates_;
    NSMutableDictionary *childCache_;
    NSMutableDictionary *userProperties_;
}

+ (BOOL)resolveInstanceMethod:(SEL)fp8;
+ (Class)ancestorClass;
+ (id)arrayPropertyToClassMapForClass:(Class)fp8;
+ (id)propertyToJSONKeyMapForClass:(Class)fp8;
+ (void)initialize;
+ (id)objectForJSON:(id)fp8 defaultClass:(Class)fp12 surrogates:(id)fp16 batchClassMap:(id)fp20;
+ (void)registerObjectClassForKind:(id)fp8;
+ (Class)registeredObjectClassForKind:(id)fp8;
+ (id)allKnownKeys;
+ (id)allDeclaredProperties;
+ (id)nullValue;
+ (id)patchDictionaryForJSON:(id)fp8 fromOriginalJSON:(id)fp12;
+ (id)fieldsElementsForJSON:(id)fp8;
+ (id)fieldsDescriptionForJSON:(id)fp8;
+ (Class)classForAdditionalProperties;
+ (id)arrayPropertyToClassMap;
+ (id)propertyToJSONKeyMap;
+ (id)objectWithJSON:(id)fp8;
+ (id)object;
- (void)setUserProperties:(id)fp8;
- (id)userProperties;
- (void)setSurrogates:(id)fp8;
- (id)surrogates;
- (void)setJSON:(id)fp8;
- (id)JSON;
- (id)description;
- (id)propertyForKey:(id)fp8;
- (void)setProperty:(id)fp8 forKey:(id)fp12;
- (id)userData;
- (void)setUserData:(id)fp8;
- (id)cacheChildForKey:(id)fp8;
- (void)setCacheChild:(id)fp8 forKey:(id)fp12;
- (id)additionalProperties;
- (void)setAdditionalProperty:(id)fp8 forName:(id)fp12;
- (id)additionalPropertyForName:(id)fp8;
- (id)patchObjectFromOriginal:(id)fp8;
- (id)fieldsDescription;
- (id)additionalJSONKeys;
- (id)JSONString;
- (id)JSONValueForKey:(id)fp8;
- (void)setJSONValue:(id)fp8 forKey:(id)fp12;
- (void)dealloc;
- (id)descriptionWithLocale:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;

@end

