/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTLQuery.h"

@interface GTLQueryPlus : GTLQuery
{
}

+ (id)queryForPeopleUnignoreWithUserId:(id)fp8;
+ (id)queryForPeopleUnblockWithUserId:(id)fp8;
+ (id)queryForPeopleSearchWithQuery:(id)fp8;
+ (id)queryForPeopleRemoveFromCircleWithCircleId:(id)fp8 userId:(id)fp12;
+ (id)queryForPeopleListByCircleWithCircleId:(id)fp8;
+ (id)queryForPeopleListByActivityWithActivityId:(id)fp8 collection:(id)fp12;
+ (id)queryForPeopleListWithUserId:(id)fp8 collection:(id)fp12;
+ (id)queryForPeopleIgnoreWithUserId:(id)fp8;
+ (id)queryForPeopleGetWithUserId:(id)fp8;
+ (id)queryForPeopleBlockWithUserId:(id)fp8;
+ (id)queryForPeopleAddToCircleWithCircleId:(id)fp8 userId:(id)fp12;
+ (id)queryForCommentsUpdateWithObject:(id)fp8 commentId:(id)fp12;
+ (id)queryForCommentsRemoveWithCommentId:(id)fp8;
+ (id)queryForCommentsPatchWithObject:(id)fp8 commentId:(id)fp12;
+ (id)queryForCommentsListWithActivityId:(id)fp8;
+ (id)queryForCommentsInsertWithObject:(id)fp8 activityId:(id)fp12;
+ (id)queryForCommentsGetWithCommentId:(id)fp8;
+ (id)queryForCirclesUpdateWithObject:(id)fp8 circleId:(id)fp12;
+ (id)queryForCirclesRemoveWithCircleId:(id)fp8;
+ (id)queryForCirclesPatchWithObject:(id)fp8 circleId:(id)fp12;
+ (id)queryForCirclesListWithUserId:(id)fp8;
+ (id)queryForCirclesInsertWithObject:(id)fp8 userId:(id)fp12;
+ (id)queryForCirclesGetWithCircleId:(id)fp8;
+ (id)queryForAudiencesListWithUserId:(id)fp8;
+ (id)queryForActivitiesUnplusoneWithActivityId:(id)fp8;
+ (id)queryForActivitiesSearchWithQuery:(id)fp8;
+ (id)queryForActivitiesRemoveWithActivityId:(id)fp8;
+ (id)queryForActivitiesPlusoneWithActivityId:(id)fp8;
+ (id)queryForActivitiesListByCircleWithCircleId:(id)fp8;
+ (id)queryForActivitiesListWithUserId:(id)fp8 collection:(id)fp12;
+ (id)queryForActivitiesInsertWithObject:(id)fp8 userId:(id)fp12 uploadParameters:(id)fp16;
+ (id)queryForActivitiesGetWithActivityId:(id)fp8;
+ (id)queryForActivitiesEnableCommentsWithActivityId:(id)fp8;
+ (id)queryForActivitiesDisableCommentsWithActivityId:(id)fp8;

@end

