/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface GTLRuntimeCommon : _AVAudioSessionCategoryPlayback
{
}

+ (BOOL)resolveInstanceMethod:(SEL)fp8 onClass:(Class)fp12;
+ (BOOL)getStoredDispatchForClass:(Class)fp8 selector:(SEL)fp12 returnClass:(Class *)fp16 containedClass:(Class *)fp20 jsonKey:(id *)fp24;
+ (void)setStoredDispatchForClass:(Class)fp8 selector:(SEL)fp12 returnClass:(Class)fp16 containedClass:(Class)fp20 jsonKey:(id)fp24;
+ (id)jsonFromAPIObject:(id)fp8 expectedClass:(Class)fp12 isCacheable:(char *)fp16;
+ (id)objectFromJSON:(id)fp8 defaultClass:(Class)fp12 surrogates:(id)fp16 isCacheable:(char *)fp20;

@end

