/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GTMFetcherAuthorizationProtocol <NSObject>
- (id)userEmail;
- (BOOL)isAuthorizedRequest:(id)fp8;
- (BOOL)isAuthorizingRequest:(id)fp8;
- (void)stopAuthorization;
- (void)authorizeRequest:(id)fp8 delegate:(id)fp12 didFinishSelector:(SEL)fp16;
@end

