/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSStreamDelegate-Protocol.h"

@class NSArray, NSData, NSInputStream;

@interface GTMGatherInputStream : _AVAudioSessionCategoryPlayback <NSStreamDelegate>
{
    NSArray *dataArray_;
    unsigned int arrayIndex_;
    long long dataOffset_;
    id delegate_;
    NSInputStream *dummyStream_;
    NSData *dummyData_;
}

+ (void)forwardInvocation:(id)fp8;
+ (id)methodSignatureForSelector:(SEL)fp8;
+ (id)streamWithArray:(id)fp8;
- (void)forwardInvocation:(id)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (id)streamError;
- (unsigned int)streamStatus;
- (void)removeFromRunLoop:(id)fp8 forMode:(id)fp12;
- (void)scheduleInRunLoop:(id)fp8 forMode:(id)fp12;
- (BOOL)setProperty:(id)fp8 forKey:(id)fp12;
- (id)propertyForKey:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)stream:(id)fp8 handleEvent:(unsigned int)fp12;
- (void)close;
- (void)open;
- (BOOL)hasBytesAvailable;
- (BOOL)getBuffer:(char **)fp8 length:(unsigned int *)fp12;
- (int)read:(char *)fp8 maxLength:(unsigned int)fp12;
- (void)dealloc;
- (id)initWithArray:(id)fp8;

@end

