/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GTMHTTPFetcherServiceProtocol <NSObject>
- (BOOL)isDelayingFetcher:(id)fp8;
- (id)fetcherWithRequest:(id)fp8;
- (void)fetcherDidStop:(id)fp8;
- (BOOL)fetcherShouldBeginFetching:(id)fp8;
@end

