/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GTMHTTPFetcherServiceProtocol-Protocol.h"

@class GTMHTTPFetchHistory, NSArray, NSMutableDictionary, NSString, NSURLCredential;

@interface GTMHTTPFetcherService : _AVAudioSessionCategoryPlayback <GTMHTTPFetcherServiceProtocol>
{
    NSMutableDictionary *delayedHosts_;
    NSMutableDictionary *runningHosts_;
    unsigned int maxRunningFetchersPerHost_;
    GTMHTTPFetchHistory *fetchHistory_;
    NSArray *runLoopModes_;
    NSString *userAgent_;
    double timeout_;
    NSURLCredential *credential_;
    NSURLCredential *proxyCredential_;
    int cookieStorageMethod_;
    BOOL shouldFetchInBackground_;
    id <GTMFetcherAuthorizationProtocol> authorizer_;
}

- (void)setFetchHistory:(id)fp8;
- (id)fetchHistory;
- (void)setShouldFetchInBackground:(BOOL)fp8;
- (BOOL)shouldFetchInBackground;
- (void)setCookieStorageMethod:(int)fp8;
- (int)cookieStorageMethod;
- (void)setProxyCredential:(id)fp8;
- (id)proxyCredential;
- (void)setCredential:(id)fp8;
- (id)credential;
- (void)setRunLoopModes:(id)fp8;
- (id)runLoopModes;
- (void)setTimeout:(double)fp8;
- (double)timeout;
- (void)setUserAgent:(id)fp8;
- (id)userAgent;
- (void)setMaxRunningFetchersPerHost:(unsigned int)fp8;
- (unsigned int)maxRunningFetchersPerHost;
- (void)detachAuthorizer;
- (void)setAuthorizer:(id)fp8;
- (id)authorizer;
- (void)setDelayedHosts:(id)fp8;
- (id)delayedHosts;
- (void)setRunningHosts:(id)fp8;
- (id)runningHosts;
- (void)waitForCompletionOfAllFetchersWithTimeout:(double)fp8;
- (void)clearHistory;
- (void)clearETaggedDataCache;
- (BOOL)shouldRememberETags;
- (void)setShouldRememberETags:(BOOL)fp8;
- (unsigned int)ETaggedDataCacheCapacity;
- (void)setETaggedDataCacheCapacity:(unsigned int)fp8;
- (BOOL)shouldCacheETaggedData;
- (void)setShouldCacheETaggedData:(BOOL)fp8;
- (void)stopAllFetchers;
- (unsigned int)numberOfDelayedFetchers;
- (unsigned int)numberOfRunningFetchers;
- (unsigned int)numberOfFetchers;
- (void)fetcherDidStop:(id)fp8;
- (void)stopFetcher:(id)fp8;
- (void)stopFetcherOnCurrentThread:(id)fp8;
- (void)startFetcher:(id)fp8;
- (void)startFetcherOnCurrentThread:(id)fp8;
- (BOOL)fetcherShouldBeginFetching:(id)fp8;
- (BOOL)isDelayingFetcher:(id)fp8;
- (void)addDelayedFetcher:(id)fp8 forHost:(id)fp12;
- (void)addRunningFetcher:(id)fp8 forHost:(id)fp12;
- (id)fetcherWithURLString:(id)fp8;
- (id)fetcherWithURL:(id)fp8;
- (id)fetcherWithRequest:(id)fp8;
- (id)fetcherWithRequest:(id)fp8 fetcherClass:(Class)fp12;
- (void)dealloc;
- (id)init;

@end

