/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMHTTPFetcher.h"

@interface GTMHTTPFetcher (GTMHTTPFetcherLoggingUtilities)
+ (id)stringWithJSONObject:(id)fp8;
+ (id)JSONObjectWithData:(id)fp8;
+ (id)headersStringForDictionary:(id)fp8;
+ (id)snipSubstringOfString:(id)fp8 betweenStartString:(id)fp12 endString:(id)fp16;
+ (BOOL)createSymbolicLinkAtPath:(id)fp8 withDestinationPath:(id)fp12;
+ (BOOL)removeItemAtPath:(id)fp8;
+ (BOOL)makeDirectoryUpToPath:(id)fp8;
+ (BOOL)fileOrDirExistsAtPath:(id)fp8;
- (void)inputStream:(id)fp8 readIntoBuffer:(void *)fp12 length:(unsigned int)fp16;
@end

