/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMHTTPFetcher.h"

@interface GTMHTTPFetcher (GTMHTTPFetcherLogging)
+ (id)loggingDateStamp;
+ (void)setLoggingDateStamp:(id)fp8;
+ (id)loggingProcessName;
+ (void)setLoggingProcessName:(id)fp8;
+ (BOOL)isLoggingToFileEnabled;
+ (void)setLoggingToFileEnabled:(BOOL)fp8;
+ (BOOL)isLoggingEnabled;
+ (void)setLoggingEnabled:(BOOL)fp8;
+ (id)loggingDirectory;
+ (void)setLoggingDirectory:(id)fp8;
- (BOOL)logCapturePostStream;
- (void)logFetchWithError:(id)fp8;
- (id)stringFromStreamData:(id)fp8 contentType:(id)fp12;
- (void)setupStreamLogging;
- (id)formattedStringFromData:(id)fp8 contentType:(id)fp12 JSON:(id *)fp16;
@end

