/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GTMLogFilter-Protocol.h"

@class NSIndexSet;

@interface GTMLogAllowedLevelFilter : _AVAudioSessionCategoryPlayback <GTMLogFilter>
{
    NSIndexSet *allowedLevels_;
}

- (BOOL)filterAllowsMessage:(id)fp8 level:(int)fp12;
- (void)dealloc;
- (id)init;
- (id)initWithAllowedLevels:(id)fp8;

@end

