/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GTMFetcherAuthorizationProtocol-Protocol.h"

@class GTMHTTPFetcher, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSURL;

@interface GTMOAuth2Authentication : _AVAudioSessionCategoryPlayback <GTMFetcherAuthorizationProtocol>
{
    NSString *clientID_;
    NSString *clientSecret_;
    NSString *redirectURI_;
    NSMutableDictionary *parameters_;
    NSURL *tokenURL_;
    NSDate *expirationDate_;
    NSDictionary *additionalTokenRequestParameters_;
    GTMHTTPFetcher *refreshFetcher_;
    NSMutableArray *authorizationQueue_;
    id <GTMHTTPFetcherServiceProtocol> fetcherService_;
    Class parserClass_;
    BOOL shouldAuthorizeAllRequests_;
    id userData_;
    NSMutableDictionary *properties_;
}

+ (id)scopeWithStrings:(id)fp8;
+ (id)dictionaryWithResponseData:(id)fp8;
+ (id)dictionaryWithResponseString:(id)fp8;
+ (id)unencodedOAuthParameterForString:(id)fp8;
+ (void)invokeDelegate:(id)fp8 selector:(SEL)fp12 object:(id)fp16 object:(id)fp20 object:(id)fp24;
+ (id)encodedQueryParametersForDictionary:(id)fp8;
+ (id)encodedOAuthValueForString:(id)fp8;
+ (id)authenticationWithServiceProvider:(id)fp8 tokenURL:(id)fp12 redirectURI:(id)fp16 clientID:(id)fp20 clientSecret:(id)fp24;
- (void)setAuthorizationQueue:(id)fp8;
- (id)authorizationQueue;
- (void)setProperties:(id)fp8;
- (id)properties;
- (void)setUserData:(id)fp8;
- (id)userData;
- (void)setShouldAuthorizeAllRequests:(BOOL)fp8;
- (BOOL)shouldAuthorizeAllRequests;
- (void)setParserClass:(Class)fp8;
- (Class)parserClass;
- (void)setFetcherService:(id)fp8;
- (id)fetcherService;
- (void)setRefreshFetcher:(id)fp8;
- (id)refreshFetcher;
- (void)setAdditionalTokenRequestParameters:(id)fp8;
- (id)additionalTokenRequestParameters;
- (void)setExpirationDate:(id)fp8;
- (id)expirationDate;
- (void)setTokenURL:(id)fp8;
- (id)tokenURL;
- (void)setParameters:(id)fp8;
- (id)parameters;
- (void)setRedirectURI:(id)fp8;
- (id)redirectURI;
- (void)setClientSecret:(id)fp8;
- (id)clientSecret;
- (void)setClientID:(id)fp8;
- (id)clientID;
- (id)propertyForKey:(id)fp8;
- (void)setProperty:(id)fp8 forKey:(id)fp12;
- (void)setUserEmailIsVerified:(id)fp8;
- (id)userEmailIsVerified;
- (void)setUserEmail:(id)fp8;
- (id)userEmail;
- (void)setServiceProvider:(id)fp8;
- (id)serviceProvider;
- (void)updateExpirationDate;
- (void)setExpiresIn:(id)fp8;
- (id)expiresIn;
- (void)setScope:(id)fp8;
- (id)scope;
- (void)setTokenType:(id)fp8;
- (id)tokenType;
- (void)setErrorString:(id)fp8;
- (id)errorString;
- (void)setAssertion:(id)fp8;
- (id)assertion;
- (void)setCode:(id)fp8;
- (id)code;
- (void)setRefreshToken:(id)fp8;
- (id)refreshToken;
- (void)setAccessToken:(id)fp8;
- (id)accessToken;
- (void)reset;
- (BOOL)primeForRefresh;
- (id)persistenceResponseString;
- (void)setKeysForPersistenceResponseString:(id)fp8;
- (void)notifyFetchIsRunning:(BOOL)fp8 fetcher:(id)fp12 type:(id)fp16;
- (void)tokenFetcher:(id)fp8 finishedWithData:(id)fp12 error:(id)fp16;
- (id)beginTokenFetchWithDelegate:(id)fp8 didFinishSelector:(SEL)fp12;
- (id)userAgent;
- (void)waitForCompletionWithTimeout:(double)fp8;
- (BOOL)shouldRefreshAccessToken;
- (BOOL)canAuthorize;
- (BOOL)authorizeRequest:(id)fp8;
- (void)invokeCallbackArgs:(id)fp8;
- (BOOL)authorizeRequestImmediateArgs:(id)fp8;
- (void)stopAuthorization;
- (BOOL)isAuthorizedRequest:(id)fp8;
- (BOOL)isAuthorizingRequest:(id)fp8;
- (void)auth:(id)fp8 finishedRefreshWithFetcher:(id)fp12 error:(id)fp16;
- (BOOL)authorizeRequestArgs:(id)fp8;
- (void)authorizeRequest:(id)fp8 delegate:(id)fp12 didFinishSelector:(SEL)fp16;
- (void)authorizeRequest:(id)fp8 completionHandler:(id)fp(null);
- (id)dictionaryWithJSONData:(id)fp8;
- (void)setKeysForResponseJSONData:(id)fp8;
- (void)setKeysForResponseString:(id)fp8;
- (void)setKeysForResponseDictionary:(id)fp8;
- (void)dealloc;
- (id)description;
- (id)init;

@end

