/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSError, NSMutableURLRequest, NSThread;

@interface GTMOAuth2AuthorizationArgs : _AVAudioSessionCategoryPlayback
{
    NSMutableURLRequest *request_;
    id delegate_;
    SEL sel_;
    id completionHandler_;
    NSThread *thread_;
    NSError *error_;
}

+ (id)argsWithRequest:(id)fp8 delegate:(id)fp12 selector:(SEL)fp16 completionHandler:(id)fp20 thread:(id)fp24;
- (void)setError:(id)fp8;
- (id)error;
- (void)setThread:(id)fp8;
- (id)thread;
- (void)setCompletionHandler:(id)fp8;
- (id)completionHandler;
- (void)setSelector:(SEL)fp8;
- (SEL)selector;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setRequest:(id)fp8;
- (id)request;
- (void)dealloc;

@end

