/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSStreamDelegate-Protocol.h"

@class NSArray, NSInputStream, NSThread;

@interface GTMReadMonitorInputStream : _AVAudioSessionCategoryPlayback <NSStreamDelegate>
{
    NSInputStream *inputStream_;
    NSThread *thread_;
    NSArray *runLoopModes_;
    id readDelegate_;
    SEL readSelector_;
}

+ (id)inputStreamWithStream:(id)fp8;
+ (void)forwardInvocation:(id)fp8;
+ (id)methodSignatureForSelector:(SEL)fp8;
- (void)setRunLoopModes:(id)fp8;
- (id)runLoopModes;
- (void)setReadSelector:(SEL)fp8;
- (SEL)readSelector;
- (void)setReadDelegate:(id)fp8;
- (id)readDelegate;
- (id)streamError;
- (unsigned int)streamStatus;
- (void)removeFromRunLoop:(id)fp8 forMode:(id)fp12;
- (void)scheduleInRunLoop:(id)fp8 forMode:(id)fp12;
- (BOOL)setProperty:(id)fp8 forKey:(id)fp12;
- (id)propertyForKey:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)close;
- (void)open;
- (BOOL)hasBytesAvailable;
- (BOOL)getBuffer:(char **)fp8 length:(unsigned int *)fp12;
- (void)invokeReadSelectorWithBuffer:(id)fp8;
- (int)read:(char *)fp8 maxLength:(unsigned int)fp12;
- (void)dealloc;
- (id)init;
- (id)initWithStream:(id)fp8;
- (void)forwardInvocation:(id)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;

@end

