/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface MASFNotificationSubscription : _AVAudioSessionCategoryPlayback
{
    NSString *notificationName_;
    int notificationMode_;
    NSString *soundFile_;
}

+ (id)subscriptionWithName:(id)fp8 mode:(int)fp12;
- (void)setSoundFile:(id)fp8;
- (id)soundFile;
- (void)setNotificationMode:(int)fp8;
- (int)notificationMode;
- (void)setNotificationName:(id)fp8;
- (id)notificationName;
- (id)notificationModeString;
- (void)dealloc;
- (id)initWithName:(id)fp8 mode:(int)fp12;

@end

