/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class MASFUserIdentification, NSArray, NSDate, NSString;

@interface MASFUserServicePreferences : _AVAudioSessionCategoryPlayback
{
    MASFUserIdentification *userIdentity_;
    NSArray *servicePreferences_;
    NSString *timeZone_;
    NSDate *startTime_;
    NSDate *endTime_;
    NSString *languageTag_;
}

- (void)setLanguageTag:(id)fp8;
- (id)languageTag;
- (void)setEndTime:(id)fp8;
- (id)endTime;
- (void)setStartTime:(id)fp8;
- (id)startTime;
- (void)setUserIdentity:(id)fp8;
- (id)userIdentity;
- (void)setTimeZone:(id)fp8;
- (id)timeZone;
- (void)setServicePreferences:(id)fp8;
- (id)servicePreferences;
- (id)description;
- (void)dealloc;
- (id)initWithUserIdentity:(id)fp8 servicePreferences:(id)fp12 timeZone:(id)fp16 startTime:(id)fp20 endTime:(id)fp24 languageTag:(id)fp28;

@end

