/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface MASFRequest : _AVAudioSessionCategoryPlayback
{
    struct __MASFRequestPrivate *cpp_;
    id target_;
    SEL onSuccess_;
    SEL onError_;
    id successBlock_;
    id errorBlock_;
}

- (void)releaseHandlers;
- (void)invokeSuccess:(id)fp8;
- (void)invokeError:(int)fp8;
- (void)onRequestUpdated:(id)fp8;
- (void)onRequestFailed:(id)fp8;
- (void)onRequestComplete:(id)fp8;
- (void)beginRequest;
- (void)dealloc;
- (id)initWithRequest:(id)fp8 serviceURI:(id)fp12 successBlock:(id)fp(null) errorBlock:(void)fp16;
- (id)initWithRequest:(id)fp8 serviceURI:(id)fp12 target:(id)fp16 onSuccess:(SEL)fp20 onError:(SEL)fp24;
- (id)initWithRequest:(id)fp8 serviceURI:(id)fp12;

@end

