/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface MASFReverseGeocodeRequest : _AVAudioSessionCategoryPlayback
{
    struct __MASFReverseGeocodeRequestPrivate *cpp_;
    id <MASFReverseGeocodeRequestObserver> delegate_;
    double latitude_;
    double longitude_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)dumpFeature:(const struct GLocation *)fp8;
- (void)onRequestUpdated:(id)fp8;
- (void)onRequestFailed:(id)fp8;
- (id)countryFromLocation:(const struct GLocation *)fp8;
- (id)postCodeFromLocation:(const struct GLocation *)fp8;
- (id)cityFromLocation:(const struct GLocation *)fp8;
- (id)featureNameFromLocation:(const struct GLocation *)fp8 ofType:(int)fp12;
- (const struct GLocation *)locationFromResponse:(const struct GLocReply *)fp8;
- (void)onRequestComplete:(id)fp8;
- (void)beginRequest;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 latitude:(double)fp12 longitude:(double)fp20;

@end

