/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MASFServicePreference.h"

@interface MASFServicePreference (CPP)
- (void)copyInto:(struct ServicePreference *)fp8;
- (struct ServicePreference *)cppValue;
- (id)initWithServicePreference:(const struct ServicePreference *)fp8;
@end

