/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface MASFNotificationSetSettingsRequest : _AVAudioSessionCategoryPlayback
{
    struct __MASFNotificationSetSettingsRequestPrivate *cpp_;
    id <MASFNotificationSetSettingsRequestObserver> delegate_;
    id userData_;
}

- (void)setUserData:(id)fp8;
- (id)userData;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)onRequestUpdated:(id)fp8;
- (void)onRequestFailed:(id)fp8;
- (void)onRequestComplete:(id)fp8;
- (void)beginRequest;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 userPreferences:(id)fp12 deviceToken:(id)fp16 deviceName:(id)fp20 applicationId:(id)fp24;

@end

