/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface MASFGooglePlacesEventLogRequest : _AVAudioSessionCategoryPlayback
{
    struct __MASFGooglePlacesEventLogRequestPrivate *cpp_;
    id <MASFGooglePlacesEventLogRequestObserver> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)onRequestUpdated:(id)fp8;
- (void)onRequestFailed:(id)fp8;
- (void)onRequestComplete:(id)fp8;
- (void)cancelRequest;
- (void)beginRequest;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 action:(int)fp12 currentView:(int)fp16 nextView:(int)fp20 rating:(int)fp24 error:(int)fp28 durationMs:(int)fp32 resultPosition:(int)fp36 locationAccuracy:(int)fp40 locationDelta:(int)fp44 latSpanDegreesE6:(int)fp48 longSpanDegreesE6:(int)fp52 timestampMs:(long long)fp56 language:(id)fp64 connectionType:(int)fp68 category:(id)fp72 hasNegativeJustifications:(BOOL)fp76 hasPositiveJustifications:(BOOL)fp80 reviewSource:(id)fp84 isLoggedIn:(BOOL)fp88 shouldFlush:(_Bool)fp92;

@end

