/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString;

@interface MASFNotification : _AVAudioSessionCategoryPlayback
{
    int service_;
    NSString *text_;
    int count_;
    NSString *url_;
}

- (void)setUrl:(id)fp8;
- (id)url;
- (void)setText:(id)fp8;
- (id)text;
- (void)setService:(int)fp8;
- (int)service;
- (void)setCount:(int)fp8;
- (int)count;
- (void)dealloc;
- (id)description;

@end

