/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PBArray.h"

@interface PBArray (ExtensionField)
+ (int)arrayTypeForPBType:(int)fp8;
- (id)initWithArray:(id)fp8 pbValueType:(int)fp12;
- (CDAnonymousUnion1)valueAtIndex:(unsigned int)fp8;
@end

