/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "PBExtensionField-Protocol.h"

@class PBDescriptor, PBExtensionDescriptor;

@interface PBConcreteExtensionField : _AVAudioSessionCategoryPlayback <PBExtensionField>
{
    int type_;
    int fieldNumber_;
    CDAnonymousUnion2 defaultPBValue_;
    Class messageOrGroupClass_;
    BOOL isRepeated_;
    BOOL isPacked_;
    BOOL isMessageSetWireFormat_;
    PBExtensionDescriptor *descriptor_;
    PBDescriptor *containingType_;
}

- (id)descriptor;
- (id)containingType;
- (BOOL)isRepeated;
- (int)fieldNumber;
- (void)mergeFromCodedInputStream:(id)fp8 unknownFields:(id)fp12 extensionRegistry:(id)fp16 builder:(id)fp20 tag:(int)fp24;
- (id)readSingleValueFromCodedInputStream:(id)fp8 extensionRegistry:(id)fp12;
- (void)mergeMessageSetExtentionFromCodedInputStream:(id)fp8 unknownFields:(id)fp12;
- (id)description;
- (unsigned int)computeSerializedSizeIncludingTag:(id)fp8;
- (unsigned int)computePBSerializedSizesIncludingTags:(id)fp8;
- (void)writeValue:(id)fp8 includingTagToCodedOutputStream:(id)fp12;
- (void)writePBValues:(id)fp8 includingTagsToCodedOutputStream:(id)fp12;
- (CDAnonymousUnion1)defaultPBValue;
- (id)defaultValue;
- (unsigned int)computePBSerializedSizeIncludingTag:(CDAnonymousUnion1)fp8;
- (unsigned int)computePBSerializedSizeNoTag:(CDAnonymousUnion1)fp8;
- (void)writePBValue:(CDAnonymousUnion1)fp8 noTagToCodedOutputStream:(id)fp16;
- (void)writePBValue:(CDAnonymousUnion1)fp8 includingTagToCodedOutputStream:(id)fp16;
- (int)wireType;
- (void)dealloc;
- (id)initWithDescription:(struct PBExtensionDescription *)fp8;

@end

