/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "PBDescriptor-Protocol.h"

@class PBArray;

@interface PBDescriptor : _AVAudioSessionCategoryPlayback <PBDescriptor>
{
    Class messageClass_;
    Class builderClass_;
    PBArray *fields_;
    PBArray *enums_;
    PBArray *extensions_;
    unsigned long storageSize_;
    BOOL wireFormat_;
    PBArray *extensionRanges_;
}

+ (id)allocDescriptorForClass:(Class)fp8 rootClass:(Class)fp12 fields:(CDAnonymousStruct5 *)fp16 fieldCount:(unsigned int)fp20 ranges:(CDAnonymousStruct2 *)fp24 rangeCount:(unsigned int)fp28 storageSize:(unsigned long)fp32 wireFormat:(BOOL)fp36;
- (BOOL)isWireFormat;
- (unsigned long)storageSize;
- (id)extensionRanges;
- (id)extensions;
- (id)enums;
- (id)fields;
- (Class)builderClass;
- (Class)messageClass;
- (id)extensionWithName:(id)fp8;
- (id)extensionWithNumber:(unsigned int)fp8;
- (id)enumWithName:(id)fp8;
- (id)enumWithNumber:(unsigned int)fp8;
- (id)fieldWithName:(id)fp8;
- (id)fieldWithNumber:(unsigned int)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)name;
- (void)dealloc;
- (id)initWithClass:(Class)fp8 builderClass:(Class)fp12 fields:(id)fp16 enums:(id)fp20 extensions:(id)fp24 extensionRanges:(id)fp28 storageSize:(unsigned long)fp32 wireFormat:(BOOL)fp36;

@end

