/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "PBEnumDescriptor-Protocol.h"

@class NSString;

@interface PBEnumDescriptor : _AVAudioSessionCategoryPlayback <PBEnumDescriptor>
{
    NSString *name_;
    unsigned int number_;
}

- (unsigned int)number;
- (id)name;

@end

