/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "PBExtensionDescriptor-Protocol.h"

@interface PBExtensionDescriptor : _AVAudioSessionCategoryPlayback <PBExtensionDescriptor>
{
    unsigned int number_;
    int type_;
    unsigned int options_;
    Class msgClass_;
}

- (Class)msgClass;
- (int)type;
- (unsigned int)number;
- (BOOL)isMessage;
- (BOOL)isPackable;
- (BOOL)isRepeated;
- (id)initWithExtensionDescription:(struct PBExtensionDescription *)fp8;

@end

