/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class PBMutableArray;

@interface PBField : _AVAudioSessionCategoryPlayback
{
    int number_;
    PBMutableArray *mutableVarintList_;
    PBMutableArray *mutableFixed32List_;
    PBMutableArray *mutableFixed64List_;
    PBMutableArray *mutableLengthDelimitedList_;
    PBMutableArray *mutableGroupList_;
}

- (int)number;
- (id)groupList;
- (id)lengthDelimitedList;
- (id)fixed64List;
- (id)fixed32List;
- (id)varintList;
- (id)description;
- (unsigned int)serializedSizeAsMessageSetExtension;
- (void)writeAsMessageSetExtensionToOutput:(id)fp8;
- (unsigned int)serializedSize;
- (void)writeToOutput:(id)fp8;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;

@end

