/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PBField.h"

@interface PBMutableField : PBField
{
}

- (void)addGroup:(id)fp8;
- (void)addLengthDelimited:(id)fp8;
- (void)addFixed64:(unsigned long long)fp8;
- (void)addFixed32:(unsigned int)fp8;
- (void)addVarint:(unsigned long long)fp8;
- (void)mergeFromField:(id)fp8;
- (id)initWithNumber:(int)fp8;

@end

