/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PBArray.h"

@interface PBMutableArray : PBArray
{
    unsigned long _mutationCount;
}

+ (id)arrayWithValueType:(int)fp8 capacity:(unsigned int)fp12;
- (void)removeAllValues;
- (void)appendValues:(const void *)fp8 valueType:(int)fp12 count:(unsigned int)fp16;
- (void)appendArray:(id)fp8;
- (void)replaceDoubleAtIndex:(unsigned int)fp8 withDouble:(double)fp12;
- (void)replaceFloatAtIndex:(unsigned int)fp8 withFloat:(float)fp12;
- (void)replaceUInt64AtIndex:(unsigned int)fp8 withUInt64:(unsigned long long)fp12;
- (void)replaceInt64AtIndex:(unsigned int)fp8 withInt64:(long long)fp12;
- (void)replaceUInt32AtIndex:(unsigned int)fp8 withUInt32:(unsigned int)fp12;
- (void)replaceInt32AtIndex:(unsigned int)fp8 withInt32:(int)fp12;
- (void)replaceBoolAtIndex:(unsigned int)fp8 withBool:(BOOL)fp12;
- (void)replaceObjectAtIndex:(unsigned int)fp8 withObject:(id)fp12;
- (void)addDouble:(double)fp8;
- (void)addFloat:(float)fp8;
- (void)addUInt64:(unsigned long long)fp8;
- (void)addInt64:(long long)fp8;
- (void)addUInt32:(unsigned int)fp8;
- (void)addInt32:(int)fp8;
- (void)addBool:(BOOL)fp8;
- (void)addObject:(id)fp8;
- (void)ensureAdditionalCapacity:(unsigned int)fp8;
- (void)enumerateInt32sUsingBlock:(id)fp(null);
- (void)enumerateObjectsUsingBlock:(id)fp(null);
- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct6 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithValueType:(int)fp8 capacity:(unsigned int)fp12;

@end

