/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"
#import "NSFastEnumeration-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@class NSMutableDictionary;

@interface PBUnknownFieldSet : _AVAudioSessionCategoryPlayback <NSFastEnumeration, NSCopying, NSMutableCopying>
{
    NSMutableDictionary *fields_;
}

- (id)data;
- (unsigned int)serializedSizeAsMessageSet;
- (void)writeAsMessageSetTo:(id)fp8;
- (unsigned int)serializedSize;
- (id)description;
- (void)writeToCodedOutputStream:(id)fp8;
- (unsigned int)countOfFields;
- (id)getField:(int)fp8;
- (BOOL)hasField:(int)fp8;
- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct6 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;
- (id)mutableCopyWithZone:(struct _NSZone *)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithFields:(id)fp8;

@end

