/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PBUnknownFieldSet.h"

@interface PBUnknownFieldSet_Builder : PBUnknownFieldSet
{
}

+ (BOOL)isFieldTag:(int)fp8;
- (void)mergeFromCodedInputStream:(id)fp8;
- (BOOL)mergeFieldFrom:(int)fp8 input:(id)fp12;
- (void)mergeVarintField:(int)fp8 value:(int)fp12;
- (void)mergeFromData:(id)fp8;
- (void)mergeUnknownFields:(id)fp8;
- (void)mergeField:(id)fp8;
- (id)getFieldBuilder:(int)fp8 create:(BOOL)fp12;
- (void)addField:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithFields:(id)fp8;

@end

