/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface ShareboxNavigationBar : _AVAudioSessionCategoryPlayback
{
}

+ (id)navigationTitleWithTitle:(id)fp8;
+ (id)setStyle:(int)fp8 button:(id)fp12 target:(id)fp16 action:(SEL)fp20;
+ (id)buttonWithTitle:(id)fp8 ofType:(int)fp12 target:(id)fp16 action:(SEL)fp20;
+ (id)navigationButtonWithTitle:(id)fp8 ofType:(int)fp12 target:(id)fp16 action:(SEL)fp20;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

