/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton, UIImageView, UILabel;

@interface ShareboxOptionsView : _AVAudioSessionCategoryPlayback
{
    UILabel *textLabel_;
    int style_;
    UIImageView *actionImageView_;
    UIButton *actionButton_;
}

- (id)actionImageView;
- (id)textLabel;
- (void)drawRect:(struct CGRect)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 text:(id)fp12 target:(id)fp16 selector:(SEL)fp20;

@end

