/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SHKSharer.h"

#import "FBDialogDelegate-Protocol.h"
#import "FBRequestDelegate-Protocol.h"
#import "FBSessionDelegate-Protocol.h"
#import "SHKFormControllerLargeTextFieldDelegate-Protocol.h"

@interface SHKFacebook : SHKSharer <FBSessionDelegate, FBDialogDelegate, FBRequestDelegate, SHKFormControllerLargeTextFieldDelegate>
{
}

+ (void)logout;
+ (BOOL)canGetUserInfo;
+ (BOOL)canShareOffline;
+ (BOOL)canShareImage;
+ (BOOL)canShareText;
+ (BOOL)canShareURL;
+ (id)sharerTitle;
+ (BOOL)handleOpenURL:(id)fp8;
+ (id)storedImage:(id)fp8;
+ (id)storedImagePath:(id)fp8;
+ (void)flushAccessToken;
+ (id)facebook;
- (void)sendForm:(id)fp8;
- (void)showFacebookForm;
- (void)show;
- (void)request:(id)fp8 didFailWithError:(id)fp12;
- (void)request:(id)fp8 didLoad:(id)fp12;
- (void)requestLoading:(id)fp8;
- (void)fbSessionInvalidated;
- (void)fbDidLogout;
- (void)fbDidExtendToken:(id)fp8 expiresAt:(id)fp12;
- (void)fbDidNotLogin:(BOOL)fp8;
- (void)fbDidLogin;
- (BOOL)dialog:(id)fp8 shouldOpenURLInExternalBrowser:(id)fp12;
- (void)dialog:(id)fp8 didFailWithError:(id)fp12;
- (void)dialogDidCancel:(id)fp8;
- (void)dialogCompleteWithUrl:(id)fp8;
- (void)dialogDidNotComplete:(id)fp8;
- (void)dialogDidComplete:(id)fp8;
- (BOOL)send;
- (void)authFinished:(id)fp8;
- (void)promptAuthorization;
- (BOOL)isAuthorized;
- (BOOL)shouldAutoShare;
- (void)dealloc;

@end

