/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SHKSharer.h"

#import "ShareboxDelegate-Protocol.h"

@class NSString, ShareboxController;

@interface SHKGooglePlus : SHKSharer <ShareboxDelegate>
{
    ShareboxController *controller_;
    NSString *applicationName_;
}

+ (BOOL)canShare;
+ (BOOL)requiresAuthentication;
+ (BOOL)shareRequiresInternetConnection;
+ (BOOL)canShareFile;
+ (BOOL)canShareImage;
+ (BOOL)canShareURL;
+ (BOOL)canShareText;
+ (id)sharerTitle;
- (void)setApplicationName:(id)fp8;
- (id)applicationName;
- (void)shareboxDidStartPost:(id)fp8;
- (void)shareboxDidCancel:(id)fp8;
- (void)sharebox:(id)fp8 didAbortWithError:(id)fp12;
- (void)sharebox:(id)fp8 didFinishWithError:(id)fp12;
- (BOOL)send;
- (BOOL)shouldAutoShare;
- (void)dealloc;

@end

