/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SHKSharer.h"

@class UIViewController;

@interface SHKiOS5Twitter : SHKSharer
{
    UIViewController *currentTopViewController;
}

+ (id)sharerId;
+ (id)sharerTitle;
- (void)setCurrentTopViewController:(id)fp8;
- (id)currentTopViewController;
- (void)sharerCancelledSending:(id)fp8;
- (void)sharerFinishedSending:(id)fp8;
- (void)presentUI;
- (void)callUI:(id)fp8;
- (void)share;
- (void)dealloc;

@end

