/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TBXML.h"

@interface TBXML (Private)
+ (id)errorWithCode:(int)fp8 userInfo:(id)fp12;
+ (id)errorWithCode:(int)fp8;
+ (id)errorTextForCode:(int)fp8;
- (struct _TBXMLAttribute *)nextAvailableAttribute;
- (struct _TBXMLElement *)nextAvailableElement;
- (void)dealloc;
- (void)decodeBytes;
- (void)allocateBytesOfLength:(long)fp8 error:(id *)fp12;
@end

