/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface UbertokenFetcher : _AVAudioSessionCategoryPlayback
{
}

+ (id)loginScope;
- (id)mergeSessionURLWithContinueURL:(id)fp8 ubertoken:(id)fp12 source:(id)fp16;
- (void)startFetchingUbertokenWithSuccessHandler:(id)fp(null) errorHandler:(void)fp8 auth:(id)fp(null);
- (id)authHeaderForOAuth:(id)fp8;

@end

