/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPad.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, UIButton, YTAccountView_iPad, YTTitleBar_iPad;

@interface YTAccountViewController_iPad : YTBaseViewController_iPad <UITableViewDataSource, UITableViewDelegate>
{
    YTAccountView_iPad *accountView_;
    YTTitleBar_iPad *titleBar_;
    NSArray *accountViewTitles_;
    int selectedRow_;
    UIButton *signOutButton_;
}

- (void)didPressLogoutButton;
- (void)loadMyProfileWithAuth:(id)fp8;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)loadView;
- (void)viewDidUnload;
- (void)dealloc;
- (id)init;
- (id)initWithServices:(id)fp8 navigation:(id)fp12;

@end

