/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableString, YTAccountView_iPhone;

@interface YTAccountViewController_iPhone : YTBaseViewController_iPhone <UITableViewDataSource, UITableViewDelegate>
{
    YTAccountView_iPhone *accountView_;
    NSArray *accountViewTitles_;
    NSMutableString *uploadsString_;
}

- (void)didPressLogoutButton:(id)fp8;
- (void)loadMyProfileWithAuth:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)loadView;
- (void)viewDidUnload;
- (void)dealloc;

@end

