/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView, UITextField, UIView, UIView<YTStatusViewProtocol>, YTImageView;

@interface YTAddCommentView : _AVAudioSessionCategoryPlayback
{
    UIView *backgroundView_;
    YTImageView *userThumbnailView_;
    UIImageView *userThumbnailMaskView_;
    UIView<YTStatusViewProtocol> *statusView_;
    BOOL loading_;
    UITextField *inputField_;
    id <YTAddCommentViewDelegate> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)inputField;
- (void)setUserThumbnail:(id)fp8;
- (void)setShowLoading:(BOOL)fp8;
- (BOOL)hasFocus;
- (BOOL)resignFirstResponder;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8;

@end

