/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseService.h"

@class NSDate, YTAdTagsParser, YTGDataService, YTReachability, YTUserAuthenticator, YTVASTAdParser;

@interface YTAdsService : YTBaseService
{
    YTAdTagsParser *adTagsParser_;
    YTVASTAdParser *VASTAdParser_;
    NSDate *lastAdTime_;
    YTUserAuthenticator *userAuthenticator_;
    YTGDataService *GDataService_;
    YTReachability *reachability_;
}

+ (void)setAdFormatValueForAd:(id)fp8 withAdTag:(id)fp12;
+ (void)appendAdSenseExtraParamsToURLBuilder:(id)fp8 onWiFi:(BOOL)fp12;
+ (void)appendAdSenseSpamSignalsToURLBuilder:(id)fp8;
+ (BOOL)isAdSenseAdTag:(id)fp8;
+ (BOOL)isDoubleClickAdTag:(id)fp8;
+ (BOOL)isFreeWheelAdTag:(id)fp8;
+ (id)YouTubeVideoIDForAd:(id)fp8;
- (void)makeVASTAdRequestWithEnumerator:(id)fp8 impressionURLs:(id)fp12 timeoutTime:(id)fp16 responseBlock:(id)fp(null) errorBlock:(void)fp20;
- (void)makeAdTagsRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)makeVASTAdRequestWithVideoID:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)resetFrequencyCap;
- (void)dealloc;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12 userAuthenticator:(id)fp16 GDataService:(id)fp20 reachability:(id)fp24;

@end

