/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "GIPPickerDelegate-Protocol.h"
#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"

@class GIPPicker, NSMutableArray, NSMutableSet, UIView, YTGDataRequest, YTVideo;

@interface YTAddToPlaylistController : _AVAudioSessionCategoryPlayback <UIPickerViewDelegate, UIPickerViewDataSource, GIPPickerDelegate>
{
    YTVideo *video_;
    id <YTNavigation> navigation_;
    id <YTServices> services_;
    UIView *fromView_;
    struct CGRect fromRect_;
    NSMutableArray *playlists_;
    NSMutableSet *playlistTitles_;
    YTGDataRequest *pendingPlaylistsRequest_;
    YTGDataRequest *nextPlaylistsRequest_;
    GIPPicker *playlistPicker_;
}

- (void)authenticateWithBlock:(id)fp(null);
- (void)makePlaylistsRequest:(id)fp8;
- (void)addToPlaylist:(id)fp8;
- (void)didCreatePlaylistWithTitle:(id)fp8 isPrivate:(id)fp12;
- (void)cleanup;
- (int)pickerView:(id)fp8 numberOfRowsInComponent:(int)fp12;
- (int)numberOfComponentsInPickerView:(id)fp8;
- (id)pickerView:(id)fp8 titleForRow:(int)fp12 forComponent:(int)fp16;
- (void)pickerView:(id)fp8 didSelectRow:(int)fp12 inComponent:(int)fp16;
- (void)pickerDidCancel:(id)fp8;
- (void)picker:(id)fp8 didSelectItemAtIndex:(int)fp12;
- (void)showFromRect:(struct CGRect)fp8 inView:(id)fp24;
- (void)dealloc;
- (id)init;
- (id)initWithVideo:(id)fp8 navigation:(id)fp12 services:(id)fp16;

@end

