/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UIApplicationDelegate-Protocol.h"

@class GIPFeedbackCrashReportHandler, UIWindow;

@interface YTAppDelegate : _AVAudioSessionCategoryPlayback <UIApplicationDelegate>
{
    id <YTNavigation> navigation_;
    id <YTServices> services_;
    UIWindow *mainWindow_;
    GIPFeedbackCrashReportHandler *crashReportHandler_;
}

- (id)mainWindow;
- (void)runWithServices:(id)fp8;
- (void)openVideoWithID:(id)fp8;
- (void)registerCrashReportHandler;
- (void)applicationDidReceiveMemoryWarning:(id)fp8;
- (BOOL)application:(id)fp8 openURL:(id)fp12 sourceApplication:(id)fp16 annotation:(id)fp20;
- (void)dealloc;
- (BOOL)application:(id)fp8 didFinishLaunchingWithOptions:(id)fp12;

@end

