/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

@class MobileArtistBundle, NSString, YTArtistController;

@interface YTArtistViewController_iPhone : YTBaseViewController_iPhone
{
    MobileArtistBundle *artistBundle_;
    NSString *artistID_;
    YTArtistController *controller_;
}

- (void)loadWithArtistBundle:(id)fp8;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithArtistID:(id)fp8 services:(id)fp12 navigation:(id)fp16;
- (id)initWithArtistBundle:(id)fp8 services:(id)fp12 navigation:(id)fp16;

@end

