/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class YTAttributedTextLabel;

@interface YTArtistBioView_iPad : _AVAudioSessionCategoryPlayback
{
    YTAttributedTextLabel *bioLabel_;
    BOOL layoutChanged_;
}

- (void)setArtist:(id)fp8;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)fp8;
- (id)init;

@end

