/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface YTBaseController : _AVAudioSessionCategoryPlayback
{
    id <YTServices> services_;
    id <YTNavigation> navigation_;
}

- (id)services;
- (id)navigation;
- (void)dealloc;
- (id)initWithServices:(id)fp8 navigation:(id)fp12;

@end

