/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPResourceLoader, UIImageView, UILabel;

@interface YTBadge : _AVAudioSessionCategoryPlayback
{
    GIPResourceLoader *resourceLoader_;
    UIImageView *backgroundView_;
    UILabel *label_;
    int style_;
    float padding_;
    float textOffset_;
}

- (void)setTextOffset:(float)fp8;
- (void)setPadding:(float)fp8;
- (void)setStyle:(int)fp8;
- (void)setFont:(id)fp8 color:(id)fp12 shadowType:(int)fp16;
- (void)setText:(id)fp8;
- (id)text;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithResourceLoader:(id)fp8;
- (id)initWithResourceLoader:(id)fp8 style:(int)fp12;

@end

