/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTVideoCellProtocol-Protocol.h"

@class GIPResourceLoader, UIImageView, UILabel, YTImageView;

@interface YTBaseVideoCell_iPad : _AVAudioSessionCategoryPlayback <YTVideoCellProtocol>
{
    YTImageView *thumbnailView_;
    UILabel *titleLabel_;
    UILabel *duration_;
    UIImageView *headerView_;
    UILabel *uploaderLabel_;
    GIPResourceLoader *loader_;
}

+ (float)cellHeight;
+ (struct CGSize)thumbnailSizeForEntry:(id)fp8;
- (void)setThumbnail:(id)fp8 animated:(BOOL)fp12;
- (void)setEntry:(id)fp8;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)dealloc;
- (id)init;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

