/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GTMHTTPFetcherService, NSOperationQueue;

@interface YTBaseService : _AVAudioSessionCategoryPlayback
{
    NSOperationQueue *operationQueue_;
    GTMHTTPFetcherService *httpFetcherService_;
}

- (void)didReceiveMemoryWarning;
- (void)performMASFRequest:(id)fp8 serviceURI:(id)fp12 dataBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)performHTTPRequest:(id)fp8 parser:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)performHTTPRequest:(id)fp8 withAuthorizer:(id)fp12 parser:(id)fp16 responseBlock:(id)fp(null) errorBlock:(void)fp20;
- (void)performHTTPRequest:(id)fp8 dataBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)performHTTPRequest:(id)fp8 withAuthorizer:(id)fp12 dataBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)performHTTPRequest:(id)fp8 withAuthorizer:(id)fp12 completionBlock:(id)fp(null);
- (void)performErrorBlock:(id)fp(null) error:(void)fp8;
- (void)performResponseBlock:(id)fp(null) response:(void)fp8;
- (void)performBackgroundBlock:(id)fp(null);
- (void)dealloc;
- (id)init;
- (id)initWithOperationQueue:(id)fp8;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12;

@end

