/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTContainerViewController.h"

@class UIView, YTLeftNavigationButtons, YTRightNavigationButtons;

@interface YTBaseViewController_iPhone : YTContainerViewController
{
    id <YTNavigation> navigation_;
    id <YTServices> services_;
    YTLeftNavigationButtons *leftNavigationButtons_;
    YTRightNavigationButtons *rightNavigationButtons_;
    UIView *leftView_;
    UIView *rightView_;
}

- (id)services;
- (id)navigation;
- (void)didPressSearchButton:(id)fp8;
- (void)setNavigationBarTitle:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithServices:(id)fp8 navigation:(id)fp12;
- (id)initWithServices:(id)fp8 navigation:(id)fp12 rightView:(id)fp16;
- (id)initWithServices:(id)fp8 navigation:(id)fp12 leftView:(id)fp16 rightView:(id)fp20;

@end

