/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSString, NSURL;

@interface YTBranding : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSURL *watermarkURL_;
    NSURL *bannerURL_;
    NSURL *bannerTargetURL_;
    NSString *featuredPlaylistID_;
}

- (id)featuredPlaylistID;
- (id)bannerTargetURL;
- (id)bannerURL;
- (id)watermarkURL;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithWatermarkURL:(id)fp8 bannerURL:(id)fp12 bannerTargetURL:(id)fp16 featuredPlaylistID:(id)fp20;

@end

