/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

@class NSString, YTEventsFeedController;

@interface YTCategoryViewController_iPhone : YTBaseViewController_iPhone
{
    NSString *term_;
    YTEventsFeedController *eventsController_;
}

- (void)didSelectEvent:(id)fp8 source:(int)fp12 fromView:(id)fp16;
- (id)eventsTableView;
- (void)dismissPromo;
- (void)authenticationChanged:(id)fp8;
- (void)willMaximizeGuide:(id)fp8;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithServices:(id)fp8 navigation:(id)fp12;
- (id)initWithCategory:(id)fp8 services:(id)fp12 navigation:(id)fp16;

@end

