/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@interface YTCacheKeyWrapper : _AVAudioSessionCategoryPlayback <NSCopying>
{
    id key_;
}

+ (id)wrapperWithKey:(id)fp8;
- (id)key;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithKey:(id)fp8;

@end

