/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray, NSMutableDictionary;

@interface YTCache : _AVAudioSessionCategoryPlayback
{
    NSMutableDictionary *dictionary_;
    NSMutableArray *expirationQueue_;
    double expirationInterval_;
    unsigned int countLimit_;
}

- (id)valueWrapperForKeyWrapper:(id)fp8;
- (void)evict;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)fp8;
- (id)objectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)allKeys;
- (void)dealloc;
- (id)init;
- (id)initWithCountLimit:(unsigned int)fp8;
- (id)initWithExpirationInterval:(double)fp8 countLimit:(unsigned int)fp16;

@end

