/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTFeedController.h"

@class NSMutableDictionary;

@interface YTChannelStoreFeedController : YTFeedController
{
    id <YTNavigation> navigation_;
    NSMutableDictionary *switchControllersForCells_;
    NSMutableDictionary *switchControllersForChannels_;
}

- (void)updateCell:(id)fp8 forEntry:(id)fp12 animated:(BOOL)fp16;
- (void)handleEntries:(id)fp8;
- (void)dealloc;
- (id)initWithFeedView:(id)fp8 services:(id)fp12;
- (id)initWithFeedView:(id)fp8 navigation:(id)fp12 services:(id)fp16;

@end

