/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSString, NSURL;

@interface YTChannel : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *summary_;
    NSString *displayName_;
    NSString *channelID_;
    NSDate *updated_;
    unsigned long long videoCount_;
    NSURL *thumbnailURL_;
    unsigned long long subscribersCount_;
}

- (unsigned long long)subscribersCount;
- (id)thumbnailURL;
- (unsigned long long)videoCount;
- (id)updated;
- (id)channelID;
- (id)displayName;
- (id)summary;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithDisplayName:(id)fp8 channelID:(id)fp12 summary:(id)fp16 updated:(id)fp20 videoCount:(unsigned long long)fp24 thumbnailURL:(id)fp32 subscribersCount:(unsigned long long)fp36;

@end

