/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

#import "YTTabsViewDelegate-Protocol.h"

@class NSString, YTChannel, YTChannelController, YTChannelView_iPhone;

@interface YTChannelViewController_iPhone : YTBaseViewController_iPhone <YTTabsViewDelegate>
{
    NSString *channelID_;
    YTChannel *channel_;
    YTChannelController *controller_;
    YTChannelView_iPhone *view_;
    BOOL hiddenTabsAttemptedToLoad_;
}

- (void)loadWithChannel:(id)fp8;
- (void)didAttemptToChangeTab;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithServices:(id)fp8 navigation:(id)fp12;
- (id)initWithChannel:(id)fp8 services:(id)fp12 navigation:(id)fp16;
- (id)initWithChannelID:(id)fp8 services:(id)fp12 navigation:(id)fp16;

@end

