/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTChannelViewProtocol-Protocol.h"

@class UIView<YTChannelHeaderViewProtocol>, YTFeedTableView, YTTabsView;

@interface YTChannelView_iPhone : _AVAudioSessionCategoryPlayback <YTChannelViewProtocol>
{
    UIView<YTChannelHeaderViewProtocol> *headerView_;
    YTFeedTableView *playlistsFeedView_;
    YTFeedTableView *activityFeedView_;
    YTFeedTableView *uploadsFeedView_;
    YTTabsView *tabsView_;
}

- (id)tabsView;
- (id)uploadsFeedView;
- (id)activityFeedView;
- (id)playlistsFeedView;
- (id)headerView;
- (void)setScrollsToTop:(BOOL)fp8;
- (id)initWithResourceLoader:(id)fp8;

@end

