/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTContainerViewController.h"

#import "YTConveyorViewDelegate-Protocol.h"

@class NSMutableSet, YTConveyorView;

@interface YTConveyorViewController : YTContainerViewController <YTConveyorViewDelegate>
{
    YTConveyorView *conveyorView_;
    NSMutableSet *visibleChildren_;
    NSMutableSet *appearingChildren_;
    NSMutableSet *disappearingChildren_;
}

- (id)controllerForView:(id)fp8;
- (void)didHideView:(id)fp8 animated:(BOOL)fp12;
- (void)willHideView:(id)fp8 animated:(BOOL)fp12;
- (void)didShowView:(id)fp8 animated:(BOOL)fp12;
- (void)willShowView:(id)fp8 animated:(BOOL)fp12;
- (BOOL)childVisibleInView:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)pushViewController:(id)fp8 fromViewController:(id)fp12 animated:(BOOL)fp16;
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)init;

@end

