/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol YTConveyorViewDelegate
- (void)didHideView:(id)fp8 animated:(BOOL)fp12;
- (void)willHideView:(id)fp8 animated:(BOOL)fp12;
- (void)didShowView:(id)fp8 animated:(BOOL)fp12;
- (void)willShowView:(id)fp8 animated:(BOOL)fp12;
@end

