/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSMutableArray;

@interface YTContainerViewController : _AVAudioSessionCategoryPlayback
{
    NSMutableArray *childControllers_;
    BOOL forwardCallsToOS_;
    BOOL viewVisible_;
}

- (BOOL)viewVisible;
- (void)realignChildNavigationBars;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)childVisibleInView:(id)fp8;
- (BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
- (void)willRemoveChildController:(id)fp8;
- (void)didAddChildController:(id)fp8;
- (void)removeChildController:(id)fp8;
- (void)addChildController:(id)fp8;
- (id)childControllers;
- (void)viewDidUnload;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)init;

@end

