/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTFeedController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UITextField, YTAddCommentView;

@interface YTCommentsFeedController : YTFeedController <UITextFieldDelegate>
{
    YTAddCommentView *addCommentView_;
    NSString *videoID_;
    id <YTNavigation> navigation_;
    UITextField *inputField_;
}

- (void)updateUserAvatar:(id)fp8;
- (void)setCommentStatusToLoading:(BOOL)fp8;
- (void)addComment;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (BOOL)textFieldShouldEndEditing:(id)fp8;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)dealloc;
- (id)initWithFeedView:(id)fp8 videoID:(id)fp12 navigation:(id)fp16 services:(id)fp20;

@end

