/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTContainerViewController.h"

#import "UINavigationControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSArray, UIButton, UITableView, UITextField;

@interface YTCreatePlaylistViewController : YTContainerViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, UINavigationControllerDelegate>
{
    UITableView *tableView_;
    NSArray *sectionNames_;
    UIButton *doneButton_;
    UIButton *cancelButton_;
    UITextField *nameField_;
    BOOL isPlaylistPrivate_;
    id doneTarget_;
    SEL doneAction_;
    id <YTNavigation> navigation_;
}

+ (void)selectCell:(id)fp8 condition:(BOOL)fp12;
- (void)didPressDoneButton:(id)fp8;
- (BOOL)isInputValid;
- (void)didPressCancelButton:(id)fp8;
- (id)reuseableCellForTableView:(id)fp8;
- (id)privacyCellForRow:(int)fp8;
- (void)setPlaylistName:(id)fp8;
- (id)playlistName;
- (BOOL)playlistIsPrivate;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)nameCell;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)navigationController:(id)fp8 didShowViewController:(id)fp12 animated:(BOOL)fp16;
- (void)viewDidAppear:(BOOL)fp8;
- (void)reset;
- (void)playlistNameDidChange;
- (void)dealloc;
- (id)init;
- (id)initWithNavigation:(id)fp8 resourceLoader:(id)fp12 doneTarget:(id)fp16 doneAction:(SEL)fp20;

@end

