/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTFeedController.h"

@class NSMutableDictionary, NSMutableSet, UIImage;

@interface YTEventsFeedController : YTFeedController
{
    NSMutableDictionary *avatars_;
    NSMutableSet *groupIDs_;
    int source_;
    UIImage *YouTubeSystemChannelImage_;
}

- (void)feedView:(id)fp8 didSelectEntryAtIndex:(int)fp12;
- (void)updateCell:(id)fp8 forEntry:(id)fp12 animated:(BOOL)fp16;
- (void)setAvatar:(id)fp8 forEntry:(id)fp12;
- (void)loadAvatarForEvent:(id)fp8;
- (void)clear;
- (void)handleEntries:(id)fp8;
- (void)dealloc;
- (id)initWithFeedView:(id)fp8 services:(id)fp12;
- (id)initWithFeedView:(id)fp8 services:(id)fp12 source:(int)fp16;

@end

