/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol YTFeedViewDelegate <NSObject>
- (void)feedViewDidAskForRefresh:(id)fp8;
- (void)feedViewDidAskForMore:(id)fp8;
- (void)feedView:(id)fp8 didSelectEntryAtIndex:(int)fp12;
- (id)entryAtIndex:(int)fp8;
- (void)updateCell:(id)fp8 atIndex:(int)fp12;
- (int)entryCount;
@end

