/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class GTMOAuth2Authentication, NSData, NSURL;

@interface YTGDataRequest : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSURL *URL_;
    GTMOAuth2Authentication *authentication_;
    NSData *body_;
    BOOL noCache_;
}

+ (void)setSafeSearchFilter:(int)fp8 toURLBuilder:(id)fp12;
+ (void)setCCFilter:(BOOL)fp8 toURLBuilder:(id)fp12;
+ (void)setDurationFilter:(int)fp8 toURLBuilder:(id)fp12;
+ (void)setUploadDateFilter:(int)fp8 toURLBuilder:(id)fp12;
+ (void)setSortByFilter:(int)fp8 toURLBuilder:(id)fp12;
+ (void)setFormatsToURLBuilder:(id)fp8;
+ (void)setPageSize:(int)fp8 toURLBuilder:(id)fp12;
+ (void)setDefaultPageSizeToURLBuilder:(id)fp8;
+ (void)setQueryParametersToURLBuilder:(id)fp8 withSafeSearch:(int)fp12;
+ (void)setDirectAccessParametersToURLBuilder:(id)fp8;
+ (BOOL)regionHasLocalizedStandardFeeds:(id)fp8;
+ (id)requestWithURLString:(id)fp8 authentication:(id)fp12 body:(id)fp16;
+ (id)requestWithURLString:(id)fp8 authentication:(id)fp12;
+ (id)requestWithURLString:(id)fp8;
+ (id)requestWithURL:(id)fp8 authentication:(id)fp12 body:(id)fp16 noCache:(BOOL)fp20;
+ (id)requestWithURL:(id)fp8 authentication:(id)fp12 body:(id)fp16;
+ (id)requestWithURL:(id)fp8 authentication:(id)fp12;
+ (id)requestToAddCommentWithVideoID:(id)fp8 authentication:(id)fp12 content:(id)fp16;
+ (id)requestToFlagWithVideoID:(id)fp8 authentication:(id)fp12;
+ (id)requestForMyPurchases:(id)fp8;
+ (id)requestForBrandingWithChannelID:(id)fp8;
+ (id)requestForMyChannelRecommendationsWithAuth:(id)fp8;
+ (id)requestToAddToFavoritesWithVideoID:(id)fp8 authentication:(id)fp12;
+ (id)requestToRateWithVideoID:(id)fp8 authentication:(id)fp12 like:(BOOL)fp16;
+ (id)requestForEventsWithChannelID:(id)fp8;
+ (id)requestToUnsubscribeWithSubscription:(id)fp8 authentication:(id)fp12;
+ (id)requestToSubscribeWithChannelID:(id)fp8 authentication:(id)fp12;
+ (id)requestToAddToWatchLaterWithVideoID:(id)fp8 authentication:(id)fp12;
+ (id)requestForMyWatchLaterVideosWithAuth:(id)fp8;
+ (id)requestToClearWatchHistoryWithAuth:(id)fp8;
+ (id)requestToAddToWatchHistoryWithVideoID:(id)fp8 authentication:(id)fp12;
+ (id)requestForMyWatchHistoryVideosWithAuth:(id)fp8;
+ (id)requestForMySubscriptionWithChannelID:(id)fp8 auth:(id)fp12;
+ (id)requestForMySubscriptionsWithAuth:(id)fp8;
+ (id)requestToAddToPlaylistWithVideoID:(id)fp8 contentURL:(id)fp12 auth:(id)fp16;
+ (id)requestToAddPlaylistWithTitle:(id)fp8 description:(id)fp12 isPrivate:(BOOL)fp16 auth:(id)fp20;
+ (id)requestForMyPlaylistsWithAuth:(id)fp8;
+ (id)requestForPlaylistsWithChannelID:(id)fp8;
+ (id)requestForPlaylistWithURL:(id)fp8;
+ (id)requestForMyUserProfileWithAuth:(id)fp8;
+ (id)requestForChannelWithID:(id)fp8;
+ (id)requestForMyPlaylistVideosWithURL:(id)fp8 authentication:(id)fp12;
+ (id)requestForPlaylistVideosWithPlaylistID:(id)fp8;
+ (id)requestForPlaylistVideosWithURL:(id)fp8;
+ (id)requestForMySubscriptionUploadsWithAuth:(id)fp8 safeSearch:(int)fp12;
+ (id)requestForMySubscriptionUpdatesWithAuth:(id)fp8;
+ (id)requestForMyUploadedVideosWithAuth:(id)fp8;
+ (id)requestForUploadedVideosWithChannelID:(id)fp8;
+ (id)requestForMyFavoriteVideosWithAuth:(id)fp8;
+ (id)requestForFavoriteVideosWithURL:(id)fp8;
+ (id)requestForVideosWithStandardFeed:(int)fp8 categoryTerm:(id)fp12 uploadDate:(int)fp16 safeSearch:(int)fp20;
+ (id)requestForRelatedVideosWithURL:(id)fp8 safeSearch:(int)fp12;
+ (id)requestForChannelsWithStandardFeed:(int)fp8;
+ (id)requestForChannelsWithSearchQuery:(id)fp8;
+ (id)requestForVideosWithSearchQuery:(id)fp8 languageCode:(id)fp12 filters:(id)fp16 safeSearch:(int)fp20;
+ (id)requestForVideoWithVideoID:(id)fp8;
+ (id)requestForCategoriesWithLanguageCode:(id)fp8;
+ (id)requestWithRequest:(id)fp8 noCache:(BOOL)fp12;
+ (id)requestWithRequest:(id)fp8 URL:(id)fp12;
+ (id)requestWithURL:(id)fp8;
- (BOOL)noCache;
- (id)body;
- (id)authentication;
- (id)URL;
- (id)initWithURL:(id)fp8;
- (BOOL)isPathIdenticalToRequest:(id)fp8;
- (unsigned int)hash;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;
- (id)initWithURL:(id)fp8 authentication:(id)fp12 body:(id)fp16 noCache:(BOOL)fp20;

@end

