/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMHTTPFetcher.h"

@interface YTGTMHTTPFetcher : GTMHTTPFetcher
{
}

- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;

@end

