/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSString, YTCategory, YTSubscription;

@interface YTGuideEntry : _AVAudioSessionCategoryPlayback <NSCopying>
{
    YTSubscription *subscription_;
    YTCategory *category_;
    NSString *title_;
    int action_;
    unsigned int count_;
}

- (void)setCount:(unsigned int)fp8;
- (unsigned int)count;
- (int)action;
- (void)setTitle:(id)fp8;
- (id)title;
- (id)category;
- (id)subscription;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithTitle:(id)fp8 guideAction:(int)fp12;
- (id)initWithCategory:(id)fp8;
- (id)initWithSubscription:(id)fp8;

@end

