/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTGuideCellProtocol-Protocol.h"

@class GIPResourceLoader, UIImageView, UILabel, YTImageView;

@interface YTGuideCell_iPhone : _AVAudioSessionCategoryPlayback <YTGuideCellProtocol>
{
    UILabel *titleLabel_;
    YTImageView *thumbnailView_;
    UIImageView *thumbnailMaskView_;
    UIImageView *backgroundView_;
    BOOL layoutChanged_;
    GIPResourceLoader *loader_;
    BOOL entryIsSelected_;
}

+ (float)cellWidth;
+ (float)cellHeight;
+ (struct CGSize)thumbnailSizeForEntry:(id)fp8;
- (void)updatePressedAppearance;
- (void)setSelectedThumbnail:(id)fp8;
- (void)setTitle:(id)fp8;
- (void)setThumbnail:(id)fp8 animated:(BOOL)fp12;
- (void)setEntry:(id)fp8;
- (void)setHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setEntryIsSelected:(BOOL)fp8;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

