/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView, UILabel;

@interface YTGuidePromoView_iPhone : _AVAudioSessionCategoryPlayback
{
    UIImageView *backgroundImageView_;
    UIImageView *arrowImageView_;
    UILabel *messageLabel_;
}

- (void)layoutSubviews;
- (id)init;
- (id)initWithResourceLoader:(id)fp8;

@end

