/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIButton, UIImageView, UILabel;

@interface YTGuidePromoView_iPad : _AVAudioSessionCategoryPlayback
{
    UILabel *messageLabel_;
    UIImageView *buttonsFrame_;
    UIButton *signInButton_;
    UIButton *signUpButton_;
}

- (void)removeAllActionsForTarget:(id)fp8 forControlEvents:(unsigned int)fp12;
- (void)addSignUpTarget:(id)fp8 action:(SEL)fp12 forControlEvents:(unsigned int)fp16;
- (void)addSignInTarget:(id)fp8 action:(SEL)fp12 forControlEvents:(unsigned int)fp16;
- (void)layoutSubviews;
- (id)initWithResourceLoader:(id)fp8;

@end

