/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseService.h"

@class YTCache, YTReachability;

@interface YTImageService : YTBaseService
{
    YTCache *imageCache_;
    YTCache *dataCache_;
    YTReachability *reachability_;
}

- (id)closestImageURLWithTargetSize:(struct CGSize)fp8 preferredSize:(struct CGSize)fp16 URLs:(id)fp24;
- (id)selectURLForTargetSize:(struct CGSize)fp8 fromURLs:(id)fp16;
- (void)didReceiveMemoryWarning;
- (void)makeImageRequestWithURLs:(id)fp8 targetSize:(struct CGSize)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp20;
- (void)makeImageRequestWithURL:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)dealloc;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12 reachability:(id)fp16;

@end

