/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTServices-Protocol.h"

@class GIPResourceLoader, GTMHTTPFetcherService, NSOperationQueue, YTAdsService, YTDeviceAuthorizer, YTGDataService, YTImageService, YTMusicService, YTPTrackingService, YTReachability, YTSearchHistory, YTSettings, YTSubtitlesService, YTSuggestService, YTUserAuthenticator;

@interface YTLiveServices : _AVAudioSessionCategoryPlayback <YTServices>
{
    NSOperationQueue *dataOperationQueue_;
    GTMHTTPFetcherService *dataFetcherService_;
    NSOperationQueue *imageOperationQueue_;
    GTMHTTPFetcherService *imageFetcherService_;
    GTMHTTPFetcherService *adsFetcherService_;
    YTAdsService *adsService_;
    YTGDataService *gDataService_;
    YTImageService *imageService_;
    YTMusicService *musicService_;
    YTSuggestService *suggestService_;
    YTSubtitlesService *subtitlesService_;
    YTPTrackingService *PTrackingService_;
    YTDeviceAuthorizer *deviceAuthorizer_;
    YTUserAuthenticator *userAuthenticator_;
    YTSearchHistory *searchHistory_;
    GIPResourceLoader *resourceLoader_;
    YTReachability *reachability_;
    YTSettings *settings_;
}

- (void)didReceiveMemoryWarning;
- (id)settings;
- (id)reachability;
- (id)resourceLoader;
- (id)userAuthenticator;
- (id)PTrackingServiceWithAdVideo:(id)fp8 video:(id)fp12 CPN:(id)fp16;
- (id)PTrackingServiceWithVideo:(id)fp8 CPN:(id)fp12;
- (id)videoStatsServiceWithSource:(int)fp8;
- (id)subtitlesService;
- (id)suggestService;
- (id)searchHistory;
- (id)musicService;
- (id)imageService;
- (id)gDataService;
- (id)adTrackingServiceForAd:(id)fp8;
- (id)adsService;
- (void)dealloc;
- (id)init;

@end

