/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

#import "UIAlertViewDelegate-Protocol.h"

@class UIAlertView, UIButton, YTVideosFeedController;

@interface YTMyWatchHistoryViewController_iPhone : YTBaseViewController_iPhone <UIAlertViewDelegate>
{
    YTVideosFeedController *videosFeedController_;
    UIButton *clearButton_;
    UIAlertView *confirmAlert_;
}

- (void)clearHistory;
- (void)didPressClearButton:(id)fp8;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithServices:(id)fp8 navigation:(id)fp12;

@end

