/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

@class YTVideosFeedController;

@interface YTMyWatchLaterViewController_iPhone : YTBaseViewController_iPhone
{
    YTVideosFeedController *videosFeedController_;
}

- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithServices:(id)fp8 navigation:(id)fp12;

@end

