/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol YTNavigation <NSObject>
- (BOOL)isLastSender:(id)fp8;
- (void)setNavigationBarHidden:(BOOL)fp8;
- (void)toastWithError:(id)fp8 message:(id)fp12;
- (void)toastWithMessage:(id)fp8;
- (void)hideGuide;
- (void)showGuide;
- (void)back;
- (void)showSettingsFromView:(id)fp8;
- (void)showSignInFromRect:(struct CGRect)fp8 inView:(id)fp24 auth:(id)fp28 authedBlock:(id)fp(null) failedBlock:(void)fp32 canceledBlock:(id)fp(null);
- (void)showChannelStoreFromView:(id)fp8;
- (void)showAccountFromView:(id)fp8;
- (void)showArtistWithArtistID:(id)fp8 fromView:(id)fp12;
- (void)showArtistWithArtistBundle:(id)fp8 fromView:(id)fp12;
- (void)showRiverFromView:(id)fp8;
- (void)showCategory:(id)fp8 fromView:(id)fp12;
- (void)showChannel:(id)fp8 fromView:(id)fp12;
- (void)showChannelWithID:(id)fp8 fromView:(id)fp12;
- (void)showPlaylist:(id)fp8 source:(int)fp12 fromView:(id)fp16;
- (void)showMyWatchLaterFromView:(id)fp8;
- (void)showMyWatchHistoryFromView:(id)fp8;
- (void)showMyUploadsFromView:(id)fp8;
- (void)showMyPurchasesFromView:(id)fp8;
- (void)showMyPlaylistsFromView:(id)fp8;
- (void)showMyFavoritesFromView:(id)fp8;
- (void)showWatchWithVideoID:(id)fp8 source:(int)fp12 fromView:(id)fp16;
- (void)showWatchWithVideo:(id)fp8 source:(int)fp12 fromView:(id)fp16;
- (void)showAddPlaylistFromView:(id)fp8 target:(id)fp12 action:(SEL)fp16;
- (void)showSearchFilters:(id)fp8 target:(id)fp12 action:(SEL)fp16;
- (void)showSearchResultsForQuery:(id)fp8 fromView:(id)fp12;
- (void)showSearchForQuery:(id)fp8 fromView:(id)fp12;
- (void)showHome;
- (void)shutdown;
- (void)loadWithWindow:(id)fp8;
@end

