/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPResourceLoader, UIView;

@interface YTPillsView : _AVAudioSessionCategoryPlayback
{
    UIView *backgroundView_;
    UIView *pillsBar_;
    UIView *contentViewsContainer_;
    int currentIndex_;
    GIPResourceLoader *loader_;
    id target_;
    SEL action_;
}

- (void)animateToIndex:(int)fp8;
- (void)didPressPill:(id)fp8;
- (id)pillWithTitle:(id)fp8;
- (void)setContentViewSelectedTarget:(id)fp8 action:(SEL)fp12;
- (void)addContentView:(id)fp8 withTitle:(id)fp12;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8;

@end

