/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTPlayerControlsViewDelegate-Protocol.h"
#import "YTPlayerDelegate-Protocol.h"
#import "YTPlayerViewDelegate-Protocol.h"
#import "YTSubtitlesControllerDelegate-Protocol.h"

@class UIWindow, YTAdTrackingService, YTDRMStreamConverter, YTPTrackingService, YTPlayerView, YTSubtitlesController, YTVASTAd, YTVideo, YTVideoStatsService;

@interface YTPlayerController : _AVAudioSessionCategoryPlayback <YTPlayerDelegate, YTPlayerControlsViewDelegate, YTPlayerViewDelegate, YTSubtitlesControllerDelegate>
{
    BOOL viewVisible_;
    BOOL autopaused_;
    int state_;
    YTVASTAd *vastAd_;
    YTAdTrackingService *adTrackingService_;
    BOOL DRMStreamConverterNeedsRestart_;
    BOOL replayReady_;
    BOOL videoAddedToHistory_;
    id <YTPlayer> player_;
    YTPlayerView *playerView_;
    YTSubtitlesController *subtitlesController_;
    YTVideo *video_;
    id <YTServices> services_;
    id <YTNavigation> navigation_;
    YTDRMStreamConverter *DRMStreamConverter_;
    double savedSeekTime_;
    YTVideoStatsService *videoStatsService_;
    YTPTrackingService *PTrackingService_;
    id <YTPlayerControllerDelegate> playerControllerDelegate_;
    UIWindow *secondScreenWindow_;
    id <YTPlayerControlsVisibilityDelegate> controlsVisibilityDelegate_;
}

+ (void)pauseActivePlayer;
- (void)setControlsVisibilityDelegate:(id)fp8;
- (id)controlsVisibilityDelegate;
- (void)startCPNServicesForAd;
- (void)startCPNServicesForVideo;
- (void)showAudioAirPlayToast;
- (void)appDidBecomeActive;
- (void)appWillResignActive;
- (void)stopSecondScreen:(id)fp8;
- (void)startSecondScreen:(id)fp8;
- (id)selectStreamForVideo:(id)fp8;
- (void)addVideoToHistory;
- (void)animateControlsToHiddenWithDuration:(id)fp8;
- (void)animateControlsToHiddenWithDelay;
- (void)animateControlsToVisible;
- (void)clearVisibilityTimer;
- (void)loadAdThenVideoStreams;
- (void)setAndPlayVideoStream:(id)fp8;
- (void)loadVideoStream;
- (void)playIfPermitted;
- (void)restartDRMStreamConverterIfNeeded;
- (void)didReceiveDRMErrorNotification:(id)fp8;
- (void)pauseAndReleasePlayer;
- (void)adPlaybackDidStop;
- (id)videoOrAdVideo;
- (void)subtitlesPickerDidClose;
- (void)playerViewDidPinchToSmallscreen;
- (void)playerViewDidPinchToFullscreen;
- (void)playerViewDidPressAdTitle;
- (void)playerViewDidPressAdLearnMore;
- (void)playerViewDidPressSkipAd;
- (void)playerViewDidShowSkipAd;
- (void)playerViewDidReceiveTouch;
- (void)playbackDidFailWithError:(id)fp8;
- (void)playbackRenderingDidChangeToView:(id)fp8;
- (void)playbackReadyToDisplay;
- (void)playbackLoadingDidStop;
- (void)playbackLoadingDidStart;
- (void)playbackDidPause;
- (void)playbackDidProgress;
- (void)updatePlayerView;
- (void)playbackDidPlay;
- (void)playbackNotReadyToReplay;
- (void)playbackReadyToReplay;
- (void)playbackDidFinish;
- (void)didPressReplay;
- (void)didPressSmallscreen;
- (void)didPressFullscreen;
- (void)didEndScrubbing;
- (void)didStartScrubbing;
- (void)didPressSubtitlesInRect:(struct CGRect)fp8 inView:(id)fp24;
- (void)didSeekToTime:(double)fp8;
- (void)didPressPause;
- (void)didPressPlay;
- (void)animateControlsToHidden;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)setBranding:(id)fp8;
- (void)setPlayerControllerDelegate:(id)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithServices:(id)fp8 navigation:(id)fp12 playerView:(id)fp16 player:(id)fp20 video:(id)fp24 source:(int)fp28;

@end

