/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

@class YTPlaylist, YTVideosFeedController;

@interface YTPlaylistViewController_iPhone : YTBaseViewController_iPhone
{
    YTPlaylist *playlist_;
    int source_;
    BOOL showTitleBar_;
    YTVideosFeedController *videosController_;
}

- (void)loadView;
- (void)viewDidUnload;
- (void)dealloc;
- (id)initWithPlaylist:(id)fp8 source:(int)fp12 showTitleBar:(BOOL)fp16 services:(id)fp20 navigation:(id)fp24;

@end

