/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTFeedViewCellProtocol-Protocol.h"

@class UIImageView, UILabel, UIView, YTImageView;

@interface YTPlaylistCell_iPad : _AVAudioSessionCategoryPlayback <YTFeedViewCellProtocol>
{
    UILabel *titleLabel_;
    UILabel *videoCount_;
    YTImageView *thumbnailView_;
    UIView *playallView_;
    UIImageView *headerView_;
}

+ (float)cellHeight;
+ (struct CGSize)thumbnailSizeForEntry:(id)fp8;
- (void)setThumbnail:(id)fp8 animated:(BOOL)fp12;
- (void)setEntry:(id)fp8;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

