/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSNumber;

@interface YTPlaybackRange : _AVAudioSessionCategoryPlayback
{
    NSNumber *start_;
    NSNumber *end_;
}

- (void)setEnd:(id)fp8;
- (id)end;
- (void)setStart:(id)fp8;
- (id)start;
- (id)description;
- (void)dealloc;

@end

