/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTPlayer-Protocol.h"

@class AVPlayer, AVPlayerItem, AVURLAsset, NSTimer, NSURL, YTPlayerLayerView;

@interface YTPlayer_iOS5 : _AVAudioSessionCategoryPlayback <YTPlayer>
{
    NSURL *contentURL_;
    double seekingTo_;
    double totalTimeHint_;
    int playbackState_;
    int prevPlaybackState_;
    BOOL statusReadyToPlay_;
    BOOL seekPerformedBeforeReadyToPlay_;
    BOOL readyToDisplay_;
    id <YTPlayerDelegate> delegate_;
    NSTimer *playbackStatusObserver_;
    AVPlayer *avPlayer_;
    YTPlayerLayerView *playerView_;
    AVPlayerItem *playerItem_;
    AVURLAsset *loadingAsset_;
    double lastSavedPlaybackTime_;
    int seekingCount_;
    double secondsToBufferBeforePlaybackRestart_;
    struct {
    } itemStatusContext;
}

+ (double)secondsWithCMTime:(CDAnonymousStruct1)fp8;
- (void)setPlaybackState:(int)fp8;
- (void)removePlayerItemNotifications;
- (void)addPlayerItemNotifications;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)playbackDidFinish:(id)fp8;
- (void)stopPlaybackStatusObserver;
- (void)startPlaybackStatusObserver;
- (void)updateSpinnerStatusAndLastPlaybackTime;
- (void)restartPlaybackIfNecessary;
- (void)createPlayerIfNeeded;
- (void)setDelegate:(id)fp8;
- (id)currentFrame;
- (BOOL)isPlaying;
- (double)downloadedTime;
- (double)totalTime;
- (void)setTotalTimeHint:(double)fp8;
- (double)mediaTime;
- (void)seekToTimeWithoutPlayerCreation:(double)fp8;
- (void)seekToTime:(double)fp8;
- (void)rewind;
- (void)pause;
- (void)play;
- (void)setContentURL:(id)fp8;
- (id)contentURL;
- (void)releasePlayer;
- (void)dealloc;
- (id)init;

@end

