/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class YTFeedTableView, YTPlaylistHeaderView_iPhone, YTPlaylistTitleBar_iPhone;

@interface YTPlaylistView_iPhone : _AVAudioSessionCategoryPlayback
{
    YTPlaylistHeaderView_iPhone *headerView_;
    YTPlaylistTitleBar_iPhone *titleBar_;
    BOOL layoutChanged_;
    YTFeedTableView *feedView_;
}

- (id)feedView;
- (void)setScrollsToTop:(BOOL)fp8;
- (void)layoutSubviews;
- (void)loadWithPlaylist:(id)fp8;
- (id)initWithResourceLoader:(id)fp8 showTitleBar:(BOOL)fp12;

@end

