/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol YTPlayer <NSObject>
- (void)setDelegate:(id)fp8;
- (id)currentFrame;
- (BOOL)isPlaying;
- (double)downloadedTime;
- (void)setTotalTimeHint:(double)fp8;
- (double)totalTime;
- (void)seekToTimeWithoutPlayerCreation:(double)fp8;
- (void)seekToTime:(double)fp8;
- (double)mediaTime;
- (void)rewind;
- (void)pause;
- (void)play;
- (void)setContentURL:(id)fp8;
- (id)contentURL;
- (void)releasePlayer;
@end

