/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSDictionary, NSString, NSURL;

@interface YTPlaylist : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *title_;
    NSString *summary_;
    NSString *authorDisplayName_;
    NSDate *updated_;
    NSDictionary *thumbnailURLs_;
    NSURL *contentURL_;
    NSURL *editURL_;
    unsigned int size_;
    BOOL isPrivate_;
}

- (BOOL)isPrivate;
- (unsigned int)size;
- (id)editURL;
- (id)contentURL;
- (id)thumbnailURLs;
- (id)updated;
- (id)authorDisplayName;
- (id)summary;
- (id)title;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithTitle:(id)fp8 summary:(id)fp12 authorDisplayName:(id)fp16 updated:(id)fp20 thumbnailURLs:(id)fp24 contentURL:(id)fp28 editURL:(id)fp32 size:(unsigned int)fp36 isPrivate:(BOOL)fp40;

@end

