/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTPlayer-Protocol.h"

@class MPMoviePlayerController, NSTimer, NSURL;

@interface YTPlayer_iOS4 : _AVAudioSessionCategoryPlayback <YTPlayer>
{
    MPMoviePlayerController *mpcPlayer_;
    NSURL *contentURL_;
    double seekingTo_;
    BOOL seekPerformedBeforeReadyToPlay_;
    BOOL playbackProgressReported_;
    double totalTimeHint_;
    double lastSavedPlaybackTime_;
    int playbackState_;
    int prevPlaybackState_;
    BOOL statusReadyToPlay_;
    BOOL readyToDisplay_;
    int seekingCount_;
    id <YTPlayerDelegate> delegate_;
    NSTimer *playbackStatusObserver_;
}

- (void)setPlaybackState:(int)fp8;
- (void)seekingDidFinish;
- (void)seekingDidStart;
- (void)stopPlaybackStatusObserver;
- (void)startPlaybackStatusObserver;
- (void)updateSpinnerStatusAndLastPlaybackTime;
- (void)loadStateDidChange:(id)fp8;
- (void)playbackStateDidChange:(id)fp8;
- (void)playbackDidFinish:(id)fp8;
- (void)createPlayerIfNeeded;
- (id)currentFrame;
- (void)setDelegate:(id)fp8;
- (BOOL)isPlaying;
- (double)downloadedTime;
- (double)totalTime;
- (void)setTotalTimeHint:(double)fp8;
- (double)mediaTime;
- (void)seekToTimeWithoutPlayerCreation:(double)fp8;
- (void)seekToTime:(double)fp8;
- (void)rewind;
- (void)pause;
- (void)play;
- (void)setContentURL:(id)fp8;
- (id)contentURL;
- (void)releasePlayer;
- (void)dealloc;

@end

