/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "YTFeedViewCellProtocol-Protocol.h"

@class UIImageView, UILabel, YTAttributedTextLabel, YTImageView;

@interface YTPurchaseCell : _AVAudioSessionCategoryPlayback <YTFeedViewCellProtocol>
{
    UIImageView *cellBackgroundView_;
    YTImageView *thumbnailView_;
    UILabel *titleLabel_;
    YTAttributedTextLabel *expiresLabel_;
    UILabel *yearDurationLabel_;
    UILabel *descriptionLabel_;
}

+ (void)setExpiresInTextOnLabel:(id)fp8 forTimeInterval:(double)fp12;
+ (float)cellHeight;
+ (struct CGSize)thumbnailSizeForEntry:(id)fp8;
- (void)setThumbnail:(id)fp8 animated:(BOOL)fp12;
- (void)setEntry:(id)fp8;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

