/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITextFieldDelegate-Protocol.h"
#import "YTSearchSuggestionsViewDelegate-Protocol.h"
#import "YTSearchViewProtocol-Protocol.h"

@class UIButton, UIImageView, UIPopoverController, UIView, YTSearchFilters, YTSearchFiltersViewController, YTSearchSuggestionsViewController_iPad, YTSearchTextField;

@interface YTSearchBar_iPad : _AVAudioSessionCategoryPlayback <YTSearchViewProtocol, YTSearchSuggestionsViewDelegate, UITextFieldDelegate>
{
    UIView *backgroundView_;
    UIButton *refineButton_;
    UIButton *voiceButton_;
    YTSearchTextField *searchTextField_;
    UIImageView *searchTextFieldBackgroundImageView_;
    id <YTSearchBar_iPadDelegate> delegate_;
    UIPopoverController *suggestionsPopoverController_;
    UIPopoverController *filtersPopoverController_;
    YTSearchSuggestionsViewController_iPad *searchSuggestionsViewController_;
    YTSearchFiltersViewController *searchFiltersViewController_;
    BOOL hasSuggestions_;
    id <YTSearchViewDelegate> searchViewDelegate_;
    YTSearchFilters *searchFilters_;
}

- (id)searchFilters;
- (void)setSearchViewDelegate:(id)fp8;
- (id)searchViewDelegate;
- (void)hideFiltersPopover:(id)fp8;
- (void)editingDidEnd:(id)fp8;
- (void)editingDidBegin:(id)fp8;
- (void)editingChanged:(id)fp8;
- (void)editingDidEndOnExit:(id)fp8;
- (void)showFiltersPopover:(id)fp8;
- (void)hideSuggestionsPopover:(id)fp8;
- (void)showSuggestionsPopover:(id)fp8;
- (void)searchWithFilters:(id)fp8;
- (void)didPressVoice:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)loseFocus;
- (void)gainFocus;
- (void)setEnableVoiceSearch:(BOOL)fp8;
- (void)setQuery:(id)fp8;
- (id)query;
- (void)setSuggestions:(id)fp8;
- (void)searchSuggestionAddDidPress:(id)fp8;
- (void)searchSuggestionDidPress:(id)fp8;
- (void)layoutSubviews;
- (void)setRefineButtonHidden:(BOOL)fp8;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithResourceLoader:(id)fp8 services:(id)fp12 navigation:(id)fp16;

@end

