/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class GIPResourceLoader, NSArray;

@interface YTSearchSuggestionsViewController_iPad : _AVAudioSessionCategoryPlayback <UITableViewDelegate, UITableViewDataSource>
{
    NSArray *suggestions_;
    GIPResourceLoader *resourceLoader_;
    id <YTSearchSuggestionsViewDelegate> delegate_;
}

- (void)addButtonDidPress:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)setDelegate:(id)fp8;
- (void)setSuggestions:(id)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithResourceLoader:(id)fp8;

@end

