/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface YTSearchTextField : _AVAudioSessionCategoryPlayback
{
    float horizontalPadding_;
    float verticalPadding_;
}

- (void)setVerticalPadding:(float)fp8;
- (float)verticalPadding;
- (void)setHorizontalPadding:(float)fp8;
- (float)horizontalPadding;
- (void)editingChanged:(id)fp8;
- (void)clearButtonPressed:(id)fp8;
- (struct CGRect)rightViewRectForBounds:(struct CGRect)fp8;
- (struct CGRect)leftViewRectForBounds:(struct CGRect)fp8;
- (struct CGRect)editingRectForBounds:(struct CGRect)fp8;
- (struct CGRect)textRectForBounds:(struct CGRect)fp8;
- (id)init;
- (id)initWithResourceLoader:(id)fp8 font:(id)fp12;

@end

