/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTContainerViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class GIPResourceLoader, NSArray, UITableView;

@interface YTSettingsPickerViewController : YTContainerViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *tableView_;
    NSArray *items_;
    unsigned int selectedItemIndex_;
    id choiceTarget_;
    SEL choiceAction_;
    GIPResourceLoader *loader_;
}

- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)setChoiceTarget:(id)fp8 action:(SEL)fp12;
- (void)dealloc;
- (id)init;
- (id)initWithResourceLoader:(id)fp8 title:(id)fp12 items:(id)fp16 selectedItemIndex:(unsigned int)fp20;

@end

