/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, UIButton, UITableView, YTSearchFilters;

@interface YTSearchFiltersViewController : YTBaseViewController_iPhone <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *tableView_;
    NSArray *sectionNames_;
    UIButton *doneButton_;
    UIButton *cancelButton_;
    YTSearchFilters *searchFilters_;
    id doneTarget_;
    SEL doneAction_;
    int style_;
}

- (void)didPressDoneButton:(id)fp8;
- (void)didPressCancelButton:(id)fp8;
- (id)reuseableCellForTableView:(id)fp8;
- (id)featuresCellForRow:(int)fp8;
- (id)durationCellForRow:(int)fp8;
- (id)uploadDateCellForRow:(int)fp8;
- (id)sortByCellForRow:(int)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)dealloc;
- (void)loadView;
- (id)initWithServices:(id)fp8 navigation:(id)fp12 searchFilters:(id)fp16 doneTarget:(id)fp20 doneAction:(SEL)fp24 style:(int)fp28;

@end

