/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMOAuth2ViewControllerTouch.h"

@class GIPPopoverController, UIActivityIndicatorView, UIButton;

@interface YTSignInViewController : GTMOAuth2ViewControllerTouch
{
    GIPPopoverController *popoverController_;
    UIButton *closeButton_;
    UIActivityIndicatorView *loadingSpinner_;
}

- (id)scrollViewOfWebView:(id)fp8;
- (void)checkContentAlignment:(id)fp8;
- (void)closeButtonDidPress:(id)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (void)presentInPopoverFromRect:(struct CGRect)fp8 inView:(id)fp24 permittedArrowDirections:(unsigned int)fp28 resourceLoader:(id)fp32;
- (void)dealloc;
- (id)initWithAuth:(id)fp8 authedBlock:(id)fp(null) failedBlock:(void)fp12 canceledBlock:(id)fp(null);

@end

