/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface YTSparkleBarView : _AVAudioSessionCategoryPlayback
{
    struct CGImage *cachedBar_;
    struct CGSize cachedBarSize_;
    int style_;
    float positivePercent_;
}

- (float)positivePercent;
- (int)style;
- (void)draw1PxStroke:(struct CGContext *)fp8 startPoint:(struct CGPoint)fp12 endPoint:(struct CGPoint)fp20 color:(struct CGColor *)fp28;
- (void)drawGloss:(struct CGContext *)fp8 inRect:(struct CGRect)fp12;
- (void)drawLinearGradient:(struct CGContext *)fp8 inRect:(struct CGRect)fp12 startColor:(struct CGColor *)fp28 endColor:(struct CGColor *)fp32;
- (void)setPositivePercent:(float)fp8;
- (void)setStyle:(int)fp8;
- (void)setPositiveCount:(int)fp8 negativeCount:(int)fp12;
- (void)drawRect:(struct CGRect)fp8;
- (void)dealloc;
- (id)initWithStyle:(int)fp8;

@end

