/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol YTStatusViewProtocol <NSObject>
- (void)setRightMargin:(float)fp8;
- (float)rightMargin;
- (void)setTopMargin:(float)fp8;
- (float)topMargin;
- (void)setEmptyMessage:(id)fp8;
- (id)emptyMessage;
- (void)showErrorMessage:(id)fp8;
- (void)showEmpty;
- (void)showLoading;
@end

