/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSURL;

@interface YTStream : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSURL *URL_;
    int format_;
    BOOL encrypted_;
}

+ (int)selectAdSenseiTagOnWiFi:(BOOL)fp8;
+ (id)selectStreamForVideo:(id)fp8 onWiFi:(BOOL)fp12;
+ (id)streamWithURL:(id)fp8 format:(int)fp12 encrypted:(BOOL)fp16;
- (BOOL)encrypted;
- (int)format;
- (id)URL;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithURL:(id)fp8 format:(int)fp12 encrypted:(BOOL)fp16;

@end

