/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSMutableArray;

@interface YTSubtitles : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSMutableArray *lines_;
}

- (id)textAtTime:(unsigned int)fp8;
- (void)appendLine:(id)fp8 startTime:(unsigned int)fp12 endTime:(unsigned int)fp16;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)init;

@end

