/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSString, NSURL;

@interface YTSubscription : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *username_;
    NSString *displayName_;
    NSString *channelID_;
    int type_;
    NSURL *editURL_;
    NSURL *thumbnailURL_;
    unsigned long long countHint_;
    NSDate *publishedDate_;
    NSDate *updatedDate_;
}

- (id)updatedDate;
- (id)publishedDate;
- (unsigned long long)countHint;
- (id)thumbnailURL;
- (id)editURL;
- (int)type;
- (id)channelID;
- (id)displayName;
- (id)username;
- (BOOL)isSupported;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithUsername:(id)fp8 displayName:(id)fp12 channelID:(id)fp16 type:(int)fp20 publishedDate:(id)fp24 updatedDate:(id)fp28 countHint:(unsigned long long)fp32 editURL:(id)fp40 thumbnailURL:(id)fp44;

@end

