/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class NSString, UIControl<YTSubscribeSwitchProtocol>, YTSubscription;

@interface YTSubscribeSwitchController : _AVAudioSessionCategoryPlayback
{
    NSString *channelID_;
    YTSubscription *subscription_;
    id <YTNavigation> navigation_;
    id <YTServices> services_;
    BOOL subscribeSwitchVisible_;
    UIControl<YTSubscribeSwitchProtocol> *subscribeSwitch_;
    int subscribeState_;
}

- (int)subscribeState;
- (id)subscribeSwitch;
- (void)restoreToSubscribedState;
- (void)didPressSubscribeSwitch:(id)fp8;
- (void)unsubscribe:(id)fp8;
- (void)subscribe:(id)fp8;
- (void)loadSubscriptionWithChannelID:(id)fp8;
- (void)didReceiveSubscriptionChangeNotification:(id)fp8;
- (void)setSubscribeState:(int)fp8;
- (void)setSubscribeSwitch:(id)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithChannelID:(id)fp8 navigation:(id)fp12 services:(id)fp16;
- (id)initWithChannelID:(id)fp8 subscription:(id)fp12 navigation:(id)fp16 services:(id)fp20;

@end

