/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseService.h"

@class NSCache, YTSubtitlesParser, YTSubtitlesTracksParser;

@interface YTSubtitlesService : YTBaseService
{
    YTSubtitlesTracksParser *subtitlesTracksParser_;
    YTSubtitlesParser *subtitlesParser_;
    NSCache *subtitlesTracksCache_;
    NSCache *subtitlesCache_;
}

- (id)cacheKeyForVideoID:(id)fp8 track:(id)fp12;
- (void)makeSubtitlesRequestWithVideoID:(id)fp8 track:(id)fp12 responseBlock:(id)fp(null) errorBlock:(void)fp16;
- (void)makeSubtitlesTracksRequest:(id)fp8 responseBlock:(id)fp(null) errorBlock:(void)fp12;
- (void)dealloc;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12;

@end

