/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTTBParser.h"

@class NSDictionary;

@interface YTSubscriptionParser : YTTBParser
{
    NSDictionary *typesLookup_;
}

- (id)parseElement:(id)fp8 error:(id *)fp12;
- (void)dealloc;
- (id)init;

@end

