/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface YTSubtitlesTrack : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSString *languageCode_;
    NSString *languageName_;
    NSString *trackName_;
}

- (id)trackName;
- (id)languageName;
- (id)languageCode;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithLanguageCode:(id)fp8 languageName:(id)fp12 trackName:(id)fp16;

@end

