/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPResourceLoader;

@interface YTTabTitlesView : _AVAudioSessionCategoryPlayback
{
    GIPResourceLoader *resourceLoader_;
    id <YTTabTitlesViewDelegate> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)didPressButton:(id)fp8;
- (id)buttonWithTitle:(id)fp8;
- (void)arrangeButtons;
- (float)preferredHeight;
- (int)currentTitleIndex;
- (void)setCurrentTitleIndex:(int)fp8;
- (int)titleCount;
- (void)addTitle:(id)fp8;
- (void)insertTitle:(id)fp8 atIndex:(int)fp12;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8;

@end

