/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface YTTBXMLElement : _AVAudioSessionCategoryPlayback
{
    struct _TBXMLElement *element_;
}

+ (id)description:(struct _TBXMLElement *)fp8 indent:(int)fp12;
- (id)description;
- (id)textForChildNamed:(id)fp8 withAttributeNamed:(id)fp12 ofValue:(id)fp16;
- (id)valueOfAttributeNamed:(id)fp8 ofChildNamed:(id)fp12 withAttributeNamed:(id)fp16 ofValue:(id)fp20;
- (id)valueOfAttributeNamed:(id)fp8 ofChildNamed:(id)fp12 ofChildNamed:(id)fp16;
- (id)valueOfAttributeNamed:(id)fp8 ofChildNamed:(id)fp12;
- (id)URLValueOfAttributeNamed:(id)fp8;
- (id)valueOfAttributeNamed:(id)fp8;
- (BOOL)hasAttributeNamed:(id)fp8;
- (id)URLForChildNamed:(id)fp8;
- (id)URLForChildNamed:(id)fp8 ofChildNamed:(id)fp12;
- (id)textForChildNamed:(id)fp8 ofChildNamed:(id)fp12;
- (id)textForChildNamed:(id)fp8;
- (id)text;
- (id)name;
- (void)iterateChildrenNamed:(id)fp8 withBlock:(id)fp(null);
- (void)iterateChildrenWithBlock:(id)fp(null);
- (BOOL)hasChildNamed:(id)fp8;
- (id)nextSiblingNamed:(id)fp8;
- (id)nextSibling;
- (id)firstChild;
- (id)childElementNamed:(id)fp8 withAttributeNamed:(id)fp12 ofValue:(id)fp16;
- (id)childElementNamed:(id)fp8;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (id)initWithElement:(struct _TBXMLElement *)fp8;

@end

