/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UIImageView, UIView;

@interface YTTopShadowView : _AVAudioSessionCategoryPlayback
{
    UIImageView *topShadow_;
    UIView *view_;
}

+ (id)topShadowViewWithView:(id)fp8 loader:(id)fp12;
- (id)view;
- (void)setScrollsToTop:(BOOL)fp8;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (id)initWithView:(id)fp8 loader:(id)fp12;

@end

