/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@interface YTUtils : _AVAudioSessionCategoryPlayback
{
}

+ (id)isoFixForCountryCode:(id)fp8;
+ (void)printStackTrace;
+ (BOOL)isRetinaDisplay;
+ (void)runBlock:(id)fp(null) withDelay:(void)fp8;
+ (id)generateCPN;
+ (id)systemVersion;
+ (id)appID;
+ (id)appVersion;
+ (void)setNeedsLayoutRecursivelyFromView:(id)fp8;
+ (id)styledNavigationController:(id)fp8;
+ (BOOL)viewContainsVisibleSubview:(id)fp8;
+ (id)systemCountryCode;
+ (id)userCountryCode;
+ (id)userLanguageCode;
+ (id)localizedCount:(unsigned long long)fp8;
+ (id)localizedDateSinceNow:(id)fp8;
+ (id)stringWithDurationSeconds:(int)fp8;
+ (BOOL)isDateRecent:(id)fp8;
+ (id)dateFormatter;

@end

