/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSArray, NSMutableArray, NSString, NSURL, YTVideo;

@interface YTVASTAd : _AVAudioSessionCategoryPlayback <NSCopying>
{
    NSMutableArray *impressionURLs_;
    NSURL *streamURL_;
    YTVideo *adVideo_;
    NSURL *clickthroughURL_;
    NSString *adFormatValue_;
    NSArray *startPingURLs_;
    NSArray *firstQuartilePingURLs_;
    NSArray *midpointPingURLs_;
    NSArray *thirdQuartilePingURLs_;
    NSArray *completePingURLs_;
    NSArray *closePingURLs_;
    NSArray *pausePingURLs_;
    NSArray *resumePingURLs_;
    NSArray *mutePingURLs_;
    NSArray *fullscreenPingURLs_;
    NSArray *skipShownPingURLs_;
    NSArray *skipPingURLs_;
    NSArray *engagedPingURLs_;
    NSArray *videoTitleClickedPingURLs_;
    NSArray *clickthroughPingURLs_;
}

+ (id)dummyAdWithImpressionURLs:(id)fp8;
- (id)clickthroughPingURLs;
- (id)videoTitleClickedPingURLs;
- (id)engagedPingURLs;
- (id)skipPingURLs;
- (id)skipShownPingURLs;
- (id)fullscreenPingURLs;
- (id)mutePingURLs;
- (id)resumePingURLs;
- (id)pausePingURLs;
- (id)closePingURLs;
- (id)completePingURLs;
- (id)thirdQuartilePingURLs;
- (id)midpointPingURLs;
- (id)firstQuartilePingURLs;
- (id)startPingURLs;
- (id)adFormatValue;
- (id)clickthroughURL;
- (id)adVideo;
- (id)streamURL;
- (BOOL)isSkippable;
- (BOOL)isDummy;
- (void)addImpressionURLs:(id)fp8;
- (id)impressionURLs;
- (void)setAdFormatValue:(id)fp8;
- (void)setAdVideo:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithStreamURL:(id)fp8 clickthroughURL:(id)fp12 impressionURLs:(id)fp16 startPingURLs:(id)fp20 firstQuartilePingURLs:(id)fp24 midpointPingURLs:(id)fp28 thirdQuartilePingURLs:(id)fp32 completePingURLs:(id)fp36 closePingURLs:(id)fp40 pausePingURLs:(id)fp44 resumePingURLs:(id)fp48 mutePingURLs:(id)fp52 fullscreenPingURLs:(id)fp56 skipShownPingURLs:(id)fp60 skipPingURLs:(id)fp64 engagedPingURLs:(id)fp68 videoTitleClickedPingURLs:(id)fp72 clickthroughPingURLs:(id)fp76;

@end

