/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTFeedController.h"

@interface YTVideosFeedController : YTFeedController
{
    id <YTVideoCellDelegate> cellDelegate_;
    BOOL directAccess_;
    int source_;
}

- (void)feedView:(id)fp8 didSelectEntryAtIndex:(int)fp12;
- (void)updateCell:(id)fp8 forEntry:(id)fp12 animated:(BOOL)fp16;
- (void)handleEntries:(id)fp8;
- (void)setCellDelegate:(id)fp8;
- (id)initWithFeedView:(id)fp8 services:(id)fp12;
- (id)initWithFeedView:(id)fp8 services:(id)fp12 directAccess:(BOOL)fp16 source:(int)fp20;

@end

