/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

#import "NSCopying-Protocol.h"

@class NSArray, NSDate, NSDictionary, NSSet, NSString, NSURL, YTVideoPro, YTVideoState;

@interface YTVideo : _AVAudioSessionCategoryPlayback <NSCopying>
{
    BOOL monetized_;
    NSSet *monetizedCountries_;
    NSSet *allowedCountries_;
    NSSet *deniedCountries_;
    NSString *ID_;
    NSString *title_;
    NSString *videoDescription_;
    NSString *uploaderDisplayName_;
    NSString *uploaderChannelID_;
    NSDate *uploadedDate_;
    NSDate *publishedDate_;
    unsigned int duration_;
    unsigned long long viewCount_;
    unsigned long long likesCount_;
    unsigned long long dislikesCount_;
    YTVideoState *state_;
    NSArray *streams_;
    NSDictionary *thumbnailURLs_;
    NSURL *subtitlesTracksURL_;
    BOOL commentsAllowed_;
    NSURL *commentsURL_;
    unsigned long long commentsCountHint_;
    NSURL *relatedURL_;
    BOOL claimed_;
    NSString *categoryLabel_;
    NSString *categoryTerm_;
    NSArray *tags_;
    BOOL adultContent_;
    YTVideoPro *videoPro_;
}

- (id)videoPro;
- (BOOL)isAdultContent;
- (id)tags;
- (id)categoryTerm;
- (id)categoryLabel;
- (BOOL)isClaimed;
- (id)relatedURL;
- (unsigned long long)commentsCountHint;
- (id)commentsURL;
- (BOOL)isCommentsAllowed;
- (id)subtitlesTracksURL;
- (id)thumbnailURLs;
- (id)streams;
- (id)state;
- (unsigned long long)dislikesCount;
- (unsigned long long)likesCount;
- (unsigned long long)viewCount;
- (unsigned int)duration;
- (id)publishedDate;
- (id)uploadedDate;
- (id)uploaderChannelID;
- (id)uploaderDisplayName;
- (id)videoDescription;
- (id)title;
- (id)ID;
- (BOOL)isEncrypted;
- (BOOL)isMonetizedWithCountryCode:(id)fp8;
- (BOOL)couldBeMusic;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithID:(id)fp8 title:(id)fp12 description:(id)fp16 uploaderDisplayName:(id)fp20 uploaderChannelID:(id)fp24 uploadedDate:(id)fp28 publishedDate:(id)fp32 duration:(unsigned int)fp36 viewCount:(unsigned long long)fp40 likesCount:(unsigned long long)fp48 dislikesCount:(unsigned long long)fp56 state:(id)fp64 streams:(id)fp68 thumbnailURLs:(id)fp72 subtitlesTracksURL:(id)fp76 commentsAllowed:(BOOL)fp80 commentsURL:(id)fp84 commentsCountHint:(unsigned long long)fp88 relatedURL:(id)fp96 claimed:(BOOL)fp100 monetized:(BOOL)fp104 monetizedCountries:(id)fp108 allowedCountries:(id)fp112 deniedCountries:(id)fp116 categoryLabel:(id)fp120 categoryTerm:(id)fp124 tags:(id)fp128 adultContent:(BOOL)fp132 videoPro:(id)fp136;

@end

