/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseService.h"

@class GTMOAuth2Authentication, NSDate, NSMutableArray, NSString, YTDeviceAuthorizer, YTVideo;

@interface YTVideoStatsService : YTBaseService
{
    YTVideo *video_;
    NSString *adFormat_;
    int source_;
    YTDeviceAuthorizer *deviceAuthorizer_;
    NSDate *start_;
    double timeBetweenPings_;
    unsigned int CVSSPingCounter_;
    NSMutableArray *playbackRanges_;
    double currentMediaTime_;
    BOOL didProgressLogged;
    NSString *CPN_;
    BOOL playbackReported_;
    BOOL delayedPlaybackReported_;
    BOOL playing_;
    BOOL rateLimit_;
    GTMOAuth2Authentication *userAuth_;
    double playbackDelay_;
}

- (void)playbackDidProgressNotification:(id)fp8;
- (void)playbackDidStopNotification:(id)fp8;
- (void)playbackDidPauseNotification:(id)fp8;
- (void)playbackDidPlayNotification:(id)fp8;
- (void)setCommonVSSParametersToBuilder:(id)fp8;
- (void)setPlaybackParametersToBuilder:(id)fp8;
- (void)performSignedHTTPRequestWithBuilder:(id)fp8;
- (void)reportVSSWatchTimeWithWallTime:(double)fp8;
- (void)reportVSSDelayedPlayback;
- (void)reportVSSPlayback;
- (id)featureWithSource:(int)fp8;
- (id)unescapedURLWithBuilder:(id)fp8;
- (void)stopObservers;
- (void)startObservers;
- (void)addRangeStartMediaTime:(double)fp8;
- (void)addRangeEndMediaTime:(double)fp8;
- (id)resetPlaybackRanges;
- (void)setStartAndEndTimesToBuilder:(id)fp8;
- (void)pingCVSS;
- (double)wallTimeWithStartDate:(id)fp8;
- (void)flush;
- (void)startWithCPN:(id)fp8 video:(id)fp12 adFormat:(id)fp16 playbackDelay:(double)fp20 userAuth:(id)fp28;
- (void)stop;
- (void)dealloc;
- (id)initWithOperationQueue:(id)fp8 HTTPFetcherService:(id)fp12;
- (id)initWithSource:(int)fp8 deviceAuthorizer:(id)fp12 operationQueue:(id)fp16 HTTPFetcherService:(id)fp20;

@end

