/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class GIPResourceLoader, UILabel, YTAttributedTextLabel, YTSparkleBarView;

@interface YTVideoInfoCell_iPhone : _AVAudioSessionCategoryPlayback
{
    UILabel *titleLabel_;
    YTAttributedTextLabel *likesDislikesLabel_;
    YTAttributedTextLabel *viewCountLabel_;
    YTAttributedTextLabel *dateAndDescriptionLabel_;
    YTSparkleBarView *sparkleBar_;
    GIPResourceLoader *resourceLoader_;
    BOOL layoutChanged_;
}

- (void)setVideo:(id)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)fp8;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (void)setShowSeparator:(BOOL)fp8;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)fp8 resourceLoader:(id)fp12;

@end

