/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "YTBaseViewController_iPhone.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class YTFeedController, YTVideo, YTVideoInfoTableController_iPhone, YTVideosFeedController;

@interface YTVideoViewController_iPhone : YTBaseViewController_iPhone <UIGestureRecognizerDelegate>
{
    YTVideo *video_;
    YTVideoInfoTableController_iPhone *videoDetailsController_;
    YTVideosFeedController *suggestionsController_;
    YTFeedController *commentsController_;
}

- (id)videoView;
- (void)loadRelatedVideosAndPlaylistWithID:(id)fp8;
- (void)setBranding:(id)fp8;
- (void)setVideo:(id)fp8;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;

@end

