/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AVAudioSessionCategoryPlayback.h"

@class UITableView, UIView, YTStageView;

@interface YTWatchView_iPad : _AVAudioSessionCategoryPlayback
{
    UIView *separator_;
    YTStageView *stageView_;
    UITableView *videoInfoView_;
}

- (id)videoInfoView;
- (id)stageView;
- (BOOL)viewHierarchyContainsStageView;
- (struct CGRect)stageViewFrame;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithResourceLoader:(id)fp8;

@end

